#!/usr/bin/env python3
"""Check public documentation structure, safety, and repository references.

Capability coverage remains owned by ``scripts/capabilities/check``.  This
module deliberately does not parse or reinterpret the P00 registry.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import sys
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import unquote

sys.dont_write_bytecode = True

DEV_SCRIPT_DIR = Path(__file__).resolve().parents[1] / "dev"
if str(DEV_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(DEV_SCRIPT_DIR))

from atomic_output import AtomicOutputError, atomic_replace_regular


EXCLUDED_DIRECTORIES = {
    ".git",
    ".next",
    ".pnpm-store",
    ".tools",
    "build",
    "dist",
    "node_modules",
    "vendor",
}
LINK_PATTERN = re.compile(
    r"!?\[[^\]]*\]\(\s*(?P<target><[^>]+>|[^\s)]+)(?:\s+(?:\"[^\"]*\"|'[^']*'))?\s*\)"
)
REFERENCE_LINK_PATTERN = re.compile(
    r"(?m)^\s*\[[^\]]+\]:\s*(?P<target><[^>]+>|\S+)"
)
HEADING_PATTERN = re.compile(r"(?m)^#{1,6}\s+(.+?)\s*#*\s*$")
ADR_TITLE_PATTERN = re.compile(r"(?m)^#\s+ADR-(?P<id>\d{3}):\s+.+$")
ADR_REFERENCE_PATTERN = re.compile(r"\bADR-(?P<id>\d{3})\b")
MEMORY_HEADING_PATTERN = re.compile(r"(?m)^##\s+(?P<date>\d{4}-\d{2}-\d{2})\s+[—-]\s+.+$")
MAKE_REFERENCE_PATTERN = re.compile(r"\bmake\s+(?P<target>[A-Za-z0-9][A-Za-z0-9_.-]*)")
MAKE_TARGET_PATTERN = re.compile(r"(?m)^(?P<targets>[A-Za-z0-9_.%/-]+(?:\s+[A-Za-z0-9_.%/-]+)*)\s*:(?![=])")
GENERATED_MARKERS = (
    "do not edit",
    "generated file",
    "generated by",
    '"_generated"',
    '"generated_by"',
    '"generator"',
)
STALE_CLAIMS = re.compile(r"(?i)\b(?:no SaaS|one consent|SQLite in dev|latest)\b")


@dataclass(frozen=True)
class Finding:
    check: str
    path: str
    line: int
    message: str

    def as_dict(self) -> dict[str, object]:
        return {
            "check": self.check,
            "line": self.line,
            "message": self.message,
            "path": self.path,
        }


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _walk_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for directory, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        directory_names[:] = sorted(name for name in directory_names if name not in EXCLUDED_DIRECTORIES)
        current = Path(directory)
        files.extend(
            current / name
            for name in sorted(file_names)
            if not (current / name).is_symlink() and (current / name).is_file()
        )
    return sorted(files)


def _line(content: str, offset: int) -> int:
    return content.count("\n", 0, offset) + 1


def _strip_markdown_fences(content: str) -> str:
    result = list(content)
    for match in re.finditer(r"(?ms)^\s*(```|~~~).*?^\s*\1\s*$", content):
        for index in range(match.start(), match.end()):
            if result[index] != "\n":
                result[index] = " "
    return "".join(result)


def _strip_markdown_code(content: str) -> str:
    without_blocks = _strip_markdown_fences(content)
    result = list(without_blocks)
    for match in re.finditer(r"(?<!`)`[^`\n]+`(?!`)", without_blocks):
        for index in range(match.start(), match.end()):
            result[index] = " "
    return "".join(result)


def _slug(value: str) -> str:
    value = re.sub(r"<[^>]+>", "", value)
    value = re.sub(r"[`*_~]", "", value).strip().lower()
    value = re.sub(r"[^\w\s-]", "", value, flags=re.UNICODE)
    return re.sub(r"[\s-]+", "-", value).strip("-")


def _anchors(path: Path) -> set[str]:
    try:
        content = _strip_markdown_code(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError):
        return set()
    seen: dict[str, int] = {}
    anchors: set[str] = set()
    for heading in HEADING_PATTERN.finditer(content):
        base = _slug(heading.group(1))
        if not base:
            continue
        occurrence = seen.get(base, 0)
        anchors.add(base if occurrence == 0 else f"{base}-{occurrence}")
        seen[base] = occurrence + 1
    return anchors


def _link_findings(root: Path, markdown_files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    anchor_cache: dict[Path, set[str]] = {}
    for path in markdown_files:
        try:
            raw = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        content = _strip_markdown_code(raw)
        matches = [*LINK_PATTERN.finditer(content), *REFERENCE_LINK_PATTERN.finditer(content)]
        for match in matches:
            target = match.group("target").strip("<>")
            if not target or target.startswith(("https://", "http://", "mailto:", "tel:")):
                continue
            if re.match(r"^[A-Za-z][A-Za-z0-9+.-]*:", target):
                continue
            path_part, separator, fragment = target.partition("#")
            decoded = unquote(path_part)
            target_path = path if not decoded else (path.parent / decoded).resolve(strict=False)
            line = _line(content, match.start("target"))
            rel = _relative(root, path)
            try:
                target_path.relative_to(root.resolve())
            except ValueError:
                findings.append(
                    Finding("relative-links", rel, line, f"link escapes repository: {target}")
                )
                continue
            if not target_path.exists():
                findings.append(Finding("relative-links", rel, line, f"missing link target: {target}"))
                continue
            if separator and fragment and target_path.is_file() and target_path.suffix.lower() == ".md":
                anchors = anchor_cache.setdefault(target_path, _anchors(target_path))
                if _slug(unquote(fragment)) not in anchors:
                    findings.append(
                        Finding("relative-links", rel, line, f"missing Markdown anchor: {target}")
                    )
    return findings


def _adr_findings(root: Path, markdown_files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    adr_root = root / "docs" / "adr"
    accepted: dict[str, list[Path]] = {}
    known: set[str] = set()
    if adr_root.is_dir():
        for path in sorted(adr_root.glob("[0-9][0-9][0-9][0-9]-*.md")):
            if path.name == "0000-template.md":
                continue
            content = path.read_text(encoding="utf-8")
            title = ADR_TITLE_PATTERN.search(content)
            rel = _relative(root, path)
            if title is None:
                findings.append(Finding("adr-ids", rel, 1, "ADR file lacks canonical ADR-NNN title"))
                continue
            identifier = title.group("id")
            known.add(identifier)
            filename_identifier = f"{int(path.name[:4]):03d}"
            if identifier != filename_identifier:
                findings.append(
                    Finding(
                        "adr-ids",
                        rel,
                        _line(content, title.start()),
                        f"title ADR-{identifier} does not match filename ID {filename_identifier}",
                    )
                )
            if re.search(r"(?mi)^-\s*Status:\s*Accepted(?:\s|$)", content):
                accepted.setdefault(identifier, []).append(path)
    for identifier, paths in sorted(accepted.items()):
        if len(paths) > 1:
            for path in paths:
                findings.append(
                    Finding("adr-ids", _relative(root, path), 1, f"duplicate accepted ADR-{identifier}")
                )
    for path in markdown_files:
        content = _strip_markdown_fences(path.read_text(encoding="utf-8"))
        if path.name == "0000-template.md":
            continue
        for match in ADR_REFERENCE_PATTERN.finditer(content):
            if match.group("id") not in known:
                findings.append(
                    Finding(
                        "adr-ids",
                        _relative(root, path),
                        _line(content, match.start()),
                        f"reference to unknown ADR-{match.group('id')}",
                    )
                )
    return findings


def _claude_findings(root: Path) -> list[Finding]:
    path = root / "CLAUDE.md"
    if not path.is_file():
        return [Finding("claude-pointer", "CLAUDE.md", 1, "approved compatibility pointer is missing")]
    content = path.read_text(encoding="utf-8")
    findings: list[Finding] = []
    if "(./AGENTS.md)" not in content:
        findings.append(Finding("claude-pointer", "CLAUDE.md", 1, "must link to ./AGENTS.md"))
    if re.search(r"(?m)^##+\s", content):
        findings.append(Finding("claude-pointer", "CLAUDE.md", 1, "must not contain an independent rule set"))
    if "```" in content or "~~~" in content:
        findings.append(Finding("claude-pointer", "CLAUDE.md", 1, "must remain a prose pointer, not commands"))
    if len(content.splitlines()) > 12:
        findings.append(Finding("claude-pointer", "CLAUDE.md", 1, "pointer exceeds the 12-line compatibility limit"))
    return findings


SENSITIVE_PATTERNS = (
    (
        "private-paths",
        re.compile(r"(?:^|[\s`'\"(])(?:/Users/[^/\s]+|/home/[^/\s]+|[A-Za-z]:\\Users\\[^\\\s]+)"),
        "private absolute home path",
    ),
    (
        "secrets",
        re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
        "AWS access-key-shaped value",
    ),
    (
        "secrets",
        re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
        "private key material",
    ),
    (
        "secrets",
        re.compile(r"\b(?:gh[oprsu]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{30,}|xox[baprs]-[A-Za-z0-9-]{20,})\b"),
        "provider-token-shaped value",
    ),
    (
        "secrets",
        re.compile(r"\b(?:mongodb(?:\+srv)?|postgres(?:ql)?)://[^\s/:@]+:[^\s/@]+@", re.I),
        "database URI containing credentials",
    ),
    (
        "customer-identifiers",
        re.compile(
            r"(?i)\b(?:customer|tenant)[_ -]?(?:id|name)\s*[:=]\s*[\"']?(?!redacted|example|sample|unknown|none)[A-Za-z0-9][A-Za-z0-9_.-]{5,}"
        ),
        "literal customer identifier",
    ),
)


def _safety_findings(root: Path, files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    for path in files:
        if path.suffix.lower() not in {".md", ".json", ".yaml", ".yml", ".toml", ".txt"}:
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        rel = _relative(root, path)
        for check, pattern, message in SENSITIVE_PATTERNS:
            for match in pattern.finditer(content):
                findings.append(Finding(check, rel, _line(content, match.start()), message))
        if rel in {"README.md", "PRODUCT.md", "AGENTS.md", "CLAUDE.md", "MEMORY.md"} or rel.startswith("docs/"):
            for match in STALE_CLAIMS.finditer(content):
                findings.append(
                    Finding("stale-claims", rel, _line(content, match.start()), f"stale claim token: {match.group(0)}")
                )
    return findings


def _generated_findings(root: Path, files: list[Path]) -> list[Finding]:
    findings: list[Finding] = []
    generated_root = root / "docs" / "generated"
    for path in files:
        try:
            path.relative_to(generated_root)
        except ValueError:
            continue
        content = path.read_text(encoding="utf-8", errors="replace")[:4096].lower()
        if not any(marker in content for marker in GENERATED_MARKERS):
            findings.append(
                Finding(
                    "generated-markers",
                    _relative(root, path),
                    1,
                    "generated documentation lacks a recognized generator/do-not-edit marker",
                )
            )
    return findings


def _generated_symlink_findings(root: Path) -> list[Finding]:
    """Reject every alias in the generated-document authority path."""
    generated_root = root / "docs" / "generated"
    findings: list[Finding] = []
    for parent in (root / "docs", generated_root):
        if os.path.lexists(parent) and parent.is_symlink():
            findings.append(
                Finding(
                    "generated-symlinks",
                    parent.relative_to(root).as_posix(),
                    1,
                    "generated documentation path component must be a real directory, never a symlink",
                )
            )
            return findings
    if not generated_root.is_dir():
        return findings
    for directory, directory_names, file_names in os.walk(
        generated_root, topdown=True, followlinks=False
    ):
        current = Path(directory)
        for name in sorted([*directory_names, *file_names]):
            candidate = current / name
            if candidate.is_symlink():
                findings.append(
                    Finding(
                        "generated-symlinks",
                        candidate.relative_to(root).as_posix(),
                        1,
                        "generated documentation entries must be regular repository paths, never symlinks",
                    )
                )
        directory_names[:] = sorted(
            name for name in directory_names if not (current / name).is_symlink()
        )
    return findings


def _memory_findings(root: Path) -> list[Finding]:
    path = root / "MEMORY.md"
    if not path.is_file():
        return [Finding("memory", "MEMORY.md", 1, "durable memory file is missing")]
    content = path.read_text(encoding="utf-8")
    findings: list[Finding] = []
    lines = content.splitlines()
    if len(lines) > 200:
        findings.append(Finding("memory", "MEMORY.md", 1, f"active memory has {len(lines)} lines; maximum is 200"))
    dates = [match.group("date") for match in MEMORY_HEADING_PATTERN.finditer(content)]
    if dates != sorted(dates, reverse=True):
        findings.append(Finding("memory", "MEMORY.md", 1, "dated entries are not newest-first"))
    if not dates:
        findings.append(Finding("memory", "MEMORY.md", 1, "no dated durable entries found"))
    return findings


def _make_targets(root: Path) -> set[str]:
    targets: set[str] = set()
    paths = [root / "Makefile"]
    packet_root = root / "mk" / "packets"
    if packet_root.is_dir():
        paths.extend(sorted(packet_root.glob("*.mk")))
    for path in paths:
        if not path.is_file():
            continue
        content = path.read_text(encoding="utf-8")
        for match in MAKE_TARGET_PATTERN.finditer(content):
            targets.update(item for item in match.group("targets").split() if "%" not in item)
    return targets


def _command_tokens(command: str) -> list[str]:
    try:
        tokens = shlex.split(command, comments=True, posix=True)
    except ValueError:
        tokens = command.split()
    targets: list[str] = []
    skip_flag_value = False
    for token in tokens:
        if token in {"&&", "||", "|", ";"}:
            break
        if skip_flag_value:
            skip_flag_value = False
            continue
        if token in {"-C", "--directory", "-f", "--file", "--makefile"}:
            skip_flag_value = True
            continue
        if token.startswith("-") or "=" in token:
            continue
        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_.-]*", token):
            targets.append(token)
        else:
            break
    return targets


def _make_references(content: str) -> list[tuple[str, int]]:
    references: set[tuple[str, int]] = set()
    # The first token after every prose occurrence is a public target reference.
    for match in MAKE_REFERENCE_PATTERN.finditer(content):
        references.add((match.group("target"), _line(content, match.start())))
    # Inline and fenced command examples can invoke several targets in one make
    # process. All of them are part of the documented command contract.
    code_regions = [
        (match.group(1), match.start(1))
        for match in re.finditer(r"`([^`\n]+)`", content)
    ]
    code_regions.extend(
        (match.group("body"), match.start("body"))
        for match in re.finditer(
            r"(?ms)^\s*(?:```|~~~)[^\n]*\n(?P<body>.*?)^\s*(?:```|~~~)\s*$",
            content,
        )
    )
    for region, offset in code_regions:
        for match in re.finditer(r"\bmake\s+(?P<command>[^\n;&|]+)", region):
            line = _line(content, offset + match.start())
            references.update((target, line) for target in _command_tokens(match.group("command")))
    return sorted(references, key=lambda item: (item[1], item[0]))


def _command_findings(root: Path) -> list[Finding]:
    documented = [root / "README.md", root / "AGENTS.md"]
    documented.extend(sorted(root.glob("**/AGENTS.md")))
    targets = _make_targets(root)
    findings: list[Finding] = []
    for path in sorted(set(documented)):
        if not path.is_file():
            continue
        # Public commands are conventionally formatted as inline code, so retain
        # inline spans here. References inside examples are still contractual.
        content = path.read_text(encoding="utf-8")
        for target, line in _make_references(content):
            if target not in targets:
                findings.append(
                    Finding(
                        "public-commands",
                        _relative(root, path),
                        line,
                        f"documented make target is absent: {target}",
                    )
                )
    return findings


def check(root: Path) -> dict[str, object]:
    root = root.resolve()
    files = _walk_files(root)
    markdown_files = [path for path in files if path.suffix.lower() == ".md"]
    findings = [
        *_link_findings(root, markdown_files),
        *_adr_findings(root, markdown_files),
        *_claude_findings(root),
        *_safety_findings(root, files),
        *_generated_symlink_findings(root),
        *_generated_findings(root, files),
        *_memory_findings(root),
        *_command_findings(root),
    ]
    findings = sorted(findings, key=lambda item: (item.check, item.path, item.line, item.message))
    counts: dict[str, int] = {}
    for finding in findings:
        counts[finding.check] = counts.get(finding.check, 0) + 1
    return {
        "checks": {
            "adr_ids": "pass" if not counts.get("adr-ids") else "fail",
            "claude_pointer": "pass" if not counts.get("claude-pointer") else "fail",
            "generated_markers": "pass"
            if not counts.get("generated-markers") and not counts.get("generated-symlinks")
            else "fail",
            "memory": "pass" if not counts.get("memory") else "fail",
            "public_commands": "pass" if not counts.get("public-commands") else "fail",
            "relative_links": "pass" if not counts.get("relative-links") else "fail",
            "safety": "pass"
            if not any(counts.get(key) for key in ("customer-identifiers", "private-paths", "secrets", "stale-claims"))
            else "fail",
        },
        "finding_count": len(findings),
        "findings": [finding.as_dict() for finding in findings],
        "schema_version": "1.0.0",
        "status": "pass" if not findings else "fail",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--json", action="store_true", help="print the deterministic machine report")
    parser.add_argument("--report-output", type=Path, help="write the deterministic JSON report")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    report = check(root)
    if args.report_output:
        try:
            atomic_replace_regular(
                root,
                args.report_output,
                (json.dumps(report, indent=2, sort_keys=True) + "\n").encode("utf-8"),
            )
        except (AtomicOutputError, OSError) as exc:
            print(f"docs check: ERROR: {exc}", file=sys.stderr)
            return 1
    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print(
            f"docs check: {str(report['status']).upper()} "
            f"markdown={len([path for path in _walk_files(root) if path.suffix.lower() == '.md'])} "
            f"findings={report['finding_count']}"
        )
        for finding in report["findings"]:
            print(
                f"ERROR {finding['check']}: {finding['path']}:{finding['line']}: {finding['message']}",
                file=sys.stderr,
            )
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    raise SystemExit(main())
