#!/usr/bin/env python3
"""Adversarial tests for the static architecture checker."""

from __future__ import annotations

import contextlib
import io
import json
import os
import sys
import tempfile
import unittest
from pathlib import Path

sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from architecture_check import check, main as architecture_main


class ArchitectureCheckTests(unittest.TestCase):
    def setUp(self) -> None:
        self.temporary = tempfile.TemporaryDirectory()
        self.root = Path(self.temporary.name)
        self.write("go.mod", "module example.invalid/jumpship\n\ngo 1.25\n")

    def tearDown(self) -> None:
        self.temporary.cleanup()

    def write(self, relative: str, content: str = "") -> Path:
        path = self.root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        return path

    def violations(self) -> list[dict[str, object]]:
        return check(self.root)["forbidden_edge_report"]["violations"]

    def test_scans_generated_build_tagged_and_test_sources(self) -> None:
        self.write("internal/harness/doc.go", "package harness\n")
        self.write(
            "internal/mothership/generated_never.go",
            "//go:build never\n\n// Code generated by fixture. DO NOT EDIT.\n"
            "package mothership\nimport _ \"example.invalid/jumpship/internal/harness\"\n",
        )
        self.write(
            "internal/mothership/mothership_test.go",
            "package mothership_test\nimport _ \"example.invalid/jumpship/internal/harness\"\n",
        )

        violations = self.violations()

        self.assertEqual(1, len(violations))
        self.assertEqual("mothership-narrow-authority", violations[0]["rule"])
        self.assertTrue(violations[0]["direct"])

    def test_rejects_transitively_laundered_import(self) -> None:
        self.write("internal/harness/doc.go", "package harness\n")
        self.write(
            "internal/workspaces/workspaces.go",
            "package workspaces\nimport _ \"example.invalid/jumpship/internal/harness\"\n",
        )
        self.write(
            "cmd/mothership/main.go",
            "package main\nimport _ \"example.invalid/jumpship/internal/workspaces\"\n",
        )

        violation = self.violations()[0]

        self.assertFalse(violation["direct"])
        self.assertEqual(
            ["cmd/mothership", "internal/workspaces", "internal/harness"],
            violation["path"],
        )

    def test_nested_module_cannot_hide_forbidden_package(self) -> None:
        self.write("internal/harness/go.mod", "module example.invalid/harness\n\ngo 1.25\n")
        self.write("internal/harness/doc.go", "package harness\n")
        self.write(
            "cmd/mothership/main.go",
            "package main\nimport _ \"example.invalid/harness\"\n",
        )

        report = check(self.root)

        self.assertEqual(2, len(report["import_graph"]["modules"]))
        self.assertEqual(1, report["forbidden_edge_report"]["count"])

    def test_nested_module_cannot_disguise_guarded_external_provider(self) -> None:
        provider = "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"
        self.write("internal/adapter/go.mod", f"module {provider}\n\ngo 1.25\n")
        self.write("internal/adapter/doc.go", "package adapter\n")
        self.write(
            "internal/engine/engine.go",
            f'package engine\nimport _ "{provider}"\n',
        )

        report = check(self.root)
        violations = report["forbidden_edge_report"]["violations"]

        self.assertEqual(1, len(violations))
        self.assertEqual(f"external:{provider}", violations[0]["target"])

    @unittest.skipIf(not hasattr(os, "symlink"), "platform does not support symlinks")
    def test_rejects_source_symlink_and_repository_escape(self) -> None:
        outside = Path(self.temporary.name).parent / f"{self.root.name}-outside.go"
        outside.write_text("package outside\n", encoding="utf-8")
        try:
            (self.root / "internal").mkdir(exist_ok=True)
            (self.root / "internal" / "escape.go").symlink_to(outside)

            report = check(self.root)

            self.assertEqual("fail", report["status"])
            self.assertEqual("symlink-escape", report["symlink_report"]["violations"][0]["kind"])
        finally:
            outside.unlink(missing_ok=True)

    def test_rejects_web_domain_and_escape_imports(self) -> None:
        self.write(
            "web/src/page.ts",
            "import domain from '../../internal/workspaces/domain';\n"
            "import direct from 'example.invalid/jumpship/internal/workspaces';\n",
        )
        self.write("internal/workspaces/domain.ts", "export default {};\n")

        report = check(self.root)
        violations = report["forbidden_edge_report"]["violations"]

        self.assertEqual(2, len(violations))
        self.assertTrue(all(item["rule"] == "web-presentation-boundary" for item in violations))

    def test_graph_and_report_are_deterministic(self) -> None:
        self.write("internal/contracts/doc.go", "package contracts\n")
        self.write(
            "internal/workspaces/doc.go",
            "package workspaces\nimport _ \"example.invalid/jumpship/internal/contracts\"\n",
        )

        first = json.dumps(check(self.root), sort_keys=True)
        second = json.dumps(check(self.root), sort_keys=True)

        self.assertEqual(first, second)
        self.assertEqual("pass", json.loads(first)["status"])

    @unittest.skipIf(not hasattr(os, "symlink"), "platform does not support symlinks")
    def test_output_writers_refuse_symlink_and_preserve_victim(self) -> None:
        for flag, name in (
            ("--graph-output", "graph"),
            ("--report-output", "report"),
        ):
            with self.subTest(flag=flag):
                victim = self.write(f"{name}-victim.json", '{"authority":"preserve"}\n')
                output = self.root / f"evidence/{name}.json"
                output.parent.mkdir(parents=True, exist_ok=True)
                output.symlink_to(victim)
                errors = io.StringIO()

                with contextlib.redirect_stderr(errors):
                    result = architecture_main(
                        ["--root", str(self.root), flag, f"evidence/{name}.json"]
                    )

                self.assertEqual(1, result)
                self.assertEqual('{"authority":"preserve"}\n', victim.read_text(encoding="utf-8"))
                self.assertTrue(output.is_symlink())
                self.assertIn("non-regular output", errors.getvalue())

    @unittest.skipIf(not hasattr(os, "symlink"), "platform does not support symlinks")
    def test_output_writer_refuses_symlinked_parent(self) -> None:
        alias = self.root / "aliased-evidence"
        alias.mkdir()
        (self.root / "evidence").symlink_to(alias, target_is_directory=True)
        errors = io.StringIO()

        with contextlib.redirect_stderr(errors):
            result = architecture_main(
                ["--root", str(self.root), "--report-output", "evidence/report.json"]
            )

        self.assertEqual(1, result)
        self.assertFalse((alias / "report.json").exists())
        self.assertIn("not a real directory", errors.getvalue())

    def test_output_writer_regenerates_existing_regular_file(self) -> None:
        output = self.write("evidence/report.json", "stale\n")

        result = architecture_main(
            ["--root", str(self.root), "--report-output", "evidence/report.json"]
        )

        self.assertEqual(0, result)
        self.assertEqual("pass", json.loads(output.read_text(encoding="utf-8"))["status"])

    def test_repository_local_toolchains_are_not_source_modules(self) -> None:
        self.write("internal/workspaces/doc.go", "package workspaces\n")
        self.write(".tools/toolchains/go/1.26.5/go.mod", "module bootstrap.invalid/go\n")
        self.write(
            ".tools/toolchains/go/1.26.5/internal/harness/doc.go",
            "package harness\n",
        )

        report = check(self.root)

        self.assertEqual(
            [{"directory": ".", "import_path": "example.invalid/jumpship"}],
            report["import_graph"]["modules"],
        )
        self.assertNotIn(
            ".tools/toolchains/go/1.26.5/internal/harness",
            report["import_graph"]["nodes"],
        )

    def test_comments_and_string_literals_cannot_invent_imports(self) -> None:
        self.write("internal/harness/doc.go", "package harness\n")
        self.write(
            "internal/mothership/doc.go",
            "package mothership\n"
            "// import _ \"example.invalid/jumpship/internal/harness\"\n"
            "const diagnostic = `import _ \"example.invalid/jumpship/internal/harness\"`\n",
        )
        self.write(
            "web/src/page.ts",
            "// import '../../internal/workspaces';\n"
            "const diagnostic = \"import '../../internal/workspaces'\";\n"
            "const template = `import '../../internal/workspaces'`;\n",
        )

        report = check(self.root)

        self.assertEqual("pass", report["status"])
        self.assertEqual(0, report["forbidden_edge_report"]["count"])

    def test_compiler_valid_go_hex_escape_cannot_hide_provider_import(self) -> None:
        self.write("internal/harness/provider/go.mod", "module example.invalid/provider\n\ngo 1.25\n")
        self.write("internal/harness/provider/doc.go", "package provider\n")
        self.write(
            "internal/engine/engine.go",
            'package engine\nimport _ "example.invalid/\\x70rovider"\n',
        )

        report = check(self.root)
        violations = report["forbidden_edge_report"]["violations"]

        self.assertEqual("fail", report["status"])
        self.assertEqual(1, len(violations))
        self.assertEqual("engine-no-model-provider", violations[0]["rule"])
        self.assertEqual("internal/harness/provider", violations[0]["target"])

    def test_go_raw_import_discards_carriage_return_before_boundary_check(self) -> None:
        self.write("internal/harness/provider/doc.go", "package provider\n")
        source = self.root / "internal/engine/escaped.go"
        source.parent.mkdir(parents=True, exist_ok=True)
        source.write_bytes(
            b"package engine\nimport _ `example.invalid/jumpship/internal/harness/\rprovider`\n"
        )

        violations = self.violations()

        self.assertEqual(1, len(violations))
        self.assertEqual("engine-no-model-provider", violations[0]["rule"])

    def test_engine_may_import_typed_harness_ports(self) -> None:
        self.write("internal/harness/ports/doc.go", "package ports\n")
        self.write(
            "internal/engine/engine.go",
            'package engine\nimport _ "example.invalid/jumpship/internal/harness/ports"\n',
        )

        report = check(self.root)

        self.assertEqual("pass", report["status"])
        self.assertEqual(0, report["forbidden_edge_report"]["count"])

    def test_engine_rejects_external_bedrock_provider_import(self) -> None:
        self.write(
            "internal/engine/engine.go",
            'package engine\nimport _ "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"\n',
        )

        report = check(self.root)
        violations = report["forbidden_edge_report"]["violations"]

        self.assertEqual("fail", report["status"])
        self.assertEqual(1, len(violations))
        self.assertEqual("engine-no-model-provider", violations[0]["rule"])
        self.assertEqual(
            "external:github.com/aws/aws-sdk-go-v2/service/bedrockruntime",
            violations[0]["target"],
        )

    def test_engine_rejects_external_database_and_provisioning_imports(self) -> None:
        self.write(
            "internal/engine/engine.go",
            "package engine\nimport (\n"
            '\t_ "github.com/aws/aws-sdk-go-v2/service/cloudformation"\n'
            '\t_ "github.com/jackc/pgx/v5"\n'
            '\t_ "go.mongodb.org/mongo-driver/v2/mongo"\n'
            ")\n",
        )

        violations = self.violations()

        self.assertEqual(3, len(violations))
        self.assertTrue(all(item["rule"] == "engine-typed-data-ports-only" for item in violations))
        self.assertEqual(
            {
                "external:github.com/aws/aws-sdk-go-v2/service/cloudformation",
                "external:github.com/jackc/pgx/v5",
                "external:go.mongodb.org/mongo-driver/v2/mongo",
            },
            {item["target"] for item in violations},
        )

    def test_engine_rejects_local_corridor_source_and_target_drivers(self) -> None:
        self.write("internal/corridors/mongodb_postgres/source/doc.go", "package source\n")
        self.write("internal/corridors/mongodb_postgres/target/doc.go", "package target\n")
        self.write(
            "internal/engine/engine.go",
            "package engine\nimport (\n"
            '\t_ "example.invalid/jumpship/internal/corridors/mongodb_postgres/source"\n'
            '\t_ "example.invalid/jumpship/internal/corridors/mongodb_postgres/target"\n'
            ")\n",
        )

        violations = self.violations()

        self.assertEqual(2, len(violations))
        self.assertTrue(all(item["rule"] == "engine-typed-data-ports-only" for item in violations))
        self.assertEqual(
            {
                "internal/corridors/mongodb_postgres/source",
                "internal/corridors/mongodb_postgres/target",
            },
            {item["target"] for item in violations},
        )

    def test_harness_rejects_external_provisioning_and_database_drivers(self) -> None:
        self.write(
            "internal/harness/runtime.go",
            "package harness\nimport (\n"
            '\t_ "github.com/aws/aws-sdk-go-v2/service/cloudformation"\n'
            '\t_ "go.mongodb.org/mongo-driver/v2/mongo"\n'
            ")\n",
        )

        violations = self.violations()

        self.assertEqual(2, len(violations))
        self.assertTrue(
            all(item["rule"] == "harness-no-provisioning-or-drivers" for item in violations)
        )
        self.assertEqual(
            {
                "external:github.com/aws/aws-sdk-go-v2/service/cloudformation",
                "external:go.mongodb.org/mongo-driver/v2/mongo",
            },
            {item["target"] for item in violations},
        )

    def test_quality_allows_only_explicit_sanitized_trajectory_contract(self) -> None:
        self.write(
            "internal/contracts/quality/sanitizedtrajectory/doc.go",
            "package sanitizedtrajectory\n",
        )
        self.write(
            "internal/quality/quality.go",
            'package quality\nimport _ "example.invalid/jumpship/internal/contracts/quality/sanitizedtrajectory"\n',
        )

        report = check(self.root)

        self.assertEqual("pass", report["status"])
        self.assertEqual(0, report["forbidden_edge_report"]["count"])

    def test_quality_rejects_provider_and_non_sanitized_local_contracts(self) -> None:
        self.write("internal/harness/provider/doc.go", "package provider\n")
        self.write("internal/contracts/quality/rawtrajectory/doc.go", "package rawtrajectory\n")
        self.write(
            "internal/quality/quality.go",
            "package quality\nimport (\n"
            '\t_ "example.invalid/jumpship/internal/harness/provider"\n'
            '\t_ "example.invalid/jumpship/internal/contracts/quality/rawtrajectory"\n'
            '\t_ "go.mongodb.org/mongo-driver/v2/mongo"\n'
            '\t_ "github.com/prometheus/client_golang/prometheus"\n'
            '\t_ "github.com/aws/aws-sdk-go-v2/service/bedrockruntime"\n'
            ")\n",
        )

        violations = self.violations()

        self.assertEqual(5, len(violations))
        self.assertTrue(all(item["rule"] == "quality-sanitized-input-only" for item in violations))
        self.assertEqual(
            {
                "internal/contracts/quality/rawtrajectory",
                "internal/harness/provider",
                "external:go.mongodb.org/mongo-driver/v2/mongo",
                "external:github.com/prometheus/client_golang/prometheus",
                "external:github.com/aws/aws-sdk-go-v2/service/bedrockruntime",
            },
            {item["target"] for item in violations},
        )

    def test_javascript_escaped_specifiers_cannot_hide_web_escape(self) -> None:
        self.write(
            "web/src/page.ts",
            r"import domain from '..\x2f..\x2finternal/workspaces/domain';" "\n"
            r"import direct from 'example.invalid/jump\u0073hip/internal/workspaces';" "\n",
        )
        self.write("internal/workspaces/domain.ts", "export default {};\n")

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(2, len(violations))
        self.assertTrue(all(item["rule"] == "web-presentation-boundary" for item in violations))

    def test_nonliteral_dynamic_import_and_require_are_denied(self) -> None:
        self.write(
            "web/src/page.ts",
            "const one = import(moduleName);\n"
            "const two = require(moduleName);\n"
            "const three = import('../' + moduleName);\n"
            "const four = require('./' + moduleName);\n"
            "const five = module.require(moduleName);\n"
            "const six = globalThis.require(moduleName);\n",
        )

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(6, len(violations))
        self.assertTrue(all(item["target"].endswith("-dynamic>") for item in violations))

    def test_escaped_and_aliased_require_are_denied(self) -> None:
        self.write(
            "web/src/page.ts",
            r"const direct = requ\u0069re('../../internal/workspaces/domain');" "\n"
            "const load = require;\n"
            "const indirect = load('../../internal/workspaces/domain');\n",
        )

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(2, len(violations))
        self.assertTrue(any(item["target"] == "<require-dynamic>" for item in violations))
        self.assertTrue(
            any(str(item["target"]).startswith("internal/workspaces") for item in violations)
        )

    def test_tsconfig_resolution_fields_cannot_escape_web(self) -> None:
        cases = {
            "baseUrl": (
                '{"compilerOptions":{"baseUrl":"../internal"}}\n',
                "baseUrl escapes",
            ),
            "paths": (
                '{"compilerOptions":{"baseUrl":".","paths":{"@domain/*":["../internal/*"]}}}\n',
                "path alias",
            ),
            "include": (
                '{\n// JSONC is intentional\n"include":["../internal/**/*",],\n}\n',
                "include entry escapes",
            ),
            "reference": (
                '{"references":[{"path":"../internal"}]}\n',
                "project reference escapes",
            ),
            "rootDirs": (
                '{"compilerOptions":{"rootDirs":["src","../internal"]}}\n',
                "rootDirs entry escapes",
            ),
            "typeRoots": (
                '{"compilerOptions":{"typeRoots":["src/types","../internal/types"]}}\n',
                "typeRoots entry escapes",
            ),
            "plugins": (
                '{"compilerOptions":{"plugins":[{"name":"module-resolver"}]}}\n',
                "plugins require",
            ),
        }
        for field, (configuration, expected) in cases.items():
            with self.subTest(field=field):
                self.write("web/tsconfig.json", configuration)

                violations = check(self.root)["forbidden_edge_report"]["violations"]

                self.assertEqual(1, len(violations))
                self.assertEqual("web-configuration-boundary", violations[0]["rule"])
                self.assertIn(expected, violations[0]["explanation"])

    def test_relative_extends_recursively_validates_non_tsconfig_json(self) -> None:
        self.write(
            "web/config/base.json",
            '{"compilerOptions":{"paths":{"@domain/*":["../../internal/*"]}}}\n',
        )
        self.write("web/tsconfig.json", '{"extends":"./config/base.json"}\n')

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(1, len(violations))
        self.assertEqual("web/config/base.json", violations[0]["source_file"])
        self.assertIn("path alias", violations[0]["explanation"])

    def test_relative_extends_cycle_fails_closed(self) -> None:
        self.write("web/config/a.json", '{"extends":"./b.json"}\n')
        self.write("web/config/b.json", '{"extends":"./a.json"}\n')
        self.write("web/tsconfig.json", '{"extends":"./config/a.json"}\n')

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(1, len(violations))
        self.assertIn("cycle", violations[0]["explanation"])

    def test_jsconfig_and_unverified_bundler_aliases_are_checked(self) -> None:
        self.write(
            "web/jsconfig.json",
            '{"compilerOptions":{"baseUrl":".","paths":{"@domain/*":["../internal/*"]}}}\n',
        )
        self.write(
            "web/next.config.mjs",
            "export default { turbopack: { resolveAlias: { '@x': './src/x' } } };\n",
        )

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(2, len(violations))
        self.assertTrue(all(item["rule"] == "web-configuration-boundary" for item in violations))
        self.assertTrue(
            any(item["target"] == "<unverified-bundler-alias>" for item in violations)
        )

    def test_computed_bundler_alias_hook_is_rejected(self) -> None:
        self.write(
            "web/next.config.mjs",
            "const key = 'ali' + 'as';\n"
            "export default { webpack(config) { config.resolve[key] = "
            "{'@domain': '../internal'}; return config; } };\n",
        )

        violations = check(self.root)["forbidden_edge_report"]["violations"]

        self.assertEqual(1, len(violations))
        self.assertEqual("<unverified-bundler-alias>", violations[0]["target"])


if __name__ == "__main__":
    unittest.main()
