// Code generated by internal/contracts/codegen/generate.py from cell.proto; DO NOT EDIT.
// Dependency-free net/http adapters implement these frozen Connect protocol seams.
package cellv1

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"net/http"
	"net/url"
	"strings"
	"sync"
)

type Metadata map[string][]string

type RPCRequest[T any] struct {
	Message *T
	Header  Metadata
}

type RPCResponse[T any] struct {
	Message *T
	Header  Metadata
	Trailer Metadata
}

type SupervisorControlClient interface {
	Connect(context.Context, Metadata) (SupervisorControlConnectClient, error)
}

type SupervisorControlConnectClient interface {
	Context() context.Context
	Send(*SupervisorFrame) error
	CloseRequest() error
	Receive() (*SupervisorFrame, error)
	ResponseHeader() (Metadata, error)
	ResponseTrailer() Metadata
	CloseResponse() error
}

type CellCertificateRecoveryClient interface {
	Renew(context.Context, *RPCRequest[RenewRequest]) (*RPCResponse[RenewResponse], error)
}

const (
	connectProtocolVersion   = "1"
	connectUnaryContentType  = "application/json"
	connectStreamContentType = "application/connect+json"
	maxConnectMessageBytes   = 2 * 1024 * 1024
	maxConnectErrorBytes     = 64 * 1024
	connectFlagCompressed    = byte(0x01)
	connectFlagEndStream     = byte(0x02)
)

// ConnectError is a protocol error returned by a Connect server. Details is
// retained as raw JSON so callers can opt into service-specific decoding.
type ConnectError struct {
	Code       string
	Message    string
	Details    json.RawMessage
	HTTPStatus int
	Metadata   Metadata
}

func (connectErr *ConnectError) Error() string {
	if connectErr == nil {
		return "<nil>"
	}
	if connectErr.Message == "" {
		return fmt.Sprintf("connect: %s", connectErr.Code)
	}
	return fmt.Sprintf("connect: %s: %s", connectErr.Code, connectErr.Message)
}

type connectErrorPayload struct {
	Code    string          `json:"code"`
	Message string          `json:"message"`
	Details json.RawMessage `json:"details,omitempty"`
}

type connectEndStream struct {
	Error    *connectErrorPayload `json:"error,omitempty"`
	Metadata Metadata             `json:"metadata,omitempty"`
}

type connectHTTPClient struct {
	baseURL    *url.URL
	httpClient *http.Client
}

func newConnectHTTPClient(baseURL string, httpClient *http.Client) (*connectHTTPClient, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("parse Connect base URL: %w", err)
	}
	if (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" {
		return nil, fmt.Errorf("Connect base URL must be an absolute HTTP(S) URL")
	}
	if parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return nil, fmt.Errorf("Connect base URL must not contain credentials, a query, or a fragment")
	}
	base := *parsed
	base.Path = strings.TrimRight(base.Path, "/") + "/"
	base.RawPath = ""
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &connectHTTPClient{baseURL: &base, httpClient: httpClient}, nil
}

func (client *connectHTTPClient) procedureURL(procedure string) string {
	relative := &url.URL{Path: strings.TrimPrefix(procedure, "/")}
	return client.baseURL.ResolveReference(relative).String()
}

func cloneMetadata(source map[string][]string) Metadata {
	if len(source) == 0 {
		return nil
	}
	clone := make(Metadata, len(source))
	for key, values := range source {
		clone[key] = append([]string(nil), values...)
	}
	return clone
}

func mergeMetadata(first, second Metadata) Metadata {
	merged := cloneMetadata(first)
	if merged == nil && len(second) != 0 {
		merged = make(Metadata, len(second))
	}
	for key, values := range second {
		merged[key] = append(merged[key], values...)
	}
	return merged
}

func applyMetadata(header http.Header, metadata Metadata) {
	for key, values := range metadata {
		for _, value := range values {
			header.Add(key, value)
		}
	}
}

func requireConnectContentType(response *http.Response, expected string) error {
	mediaType, _, err := mime.ParseMediaType(response.Header.Get("Content-Type"))
	if err != nil || mediaType != expected {
		return fmt.Errorf("connect: unexpected response content type %q", response.Header.Get("Content-Type"))
	}
	return nil
}

func marshalConnectMessage(message any) ([]byte, error) {
	payload, err := json.Marshal(message)
	if err != nil {
		return nil, fmt.Errorf("marshal Connect JSON message: %w", err)
	}
	if len(payload) > maxConnectMessageBytes {
		return nil, fmt.Errorf("connect: message exceeds %d-byte limit", maxConnectMessageBytes)
	}
	return payload, nil
}

func readConnectBody(reader io.Reader, limit int64) ([]byte, error) {
	payload, err := io.ReadAll(io.LimitReader(reader, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(payload)) > limit {
		return nil, fmt.Errorf("connect: response exceeds %d-byte limit", limit)
	}
	return payload, nil
}

func connectErrorFromPayload(payload *connectErrorPayload, status int, metadata Metadata) error {
	if payload == nil {
		return fmt.Errorf("connect: HTTP %d returned no error payload", status)
	}
	code := payload.Code
	if code == "" {
		code = "unknown"
	}
	return &ConnectError{
		Code:       code,
		Message:    payload.Message,
		Details:    append(json.RawMessage(nil), payload.Details...),
		HTTPStatus: status,
		Metadata:   cloneMetadata(metadata),
	}
}

func readConnectHTTPError(response *http.Response) error {
	payload, err := readConnectBody(response.Body, maxConnectErrorBytes)
	metadata := mergeMetadata(cloneMetadata(response.Header), cloneMetadata(response.Trailer))
	if err != nil {
		return fmt.Errorf("connect: read HTTP %d error response: %w", response.StatusCode, err)
	}
	var decoded connectErrorPayload
	if err := json.Unmarshal(payload, &decoded); err != nil {
		return fmt.Errorf("connect: malformed HTTP %d error response: %w", response.StatusCode, err)
	}
	return connectErrorFromPayload(&decoded, response.StatusCode, metadata)
}

func callConnectUnary[Request any, Response any](
	ctx context.Context,
	transport *connectHTTPClient,
	procedure string,
	request *RPCRequest[Request],
) (*RPCResponse[Response], error) {
	if request == nil || request.Message == nil {
		return nil, fmt.Errorf("connect: unary request message is required")
	}
	payload, err := marshalConnectMessage(request.Message)
	if err != nil {
		return nil, err
	}
	httpRequest, err := http.NewRequestWithContext(
		ctx,
		http.MethodPost,
		transport.procedureURL(procedure),
		bytes.NewReader(payload),
	)
	if err != nil {
		return nil, fmt.Errorf("create Connect unary request: %w", err)
	}
	applyMetadata(httpRequest.Header, request.Header)
	httpRequest.Header.Set("Content-Type", connectUnaryContentType)
	httpRequest.Header.Set("Accept", connectUnaryContentType)
	httpRequest.Header.Set("Connect-Protocol-Version", connectProtocolVersion)
	response, err := transport.httpClient.Do(httpRequest)
	if err != nil {
		return nil, fmt.Errorf("execute Connect unary request: %w", err)
	}
	defer response.Body.Close()
	if response.StatusCode != http.StatusOK {
		return nil, readConnectHTTPError(response)
	}
	if err := requireConnectContentType(response, connectUnaryContentType); err != nil {
		return nil, err
	}
	responsePayload, err := readConnectBody(response.Body, maxConnectMessageBytes)
	if err != nil {
		return nil, fmt.Errorf("read Connect unary response: %w", err)
	}
	var message Response
	if err := json.Unmarshal(responsePayload, &message); err != nil {
		return nil, fmt.Errorf("decode Connect unary response: %w", err)
	}
	return &RPCResponse[Response]{
		Message: &message,
		Header:  cloneMetadata(response.Header),
		Trailer: cloneMetadata(response.Trailer),
	}, nil
}

type connectHTTPResult struct {
	response *http.Response
	err      error
}

type connectBidiStream[Request any, Response any] struct {
	ctx               context.Context
	cancel            context.CancelFunc
	requestWriter     *io.PipeWriter
	responseResult    <-chan connectHTTPResult
	sendMu            sync.Mutex
	requestClosed     bool
	requestCloseErr   error
	responseOnce      sync.Once
	response          *http.Response
	responseErr       error
	responseHeader    Metadata
	receiveMu         sync.Mutex
	responseEnded     bool
	trailerMu         sync.RWMutex
	responseTrailer   Metadata
	closeResponseOnce sync.Once
	closeResponseErr  error
}

func newConnectBidiStream[Request any, Response any](
	ctx context.Context,
	transport *connectHTTPClient,
	procedure string,
	metadata Metadata,
) (*connectBidiStream[Request, Response], error) {
	if ctx == nil {
		return nil, fmt.Errorf("connect: stream context is required")
	}
	streamContext, cancel := context.WithCancel(ctx)
	requestReader, requestWriter := io.Pipe()
	httpRequest, err := http.NewRequestWithContext(
		streamContext,
		http.MethodPost,
		transport.procedureURL(procedure),
		requestReader,
	)
	if err != nil {
		cancel()
		requestReader.Close()
		requestWriter.Close()
		return nil, fmt.Errorf("create Connect stream request: %w", err)
	}
	applyMetadata(httpRequest.Header, metadata)
	httpRequest.Header.Set("Content-Type", connectStreamContentType)
	httpRequest.Header.Set("Accept", connectStreamContentType)
	httpRequest.Header.Set("Connect-Protocol-Version", connectProtocolVersion)
	result := make(chan connectHTTPResult, 1)
	go func() {
		response, requestErr := transport.httpClient.Do(httpRequest)
		result <- connectHTTPResult{response: response, err: requestErr}
	}()
	return &connectBidiStream[Request, Response]{
		ctx:            streamContext,
		cancel:         cancel,
		requestWriter:  requestWriter,
		responseResult: result,
	}, nil
}

func encodeConnectEnvelope(flags byte, payload []byte) ([]byte, error) {
	if len(payload) > maxConnectMessageBytes {
		return nil, fmt.Errorf("connect: message exceeds %d-byte limit", maxConnectMessageBytes)
	}
	envelope := make([]byte, 5+len(payload))
	envelope[0] = flags
	binary.BigEndian.PutUint32(envelope[1:5], uint32(len(payload)))
	copy(envelope[5:], payload)
	return envelope, nil
}

func readConnectEnvelope(reader io.Reader) (byte, []byte, error) {
	var prefix [5]byte
	if _, err := io.ReadFull(reader, prefix[:]); err != nil {
		return 0, nil, err
	}
	length := binary.BigEndian.Uint32(prefix[1:5])
	if uint64(length) > uint64(maxConnectMessageBytes) {
		return 0, nil, fmt.Errorf("connect: message exceeds %d-byte limit", maxConnectMessageBytes)
	}
	payload := make([]byte, int(length))
	if _, err := io.ReadFull(reader, payload); err != nil {
		return 0, nil, err
	}
	return prefix[0], payload, nil
}

func (stream *connectBidiStream[Request, Response]) Context() context.Context {
	return stream.ctx
}

func (stream *connectBidiStream[Request, Response]) Send(message *Request) error {
	if message == nil {
		return fmt.Errorf("connect: stream request message is required")
	}
	payload, err := marshalConnectMessage(message)
	if err != nil {
		return err
	}
	envelope, err := encodeConnectEnvelope(0, payload)
	if err != nil {
		return err
	}
	stream.sendMu.Lock()
	defer stream.sendMu.Unlock()
	if stream.requestClosed {
		return io.ErrClosedPipe
	}
	if err := stream.ctx.Err(); err != nil {
		return err
	}
	if _, err := stream.requestWriter.Write(envelope); err != nil {
		return fmt.Errorf("write Connect request envelope: %w", err)
	}
	return nil
}

func (stream *connectBidiStream[Request, Response]) CloseRequest() error {
	stream.sendMu.Lock()
	defer stream.sendMu.Unlock()
	if !stream.requestClosed {
		stream.requestCloseErr = stream.requestWriter.Close()
		stream.requestClosed = true
	}
	return stream.requestCloseErr
}

func (stream *connectBidiStream[Request, Response]) abortRequest(cause error) {
	stream.sendMu.Lock()
	defer stream.sendMu.Unlock()
	if stream.requestClosed {
		return
	}
	stream.requestCloseErr = stream.requestWriter.CloseWithError(cause)
	stream.requestClosed = true
}

func (stream *connectBidiStream[Request, Response]) awaitResponse() (*http.Response, error) {
	stream.responseOnce.Do(func() {
		result := <-stream.responseResult
		if result.err != nil {
			stream.responseErr = fmt.Errorf("execute Connect stream request: %w", result.err)
			stream.abortRequest(stream.responseErr)
			return
		}
		if result.response == nil {
			stream.responseErr = fmt.Errorf("connect: stream transport returned no response")
			stream.abortRequest(stream.responseErr)
			return
		}
		if result.response.StatusCode != http.StatusOK {
			stream.responseErr = readConnectHTTPError(result.response)
			result.response.Body.Close()
			stream.abortRequest(stream.responseErr)
			return
		}
		if err := requireConnectContentType(result.response, connectStreamContentType); err != nil {
			stream.responseErr = err
			result.response.Body.Close()
			stream.abortRequest(err)
			return
		}
		stream.response = result.response
		stream.responseHeader = cloneMetadata(result.response.Header)
	})
	return stream.response, stream.responseErr
}

func (stream *connectBidiStream[Request, Response]) ResponseHeader() (Metadata, error) {
	if _, err := stream.awaitResponse(); err != nil {
		return nil, err
	}
	return cloneMetadata(stream.responseHeader), nil
}

func (stream *connectBidiStream[Request, Response]) setResponseTrailer(metadata Metadata) {
	stream.trailerMu.Lock()
	stream.responseTrailer = cloneMetadata(metadata)
	stream.trailerMu.Unlock()
}

func (stream *connectBidiStream[Request, Response]) ResponseTrailer() Metadata {
	stream.trailerMu.RLock()
	defer stream.trailerMu.RUnlock()
	return cloneMetadata(stream.responseTrailer)
}

func (stream *connectBidiStream[Request, Response]) Receive() (*Response, error) {
	stream.receiveMu.Lock()
	defer stream.receiveMu.Unlock()
	if stream.responseEnded {
		return nil, io.EOF
	}
	response, err := stream.awaitResponse()
	if err != nil {
		return nil, err
	}
	flags, payload, err := readConnectEnvelope(response.Body)
	if err != nil {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
		return nil, fmt.Errorf("read Connect response envelope: %w", err)
	}
	if flags&connectFlagCompressed != 0 {
		return nil, fmt.Errorf("connect: compressed stream envelopes were not negotiated")
	}
	if flags&^(connectFlagCompressed|connectFlagEndStream) != 0 {
		return nil, fmt.Errorf("connect: unsupported stream envelope flags 0x%02x", flags)
	}
	if flags&connectFlagEndStream != 0 {
		var endStream connectEndStream
		if err := json.Unmarshal(payload, &endStream); err != nil {
			return nil, fmt.Errorf("decode Connect end-stream envelope: %w", err)
		}
		// The end-stream envelope must be the final protocol message. Reading to
		// HTTP EOF both rejects trailing bytes and materializes HTTP trailers.
		if _, err := readConnectBody(response.Body, 0); err != nil {
			return nil, fmt.Errorf("read after Connect end-stream envelope: %w", err)
		}
		stream.responseEnded = true
		stream.setResponseTrailer(
			mergeMetadata(cloneMetadata(response.Trailer), endStream.Metadata),
		)
		_ = stream.CloseRequest()
		if endStream.Error != nil {
			return nil, connectErrorFromPayload(
				endStream.Error,
				http.StatusOK,
				stream.ResponseTrailer(),
			)
		}
		return nil, io.EOF
	}
	var message Response
	if err := json.Unmarshal(payload, &message); err != nil {
		return nil, fmt.Errorf("decode Connect response message: %w", err)
	}
	return &message, nil
}

func (stream *connectBidiStream[Request, Response]) CloseResponse() error {
	stream.closeResponseOnce.Do(func() {
		// Cancellation closes the transport's request reader and guarantees a
		// concurrent blocked Send can release sendMu before the writer is closed.
		stream.cancel()
		if err := stream.CloseRequest(); err != nil {
			stream.closeResponseErr = err
		}
		response, responseErr := stream.awaitResponse()
		if response != nil {
			if err := response.Body.Close(); err != nil && stream.closeResponseErr == nil {
				stream.closeResponseErr = err
			}
		}
		if responseErr != nil && stream.closeResponseErr == nil && stream.ctx.Err() == nil {
			stream.closeResponseErr = responseErr
		}
	})
	return stream.closeResponseErr
}

type supervisorControlHTTPClient struct {
	transport *connectHTTPClient
}

func NewSupervisorControlClient(baseURL string, httpClient *http.Client) (SupervisorControlClient, error) {
	transport, err := newConnectHTTPClient(baseURL, httpClient)
	if err != nil {
		return nil, err
	}
	return &supervisorControlHTTPClient{transport: transport}, nil
}

func (client *supervisorControlHTTPClient) Connect(ctx context.Context, header Metadata) (SupervisorControlConnectClient, error) {
	return newConnectBidiStream[SupervisorFrame, SupervisorFrame](
		ctx,
		client.transport,
		"/jumpship.cell.v1.SupervisorControl/Connect",
		header,
	)
}

type cellCertificateRecoveryHTTPClient struct {
	transport *connectHTTPClient
}

func NewCellCertificateRecoveryClient(baseURL string, httpClient *http.Client) (CellCertificateRecoveryClient, error) {
	transport, err := newConnectHTTPClient(baseURL, httpClient)
	if err != nil {
		return nil, err
	}
	return &cellCertificateRecoveryHTTPClient{transport: transport}, nil
}

func (client *cellCertificateRecoveryHTTPClient) Renew(ctx context.Context, request *RPCRequest[RenewRequest]) (*RPCResponse[RenewResponse], error) {
	return callConnectUnary[RenewRequest, RenewResponse](
		ctx,
		client.transport,
		"/jumpship.cell.v1.CellCertificateRecovery/Renew",
		request,
	)
}
