// Code generated by internal/contracts/codegen/generate.py from cell.proto; DO NOT EDIT.
// These dependency-free structs preserve the frozen wire field numbers and JSON names.
package cellv1

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

type EnvelopeContext struct {
	WorkspaceID           string `protobuf:"bytes,1,opt,name=workspace_id,proto3" json:"workspaceId,omitempty"`
	MigrationID           string `protobuf:"bytes,2,opt,name=migration_id,proto3" json:"migrationId,omitempty"`
	CellID                string `protobuf:"bytes,3,opt,name=cell_id,proto3" json:"cellId,omitempty"`
	CellGeneration        uint64 `protobuf:"varint,4,opt,name=cell_generation,proto3" json:"cellGeneration,omitempty,string"`
	ControlRegionEpoch    uint64 `protobuf:"varint,5,opt,name=control_region_epoch,proto3" json:"controlRegionEpoch,omitempty,string"`
	TargetWriteEpoch      uint64 `protobuf:"varint,6,opt,name=target_write_epoch,proto3" json:"targetWriteEpoch,omitempty,string"`
	ProtocolVersion       string `protobuf:"bytes,7,opt,name=protocol_version,proto3" json:"protocolVersion,omitempty"`
	Sequence              uint64 `protobuf:"varint,8,opt,name=sequence,proto3" json:"sequence,omitempty,string"`
	CausationID           string `protobuf:"bytes,9,opt,name=causation_id,proto3" json:"causationId,omitempty"`
	CorrelationID         string `protobuf:"bytes,10,opt,name=correlation_id,proto3" json:"correlationId,omitempty"`
	TraceID               string `protobuf:"bytes,11,opt,name=trace_id,proto3" json:"traceId,omitempty"`
	SignatureEnvelopeHash string `protobuf:"bytes,12,opt,name=signature_envelope_hash,proto3" json:"signatureEnvelopeHash,omitempty"`
	ChannelBindingHash    string `protobuf:"bytes,13,opt,name=channel_binding_hash,proto3" json:"channelBindingHash,omitempty"`
}

type CellHello struct {
	ReleaseUnitID          string                `protobuf:"bytes,2,opt,name=release_unit_id,proto3" json:"releaseUnitId,omitempty"`
	ReleaseUnitHash        string                `protobuf:"bytes,3,opt,name=release_unit_hash,proto3" json:"releaseUnitHash,omitempty"`
	CellReleaseBindingHash string                `protobuf:"bytes,4,opt,name=cell_release_binding_hash,proto3" json:"cellReleaseBindingHash,omitempty"`
	CapabilityHash         string                `protobuf:"bytes,5,opt,name=capability_hash,proto3" json:"capabilityHash,omitempty"`
	ProjectionRoot         string                `protobuf:"bytes,6,opt,name=projection_root,proto3" json:"projectionRoot,omitempty"`
	ProviderControlHeads   []ProviderControlHead `protobuf:"bytes,7,opt,name=provider_control_heads,proto3" json:"providerControlHeads,omitempty"`
}

type Heartbeat struct {
	LivenessState         string `protobuf:"bytes,2,opt,name=liveness_state,proto3" json:"livenessState,omitempty"`
	HealthRoot            string `protobuf:"bytes,3,opt,name=health_root,proto3" json:"healthRoot,omitempty"`
	CurrentCommandLeaseID string `protobuf:"bytes,4,opt,name=current_command_lease_id,proto3" json:"currentCommandLeaseId,omitempty"`
	ObservedAt            string `protobuf:"bytes,5,opt,name=observed_at,proto3" json:"observedAt,omitempty"`
}

type CommandLease struct {
	CommandLeaseID     string `protobuf:"bytes,2,opt,name=command_lease_id,proto3" json:"commandLeaseId,omitempty"`
	CommandType        string `protobuf:"bytes,3,opt,name=command_type,proto3" json:"commandType,omitempty"`
	CommandPayloadHash string `protobuf:"bytes,4,opt,name=command_payload_hash,proto3" json:"commandPayloadHash,omitempty"`
	PrerequisiteRoot   string `protobuf:"bytes,5,opt,name=prerequisite_root,proto3" json:"prerequisiteRoot,omitempty"`
	NotBefore          string `protobuf:"bytes,6,opt,name=not_before,proto3" json:"notBefore,omitempty"`
	ExpiresAt          string `protobuf:"bytes,7,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
}

type CommandAck struct {
	CommandLeaseID string `protobuf:"bytes,2,opt,name=command_lease_id,proto3" json:"commandLeaseId,omitempty"`
	State          string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ReceiptRoot    string `protobuf:"bytes,4,opt,name=receipt_root,proto3" json:"receiptRoot,omitempty"`
	SafeErrorCode  string `protobuf:"bytes,5,opt,name=safe_error_code,proto3" json:"safeErrorCode,omitempty"`
}

type ProjectionSnapshot struct {
	ProjectionVersion         uint64 `protobuf:"varint,2,opt,name=projection_version,proto3" json:"projectionVersion,omitempty,string"`
	ProjectionRoot            string `protobuf:"bytes,3,opt,name=projection_root,proto3" json:"projectionRoot,omitempty"`
	MigrationPhase            string `protobuf:"bytes,4,opt,name=migration_phase,proto3" json:"migrationPhase,omitempty"`
	TrafficAuthority          string `protobuf:"bytes,5,opt,name=traffic_authority,proto3" json:"trafficAuthority,omitempty"`
	ApplicationAuthorityEpoch uint64 `protobuf:"varint,6,opt,name=application_authority_epoch,proto3" json:"applicationAuthorityEpoch,omitempty,string"`
}

type OperationGrant struct {
	OperationID         string `protobuf:"bytes,2,opt,name=operation_id,proto3" json:"operationId,omitempty"`
	ToolID              string `protobuf:"bytes,3,opt,name=tool_id,proto3" json:"toolId,omitempty"`
	ToolVersion         string `protobuf:"bytes,4,opt,name=tool_version,proto3" json:"toolVersion,omitempty"`
	DescriptorHash      string `protobuf:"bytes,5,opt,name=descriptor_hash,proto3" json:"descriptorHash,omitempty"`
	InputHash           string `protobuf:"bytes,6,opt,name=input_hash,proto3" json:"inputHash,omitempty"`
	GateRoot            string `protobuf:"bytes,7,opt,name=gate_root,proto3" json:"gateRoot,omitempty"`
	CapabilityGrantHash string `protobuf:"bytes,8,opt,name=capability_grant_hash,proto3" json:"capabilityGrantHash,omitempty"`
	ExpiresAt           string `protobuf:"bytes,9,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
}

type ToolReceipt struct {
	OperationID       string `protobuf:"bytes,2,opt,name=operation_id,proto3" json:"operationId,omitempty"`
	ToolID            string `protobuf:"bytes,3,opt,name=tool_id,proto3" json:"toolId,omitempty"`
	DescriptorHash    string `protobuf:"bytes,4,opt,name=descriptor_hash,proto3" json:"descriptorHash,omitempty"`
	InputHash         string `protobuf:"bytes,5,opt,name=input_hash,proto3" json:"inputHash,omitempty"`
	OutputHash        string `protobuf:"bytes,6,opt,name=output_hash,proto3" json:"outputHash,omitempty"`
	Outcome           string `protobuf:"bytes,7,opt,name=outcome,proto3" json:"outcome,omitempty"`
	EffectReceiptRoot string `protobuf:"bytes,8,opt,name=effect_receipt_root,proto3" json:"effectReceiptRoot,omitempty"`
	SafeErrorCode     string `protobuf:"bytes,9,opt,name=safe_error_code,proto3" json:"safeErrorCode,omitempty"`
}

type CellEvent struct {
	EventID      string `protobuf:"bytes,1,opt,name=event_id,proto3" json:"eventId,omitempty"`
	CellSequence uint64 `protobuf:"varint,2,opt,name=cell_sequence,proto3" json:"cellSequence,omitempty,string"`
	EventType    string `protobuf:"bytes,3,opt,name=event_type,proto3" json:"eventType,omitempty"`
	PayloadHash  string `protobuf:"bytes,4,opt,name=payload_hash,proto3" json:"payloadHash,omitempty"`
	DataClass    string `protobuf:"bytes,5,opt,name=data_class,proto3" json:"dataClass,omitempty"`
	PayloadBytes uint64 `protobuf:"varint,6,opt,name=payload_bytes,proto3" json:"payloadBytes,omitempty,string"`
	SafeSummary  string `protobuf:"bytes,7,opt,name=safe_summary,proto3" json:"safeSummary,omitempty"`
}

type CellEventBatch struct {
	BatchID       string      `protobuf:"bytes,2,opt,name=batch_id,proto3" json:"batchId,omitempty"`
	FirstSequence uint64      `protobuf:"varint,3,opt,name=first_sequence,proto3" json:"firstSequence,omitempty,string"`
	LastSequence  uint64      `protobuf:"varint,4,opt,name=last_sequence,proto3" json:"lastSequence,omitempty,string"`
	Events        []CellEvent `protobuf:"bytes,5,opt,name=events,proto3" json:"events,omitempty"`
	BatchRoot     string      `protobuf:"bytes,6,opt,name=batch_root,proto3" json:"batchRoot,omitempty"`
}

type EventAck struct {
	BatchID                 string `protobuf:"bytes,2,opt,name=batch_id,proto3" json:"batchId,omitempty"`
	AcceptedThroughSequence uint64 `protobuf:"varint,3,opt,name=accepted_through_sequence,proto3" json:"acceptedThroughSequence,omitempty,string"`
	InboxReceiptRoot        string `protobuf:"bytes,4,opt,name=inbox_receipt_root,proto3" json:"inboxReceiptRoot,omitempty"`
}

type EvidenceAccessRequest struct {
	RequestID            string `protobuf:"bytes,2,opt,name=request_id,proto3" json:"requestId,omitempty"`
	ArtifactHandle       string `protobuf:"bytes,3,opt,name=artifact_handle,proto3" json:"artifactHandle,omitempty"`
	ActorID              string `protobuf:"bytes,4,opt,name=actor_id,proto3" json:"actorId,omitempty"`
	Purpose              string `protobuf:"bytes,5,opt,name=purpose,proto3" json:"purpose,omitempty"`
	RangeStart           uint64 `protobuf:"varint,6,opt,name=range_start,proto3" json:"rangeStart,omitempty,string"`
	RangeLength          uint64 `protobuf:"varint,7,opt,name=range_length,proto3" json:"rangeLength,omitempty,string"`
	ExpectedArtifactHash string `protobuf:"bytes,8,opt,name=expected_artifact_hash,proto3" json:"expectedArtifactHash,omitempty"`
	ExpiresAt            string `protobuf:"bytes,9,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
}

type EvidenceAccessReceipt struct {
	RequestID         string `protobuf:"bytes,2,opt,name=request_id,proto3" json:"requestId,omitempty"`
	IssuanceNonceHash string `protobuf:"bytes,3,opt,name=issuance_nonce_hash,proto3" json:"issuanceNonceHash,omitempty"`
	AccessPolicyHash  string `protobuf:"bytes,4,opt,name=access_policy_hash,proto3" json:"accessPolicyHash,omitempty"`
	Outcome           string `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	AccessReceiptRoot string `protobuf:"bytes,6,opt,name=access_receipt_root,proto3" json:"accessReceiptRoot,omitempty"`
}

type CredentialLeaseRequest struct {
	RequestID          string `protobuf:"bytes,2,opt,name=request_id,proto3" json:"requestId,omitempty"`
	CredentialHandle   string `protobuf:"bytes,3,opt,name=credential_handle,proto3" json:"credentialHandle,omitempty"`
	OperationID        string `protobuf:"bytes,4,opt,name=operation_id,proto3" json:"operationId,omitempty"`
	ToolDescriptorHash string `protobuf:"bytes,5,opt,name=tool_descriptor_hash,proto3" json:"toolDescriptorHash,omitempty"`
	Purpose            string `protobuf:"bytes,6,opt,name=purpose,proto3" json:"purpose,omitempty"`
	ExpiresAt          string `protobuf:"bytes,7,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
}

type CredentialLeaseReceipt struct {
	RequestID             string `protobuf:"bytes,2,opt,name=request_id,proto3" json:"requestId,omitempty"`
	LeaseID               string `protobuf:"bytes,3,opt,name=lease_id,proto3" json:"leaseId,omitempty"`
	CredentialVersionHash string `protobuf:"bytes,4,opt,name=credential_version_hash,proto3" json:"credentialVersionHash,omitempty"`
	Outcome               string `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	LeaseReceiptRoot      string `protobuf:"bytes,6,opt,name=lease_receipt_root,proto3" json:"leaseReceiptRoot,omitempty"`
}

type RecoveryPointer struct {
	RecoveryPointerID    string `protobuf:"bytes,2,opt,name=recovery_pointer_id,proto3" json:"recoveryPointerId,omitempty"`
	CheckpointRoot       string `protobuf:"bytes,3,opt,name=checkpoint_root,proto3" json:"checkpointRoot,omitempty"`
	CheckpointSequence   uint64 `protobuf:"varint,4,opt,name=checkpoint_sequence,proto3" json:"checkpointSequence,omitempty,string"`
	RecoveryManifestHash string `protobuf:"bytes,5,opt,name=recovery_manifest_hash,proto3" json:"recoveryManifestHash,omitempty"`
	ObservedAt           string `protobuf:"bytes,6,opt,name=observed_at,proto3" json:"observedAt,omitempty"`
}

type ProviderControlHead struct {
	ProviderDataUseRecordID    string `protobuf:"bytes,1,opt,name=provider_data_use_record_id,proto3" json:"providerDataUseRecordId,omitempty"`
	ProviderDataUseRecordHash  string `protobuf:"bytes,2,opt,name=provider_data_use_record_hash,proto3" json:"providerDataUseRecordHash,omitempty"`
	ProviderReviewID           string `protobuf:"bytes,3,opt,name=provider_review_id,proto3" json:"providerReviewId,omitempty"`
	ProviderReviewHash         string `protobuf:"bytes,4,opt,name=provider_review_hash,proto3" json:"providerReviewHash,omitempty"`
	ProviderStatusID           string `protobuf:"bytes,5,opt,name=provider_status_id,proto3" json:"providerStatusId,omitempty"`
	ProviderStatusHash         string `protobuf:"bytes,6,opt,name=provider_status_hash,proto3" json:"providerStatusHash,omitempty"`
	ProviderTransitionID       string `protobuf:"bytes,7,opt,name=provider_transition_id,proto3" json:"providerTransitionId,omitempty"`
	ProviderTransitionHash     string `protobuf:"bytes,8,opt,name=provider_transition_hash,proto3" json:"providerTransitionHash,omitempty"`
	ProviderTransitionSequence uint64 `protobuf:"varint,9,opt,name=provider_transition_sequence,proto3" json:"providerTransitionSequence,omitempty,string"`
	PublicKeyRegistryID        string `protobuf:"bytes,10,opt,name=public_key_registry_id,proto3" json:"publicKeyRegistryId,omitempty"`
	PublicKeyRegistryHash      string `protobuf:"bytes,11,opt,name=public_key_registry_hash,proto3" json:"publicKeyRegistryHash,omitempty"`
	RouteHoldID                string `protobuf:"bytes,12,opt,name=route_hold_id,proto3" json:"routeHoldId,omitempty"`
	RouteHoldHash              string `protobuf:"bytes,13,opt,name=route_hold_hash,proto3" json:"routeHoldHash,omitempty"`
	ProviderUseLeaseID         string `protobuf:"bytes,14,opt,name=provider_use_lease_id,proto3" json:"providerUseLeaseId,omitempty"`
	ProviderUseLeaseHash       string `protobuf:"bytes,15,opt,name=provider_use_lease_hash,proto3" json:"providerUseLeaseHash,omitempty"`
}

type ProviderEvidenceTransitionDelivery struct {
	DeliveryID                string `protobuf:"bytes,2,opt,name=delivery_id,proto3" json:"deliveryId,omitempty"`
	CellReleaseBindingHash    string `protobuf:"bytes,3,opt,name=cell_release_binding_hash,proto3" json:"cellReleaseBindingHash,omitempty"`
	ProviderDataUseRecordID   string `protobuf:"bytes,4,opt,name=provider_data_use_record_id,proto3" json:"providerDataUseRecordId,omitempty"`
	ProviderDataUseRecordHash string `protobuf:"bytes,5,opt,name=provider_data_use_record_hash,proto3" json:"providerDataUseRecordHash,omitempty"`
	TransitionID              string `protobuf:"bytes,6,opt,name=transition_id,proto3" json:"transitionId,omitempty"`
	TransitionHash            string `protobuf:"bytes,7,opt,name=transition_hash,proto3" json:"transitionHash,omitempty"`
	TransitionSequence        uint64 `protobuf:"varint,8,opt,name=transition_sequence,proto3" json:"transitionSequence,omitempty,string"`
	PredecessorTransitionHash string `protobuf:"bytes,9,opt,name=predecessor_transition_hash,proto3" json:"predecessorTransitionHash,omitempty"`
	EmbeddedReviewHash        string `protobuf:"bytes,10,opt,name=embedded_review_hash,proto3" json:"embeddedReviewHash,omitempty"`
	EmbeddedStatusHash        string `protobuf:"bytes,11,opt,name=embedded_status_hash,proto3" json:"embeddedStatusHash,omitempty"`
	TransitionObjectKey       string `protobuf:"bytes,12,opt,name=transition_object_key,proto3" json:"transitionObjectKey,omitempty"`
	SignatureEnvelopeHash     string `protobuf:"bytes,13,opt,name=signature_envelope_hash,proto3" json:"signatureEnvelopeHash,omitempty"`
	PublicKeyRegistryID       string `protobuf:"bytes,14,opt,name=public_key_registry_id,proto3" json:"publicKeyRegistryId,omitempty"`
	PublicKeyRegistryHash     string `protobuf:"bytes,15,opt,name=public_key_registry_hash,proto3" json:"publicKeyRegistryHash,omitempty"`
	RegistryPredecessorHash   string `protobuf:"bytes,16,opt,name=registry_predecessor_hash,proto3" json:"registryPredecessorHash,omitempty"`
}

type ProviderRouteHoldFrame struct {
	HoldID                    string `protobuf:"bytes,2,opt,name=hold_id,proto3" json:"holdId,omitempty"`
	HoldHash                  string `protobuf:"bytes,3,opt,name=hold_hash,proto3" json:"holdHash,omitempty"`
	ProviderDataUseRecordID   string `protobuf:"bytes,4,opt,name=provider_data_use_record_id,proto3" json:"providerDataUseRecordId,omitempty"`
	TransitionID              string `protobuf:"bytes,5,opt,name=transition_id,proto3" json:"transitionId,omitempty"`
	CellReleaseBindingHash    string `protobuf:"bytes,6,opt,name=cell_release_binding_hash,proto3" json:"cellReleaseBindingHash,omitempty"`
	State                     string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	MaximumPreHoldLeaseExpiry string `protobuf:"bytes,8,opt,name=maximum_pre_hold_lease_expiry,proto3" json:"maximumPreHoldLeaseExpiry,omitempty"`
	SafeReasonCode            string `protobuf:"bytes,9,opt,name=safe_reason_code,proto3" json:"safeReasonCode,omitempty"`
}

type ProviderUseLeaseFrame struct {
	LeaseID                    string `protobuf:"bytes,2,opt,name=lease_id,proto3" json:"leaseId,omitempty"`
	ReservationID              string `protobuf:"bytes,3,opt,name=reservation_id,proto3" json:"reservationId,omitempty"`
	CellID                     string `protobuf:"bytes,4,opt,name=cell_id,proto3" json:"cellId,omitempty"`
	CellGeneration             uint64 `protobuf:"varint,5,opt,name=cell_generation,proto3" json:"cellGeneration,omitempty,string"`
	CellReleaseBindingHash     string `protobuf:"bytes,6,opt,name=cell_release_binding_hash,proto3" json:"cellReleaseBindingHash,omitempty"`
	ProviderDataUseRecordID    string `protobuf:"bytes,7,opt,name=provider_data_use_record_id,proto3" json:"providerDataUseRecordId,omitempty"`
	ProviderDataUseRecordHash  string `protobuf:"bytes,8,opt,name=provider_data_use_record_hash,proto3" json:"providerDataUseRecordHash,omitempty"`
	AcceptedTransitionID       string `protobuf:"bytes,9,opt,name=accepted_transition_id,proto3" json:"acceptedTransitionId,omitempty"`
	AcceptedTransitionSequence uint64 `protobuf:"varint,10,opt,name=accepted_transition_sequence,proto3" json:"acceptedTransitionSequence,omitempty,string"`
	AcceptedStatusHash         string `protobuf:"bytes,11,opt,name=accepted_status_hash,proto3" json:"acceptedStatusHash,omitempty"`
	AgentBundleID              string `protobuf:"bytes,12,opt,name=agent_bundle_id,proto3" json:"agentBundleId,omitempty"`
	AgentBundleHash            string `protobuf:"bytes,13,opt,name=agent_bundle_hash,proto3" json:"agentBundleHash,omitempty"`
	ReleaseUnitID              string `protobuf:"bytes,14,opt,name=release_unit_id,proto3" json:"releaseUnitId,omitempty"`
	ReleaseUnitHash            string `protobuf:"bytes,15,opt,name=release_unit_hash,proto3" json:"releaseUnitHash,omitempty"`
	ControlEpoch               uint64 `protobuf:"varint,16,opt,name=control_epoch,proto3" json:"controlEpoch,omitempty,string"`
	NoUnresolvedBindingHold    bool   `protobuf:"varint,17,opt,name=no_unresolved_binding_hold,proto3" json:"noUnresolvedBindingHold,omitempty"`
	IssuedAt                   string `protobuf:"bytes,18,opt,name=issued_at,proto3" json:"issuedAt,omitempty"`
	ExpiresAt                  string `protobuf:"bytes,19,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
	TtlSeconds                 uint32 `protobuf:"varint,20,opt,name=ttl_seconds,proto3" json:"ttlSeconds,omitempty"`
	NonceHash                  string `protobuf:"bytes,21,opt,name=nonce_hash,proto3" json:"nonceHash,omitempty"`
	SignaturePurpose           string `protobuf:"bytes,22,opt,name=signature_purpose,proto3" json:"signaturePurpose,omitempty"`
	SignatureEnvelopeHash      string `protobuf:"bytes,23,opt,name=signature_envelope_hash,proto3" json:"signatureEnvelopeHash,omitempty"`
}

type ProviderControlAck struct {
	DeliveryID            string `protobuf:"bytes,2,opt,name=delivery_id,proto3" json:"deliveryId,omitempty"`
	TransitionID          string `protobuf:"bytes,3,opt,name=transition_id,proto3" json:"transitionId,omitempty"`
	TransitionHash        string `protobuf:"bytes,4,opt,name=transition_hash,proto3" json:"transitionHash,omitempty"`
	RouteHoldID           string `protobuf:"bytes,5,opt,name=route_hold_id,proto3" json:"routeHoldId,omitempty"`
	AcceptedHeadHash      string `protobuf:"bytes,6,opt,name=accepted_head_hash,proto3" json:"acceptedHeadHash,omitempty"`
	State                 string `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	AcceptedAt            string `protobuf:"bytes,8,opt,name=accepted_at,proto3" json:"acceptedAt,omitempty"`
	SignatureEnvelopeHash string `protobuf:"bytes,9,opt,name=signature_envelope_hash,proto3" json:"signatureEnvelopeHash,omitempty"`
}

type SupervisorFrame struct {
	Context *EnvelopeContext       `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Frame   SupervisorFrameVariant `json:"-"`
}

type RenewRequest struct {
	Context                   *EnvelopeContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	FailoverManifestID        string           `protobuf:"bytes,2,opt,name=failover_manifest_id,proto3" json:"failoverManifestId,omitempty"`
	FailoverManifestHash      string           `protobuf:"bytes,3,opt,name=failover_manifest_hash,proto3" json:"failoverManifestHash,omitempty"`
	PriorControlRegionEpoch   uint64           `protobuf:"varint,4,opt,name=prior_control_region_epoch,proto3" json:"priorControlRegionEpoch,omitempty,string"`
	CurrentControlRegionEpoch uint64           `protobuf:"varint,5,opt,name=current_control_region_epoch,proto3" json:"currentControlRegionEpoch,omitempty,string"`
	OldCertificateSerial      string           `protobuf:"bytes,6,opt,name=old_certificate_serial,proto3" json:"oldCertificateSerial,omitempty"`
	CsrDerSHA256              string           `protobuf:"bytes,7,opt,name=csr_der_sha256,proto3" json:"csrDerSha256,omitempty"`
	CsrDer                    []byte           `protobuf:"bytes,8,opt,name=csr_der,proto3" json:"csrDer,omitempty"`
	InstanceIdentityHash      string           `protobuf:"bytes,9,opt,name=instance_identity_hash,proto3" json:"instanceIdentityHash,omitempty"`
}

type RenewResponse struct {
	Context             *EnvelopeContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	RequestID           string           `protobuf:"bytes,2,opt,name=request_id,proto3" json:"requestId,omitempty"`
	PollSecret          string           `protobuf:"bytes,3,opt,name=poll_secret,proto3" json:"pollSecret,omitempty"`
	PollSecretHash      string           `protobuf:"bytes,4,opt,name=poll_secret_hash,proto3" json:"pollSecretHash,omitempty"`
	ExpiresAt           string           `protobuf:"bytes,5,opt,name=expires_at,proto3" json:"expiresAt,omitempty"`
	RecoveryReceiptRoot string           `protobuf:"bytes,6,opt,name=recovery_receipt_root,proto3" json:"recoveryReceiptRoot,omitempty"`
}

func decodeProtoJSONObject(messageName string, data []byte) (map[string]json.RawMessage, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	opening, err := decoder.Token()
	if err != nil {
		return nil, fmt.Errorf("decode %s JSON object: %w", messageName, err)
	}
	if delimiter, ok := opening.(json.Delim); !ok || delimiter != '{' {
		return nil, fmt.Errorf("decode %s JSON object: expected object", messageName)
	}
	object := make(map[string]json.RawMessage)
	for decoder.More() {
		fieldToken, err := decoder.Token()
		if err != nil {
			return nil, fmt.Errorf("decode %s JSON field: %w", messageName, err)
		}
		field, ok := fieldToken.(string)
		if !ok {
			return nil, fmt.Errorf("decode %s JSON field: expected field name", messageName)
		}
		if _, duplicate := object[field]; duplicate {
			return nil, fmt.Errorf("%s contains duplicate field %q", messageName, field)
		}
		var payload json.RawMessage
		if err := decoder.Decode(&payload); err != nil {
			return nil, fmt.Errorf("decode %s.%s: %w", messageName, field, err)
		}
		object[field] = payload
	}
	closing, err := decoder.Token()
	if err != nil {
		return nil, fmt.Errorf("decode %s JSON object: %w", messageName, err)
	}
	if delimiter, ok := closing.(json.Delim); !ok || delimiter != '}' {
		return nil, fmt.Errorf("decode %s JSON object: expected closing delimiter", messageName)
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return nil, fmt.Errorf("decode %s JSON object: trailing value", messageName)
		}
		return nil, fmt.Errorf("decode %s JSON object: %w", messageName, err)
	}
	return object, nil
}

func normalizeProtoJSONFields(messageName string, object map[string]json.RawMessage, aliases map[string]string) (map[string]json.RawMessage, error) {
	normalized := make(map[string]json.RawMessage, len(object))
	for field, payload := range object {
		canonical, ok := aliases[field]
		if !ok {
			return nil, fmt.Errorf("%s contains unknown field %q", messageName, field)
		}
		if _, duplicate := normalized[canonical]; duplicate {
			return nil, fmt.Errorf("%s contains duplicate spellings for field %q", messageName, canonical)
		}
		normalized[canonical] = payload
	}
	return normalized, nil
}

type envelopeContextJSONAlias EnvelopeContext

func (message *EnvelopeContext) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *EnvelopeContext")
	}
	object, err := decodeProtoJSONObject("EnvelopeContext", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"EnvelopeContext",
		object,
		map[string]string{
			"workspaceId":             "workspaceId",
			"workspace_id":            "workspaceId",
			"migrationId":             "migrationId",
			"migration_id":            "migrationId",
			"cellId":                  "cellId",
			"cell_id":                 "cellId",
			"cellGeneration":          "cellGeneration",
			"cell_generation":         "cellGeneration",
			"controlRegionEpoch":      "controlRegionEpoch",
			"control_region_epoch":    "controlRegionEpoch",
			"targetWriteEpoch":        "targetWriteEpoch",
			"target_write_epoch":      "targetWriteEpoch",
			"protocolVersion":         "protocolVersion",
			"protocol_version":        "protocolVersion",
			"sequence":                "sequence",
			"causationId":             "causationId",
			"causation_id":            "causationId",
			"correlationId":           "correlationId",
			"correlation_id":          "correlationId",
			"traceId":                 "traceId",
			"trace_id":                "traceId",
			"signatureEnvelopeHash":   "signatureEnvelopeHash",
			"signature_envelope_hash": "signatureEnvelopeHash",
			"channelBindingHash":      "channelBindingHash",
			"channel_binding_hash":    "channelBindingHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize EnvelopeContext JSON: %w", err)
	}
	var decoded envelopeContextJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode EnvelopeContext: %w", err)
	}
	*message = EnvelopeContext(decoded)
	return nil
}

type cellHelloJSONAlias CellHello

func (message *CellHello) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CellHello")
	}
	object, err := decodeProtoJSONObject("CellHello", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CellHello",
		object,
		map[string]string{
			"releaseUnitId":             "releaseUnitId",
			"release_unit_id":           "releaseUnitId",
			"releaseUnitHash":           "releaseUnitHash",
			"release_unit_hash":         "releaseUnitHash",
			"cellReleaseBindingHash":    "cellReleaseBindingHash",
			"cell_release_binding_hash": "cellReleaseBindingHash",
			"capabilityHash":            "capabilityHash",
			"capability_hash":           "capabilityHash",
			"projectionRoot":            "projectionRoot",
			"projection_root":           "projectionRoot",
			"providerControlHeads":      "providerControlHeads",
			"provider_control_heads":    "providerControlHeads",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CellHello JSON: %w", err)
	}
	var decoded cellHelloJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CellHello: %w", err)
	}
	*message = CellHello(decoded)
	return nil
}

type heartbeatJSONAlias Heartbeat

func (message *Heartbeat) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *Heartbeat")
	}
	object, err := decodeProtoJSONObject("Heartbeat", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"Heartbeat",
		object,
		map[string]string{
			"livenessState":            "livenessState",
			"liveness_state":           "livenessState",
			"healthRoot":               "healthRoot",
			"health_root":              "healthRoot",
			"currentCommandLeaseId":    "currentCommandLeaseId",
			"current_command_lease_id": "currentCommandLeaseId",
			"observedAt":               "observedAt",
			"observed_at":              "observedAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize Heartbeat JSON: %w", err)
	}
	var decoded heartbeatJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode Heartbeat: %w", err)
	}
	*message = Heartbeat(decoded)
	return nil
}

type commandLeaseJSONAlias CommandLease

func (message *CommandLease) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CommandLease")
	}
	object, err := decodeProtoJSONObject("CommandLease", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CommandLease",
		object,
		map[string]string{
			"commandLeaseId":       "commandLeaseId",
			"command_lease_id":     "commandLeaseId",
			"commandType":          "commandType",
			"command_type":         "commandType",
			"commandPayloadHash":   "commandPayloadHash",
			"command_payload_hash": "commandPayloadHash",
			"prerequisiteRoot":     "prerequisiteRoot",
			"prerequisite_root":    "prerequisiteRoot",
			"notBefore":            "notBefore",
			"not_before":           "notBefore",
			"expiresAt":            "expiresAt",
			"expires_at":           "expiresAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CommandLease JSON: %w", err)
	}
	var decoded commandLeaseJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CommandLease: %w", err)
	}
	*message = CommandLease(decoded)
	return nil
}

type commandAckJSONAlias CommandAck

func (message *CommandAck) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CommandAck")
	}
	object, err := decodeProtoJSONObject("CommandAck", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CommandAck",
		object,
		map[string]string{
			"commandLeaseId":   "commandLeaseId",
			"command_lease_id": "commandLeaseId",
			"state":            "state",
			"receiptRoot":      "receiptRoot",
			"receipt_root":     "receiptRoot",
			"safeErrorCode":    "safeErrorCode",
			"safe_error_code":  "safeErrorCode",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CommandAck JSON: %w", err)
	}
	var decoded commandAckJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CommandAck: %w", err)
	}
	*message = CommandAck(decoded)
	return nil
}

type projectionSnapshotJSONAlias ProjectionSnapshot

func (message *ProjectionSnapshot) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProjectionSnapshot")
	}
	object, err := decodeProtoJSONObject("ProjectionSnapshot", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProjectionSnapshot",
		object,
		map[string]string{
			"projectionVersion":           "projectionVersion",
			"projection_version":          "projectionVersion",
			"projectionRoot":              "projectionRoot",
			"projection_root":             "projectionRoot",
			"migrationPhase":              "migrationPhase",
			"migration_phase":             "migrationPhase",
			"trafficAuthority":            "trafficAuthority",
			"traffic_authority":           "trafficAuthority",
			"applicationAuthorityEpoch":   "applicationAuthorityEpoch",
			"application_authority_epoch": "applicationAuthorityEpoch",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProjectionSnapshot JSON: %w", err)
	}
	var decoded projectionSnapshotJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProjectionSnapshot: %w", err)
	}
	*message = ProjectionSnapshot(decoded)
	return nil
}

type operationGrantJSONAlias OperationGrant

func (message *OperationGrant) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *OperationGrant")
	}
	object, err := decodeProtoJSONObject("OperationGrant", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"OperationGrant",
		object,
		map[string]string{
			"operationId":           "operationId",
			"operation_id":          "operationId",
			"toolId":                "toolId",
			"tool_id":               "toolId",
			"toolVersion":           "toolVersion",
			"tool_version":          "toolVersion",
			"descriptorHash":        "descriptorHash",
			"descriptor_hash":       "descriptorHash",
			"inputHash":             "inputHash",
			"input_hash":            "inputHash",
			"gateRoot":              "gateRoot",
			"gate_root":             "gateRoot",
			"capabilityGrantHash":   "capabilityGrantHash",
			"capability_grant_hash": "capabilityGrantHash",
			"expiresAt":             "expiresAt",
			"expires_at":            "expiresAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize OperationGrant JSON: %w", err)
	}
	var decoded operationGrantJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode OperationGrant: %w", err)
	}
	*message = OperationGrant(decoded)
	return nil
}

type toolReceiptJSONAlias ToolReceipt

func (message *ToolReceipt) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ToolReceipt")
	}
	object, err := decodeProtoJSONObject("ToolReceipt", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ToolReceipt",
		object,
		map[string]string{
			"operationId":         "operationId",
			"operation_id":        "operationId",
			"toolId":              "toolId",
			"tool_id":             "toolId",
			"descriptorHash":      "descriptorHash",
			"descriptor_hash":     "descriptorHash",
			"inputHash":           "inputHash",
			"input_hash":          "inputHash",
			"outputHash":          "outputHash",
			"output_hash":         "outputHash",
			"outcome":             "outcome",
			"effectReceiptRoot":   "effectReceiptRoot",
			"effect_receipt_root": "effectReceiptRoot",
			"safeErrorCode":       "safeErrorCode",
			"safe_error_code":     "safeErrorCode",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ToolReceipt JSON: %w", err)
	}
	var decoded toolReceiptJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ToolReceipt: %w", err)
	}
	*message = ToolReceipt(decoded)
	return nil
}

type cellEventJSONAlias CellEvent

func (message *CellEvent) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CellEvent")
	}
	object, err := decodeProtoJSONObject("CellEvent", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CellEvent",
		object,
		map[string]string{
			"eventId":       "eventId",
			"event_id":      "eventId",
			"cellSequence":  "cellSequence",
			"cell_sequence": "cellSequence",
			"eventType":     "eventType",
			"event_type":    "eventType",
			"payloadHash":   "payloadHash",
			"payload_hash":  "payloadHash",
			"dataClass":     "dataClass",
			"data_class":    "dataClass",
			"payloadBytes":  "payloadBytes",
			"payload_bytes": "payloadBytes",
			"safeSummary":   "safeSummary",
			"safe_summary":  "safeSummary",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CellEvent JSON: %w", err)
	}
	var decoded cellEventJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CellEvent: %w", err)
	}
	*message = CellEvent(decoded)
	return nil
}

type cellEventBatchJSONAlias CellEventBatch

func (message *CellEventBatch) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CellEventBatch")
	}
	object, err := decodeProtoJSONObject("CellEventBatch", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CellEventBatch",
		object,
		map[string]string{
			"batchId":        "batchId",
			"batch_id":       "batchId",
			"firstSequence":  "firstSequence",
			"first_sequence": "firstSequence",
			"lastSequence":   "lastSequence",
			"last_sequence":  "lastSequence",
			"events":         "events",
			"batchRoot":      "batchRoot",
			"batch_root":     "batchRoot",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CellEventBatch JSON: %w", err)
	}
	var decoded cellEventBatchJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CellEventBatch: %w", err)
	}
	*message = CellEventBatch(decoded)
	return nil
}

type eventAckJSONAlias EventAck

func (message *EventAck) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *EventAck")
	}
	object, err := decodeProtoJSONObject("EventAck", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"EventAck",
		object,
		map[string]string{
			"batchId":                   "batchId",
			"batch_id":                  "batchId",
			"acceptedThroughSequence":   "acceptedThroughSequence",
			"accepted_through_sequence": "acceptedThroughSequence",
			"inboxReceiptRoot":          "inboxReceiptRoot",
			"inbox_receipt_root":        "inboxReceiptRoot",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize EventAck JSON: %w", err)
	}
	var decoded eventAckJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode EventAck: %w", err)
	}
	*message = EventAck(decoded)
	return nil
}

type evidenceAccessRequestJSONAlias EvidenceAccessRequest

func (message *EvidenceAccessRequest) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *EvidenceAccessRequest")
	}
	object, err := decodeProtoJSONObject("EvidenceAccessRequest", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"EvidenceAccessRequest",
		object,
		map[string]string{
			"requestId":              "requestId",
			"request_id":             "requestId",
			"artifactHandle":         "artifactHandle",
			"artifact_handle":        "artifactHandle",
			"actorId":                "actorId",
			"actor_id":               "actorId",
			"purpose":                "purpose",
			"rangeStart":             "rangeStart",
			"range_start":            "rangeStart",
			"rangeLength":            "rangeLength",
			"range_length":           "rangeLength",
			"expectedArtifactHash":   "expectedArtifactHash",
			"expected_artifact_hash": "expectedArtifactHash",
			"expiresAt":              "expiresAt",
			"expires_at":             "expiresAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize EvidenceAccessRequest JSON: %w", err)
	}
	var decoded evidenceAccessRequestJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode EvidenceAccessRequest: %w", err)
	}
	*message = EvidenceAccessRequest(decoded)
	return nil
}

type evidenceAccessReceiptJSONAlias EvidenceAccessReceipt

func (message *EvidenceAccessReceipt) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *EvidenceAccessReceipt")
	}
	object, err := decodeProtoJSONObject("EvidenceAccessReceipt", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"EvidenceAccessReceipt",
		object,
		map[string]string{
			"requestId":           "requestId",
			"request_id":          "requestId",
			"issuanceNonceHash":   "issuanceNonceHash",
			"issuance_nonce_hash": "issuanceNonceHash",
			"accessPolicyHash":    "accessPolicyHash",
			"access_policy_hash":  "accessPolicyHash",
			"outcome":             "outcome",
			"accessReceiptRoot":   "accessReceiptRoot",
			"access_receipt_root": "accessReceiptRoot",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize EvidenceAccessReceipt JSON: %w", err)
	}
	var decoded evidenceAccessReceiptJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode EvidenceAccessReceipt: %w", err)
	}
	*message = EvidenceAccessReceipt(decoded)
	return nil
}

type credentialLeaseRequestJSONAlias CredentialLeaseRequest

func (message *CredentialLeaseRequest) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CredentialLeaseRequest")
	}
	object, err := decodeProtoJSONObject("CredentialLeaseRequest", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CredentialLeaseRequest",
		object,
		map[string]string{
			"requestId":            "requestId",
			"request_id":           "requestId",
			"credentialHandle":     "credentialHandle",
			"credential_handle":    "credentialHandle",
			"operationId":          "operationId",
			"operation_id":         "operationId",
			"toolDescriptorHash":   "toolDescriptorHash",
			"tool_descriptor_hash": "toolDescriptorHash",
			"purpose":              "purpose",
			"expiresAt":            "expiresAt",
			"expires_at":           "expiresAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CredentialLeaseRequest JSON: %w", err)
	}
	var decoded credentialLeaseRequestJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CredentialLeaseRequest: %w", err)
	}
	*message = CredentialLeaseRequest(decoded)
	return nil
}

type credentialLeaseReceiptJSONAlias CredentialLeaseReceipt

func (message *CredentialLeaseReceipt) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *CredentialLeaseReceipt")
	}
	object, err := decodeProtoJSONObject("CredentialLeaseReceipt", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"CredentialLeaseReceipt",
		object,
		map[string]string{
			"requestId":               "requestId",
			"request_id":              "requestId",
			"leaseId":                 "leaseId",
			"lease_id":                "leaseId",
			"credentialVersionHash":   "credentialVersionHash",
			"credential_version_hash": "credentialVersionHash",
			"outcome":                 "outcome",
			"leaseReceiptRoot":        "leaseReceiptRoot",
			"lease_receipt_root":      "leaseReceiptRoot",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize CredentialLeaseReceipt JSON: %w", err)
	}
	var decoded credentialLeaseReceiptJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode CredentialLeaseReceipt: %w", err)
	}
	*message = CredentialLeaseReceipt(decoded)
	return nil
}

type recoveryPointerJSONAlias RecoveryPointer

func (message *RecoveryPointer) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *RecoveryPointer")
	}
	object, err := decodeProtoJSONObject("RecoveryPointer", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"RecoveryPointer",
		object,
		map[string]string{
			"recoveryPointerId":      "recoveryPointerId",
			"recovery_pointer_id":    "recoveryPointerId",
			"checkpointRoot":         "checkpointRoot",
			"checkpoint_root":        "checkpointRoot",
			"checkpointSequence":     "checkpointSequence",
			"checkpoint_sequence":    "checkpointSequence",
			"recoveryManifestHash":   "recoveryManifestHash",
			"recovery_manifest_hash": "recoveryManifestHash",
			"observedAt":             "observedAt",
			"observed_at":            "observedAt",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize RecoveryPointer JSON: %w", err)
	}
	var decoded recoveryPointerJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode RecoveryPointer: %w", err)
	}
	*message = RecoveryPointer(decoded)
	return nil
}

type providerControlHeadJSONAlias ProviderControlHead

func (message *ProviderControlHead) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProviderControlHead")
	}
	object, err := decodeProtoJSONObject("ProviderControlHead", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProviderControlHead",
		object,
		map[string]string{
			"providerDataUseRecordId":       "providerDataUseRecordId",
			"provider_data_use_record_id":   "providerDataUseRecordId",
			"providerDataUseRecordHash":     "providerDataUseRecordHash",
			"provider_data_use_record_hash": "providerDataUseRecordHash",
			"providerReviewId":              "providerReviewId",
			"provider_review_id":            "providerReviewId",
			"providerReviewHash":            "providerReviewHash",
			"provider_review_hash":          "providerReviewHash",
			"providerStatusId":              "providerStatusId",
			"provider_status_id":            "providerStatusId",
			"providerStatusHash":            "providerStatusHash",
			"provider_status_hash":          "providerStatusHash",
			"providerTransitionId":          "providerTransitionId",
			"provider_transition_id":        "providerTransitionId",
			"providerTransitionHash":        "providerTransitionHash",
			"provider_transition_hash":      "providerTransitionHash",
			"providerTransitionSequence":    "providerTransitionSequence",
			"provider_transition_sequence":  "providerTransitionSequence",
			"publicKeyRegistryId":           "publicKeyRegistryId",
			"public_key_registry_id":        "publicKeyRegistryId",
			"publicKeyRegistryHash":         "publicKeyRegistryHash",
			"public_key_registry_hash":      "publicKeyRegistryHash",
			"routeHoldId":                   "routeHoldId",
			"route_hold_id":                 "routeHoldId",
			"routeHoldHash":                 "routeHoldHash",
			"route_hold_hash":               "routeHoldHash",
			"providerUseLeaseId":            "providerUseLeaseId",
			"provider_use_lease_id":         "providerUseLeaseId",
			"providerUseLeaseHash":          "providerUseLeaseHash",
			"provider_use_lease_hash":       "providerUseLeaseHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProviderControlHead JSON: %w", err)
	}
	var decoded providerControlHeadJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProviderControlHead: %w", err)
	}
	*message = ProviderControlHead(decoded)
	return nil
}

type providerEvidenceTransitionDeliveryJSONAlias ProviderEvidenceTransitionDelivery

func (message *ProviderEvidenceTransitionDelivery) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProviderEvidenceTransitionDelivery")
	}
	object, err := decodeProtoJSONObject("ProviderEvidenceTransitionDelivery", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProviderEvidenceTransitionDelivery",
		object,
		map[string]string{
			"deliveryId":                    "deliveryId",
			"delivery_id":                   "deliveryId",
			"cellReleaseBindingHash":        "cellReleaseBindingHash",
			"cell_release_binding_hash":     "cellReleaseBindingHash",
			"providerDataUseRecordId":       "providerDataUseRecordId",
			"provider_data_use_record_id":   "providerDataUseRecordId",
			"providerDataUseRecordHash":     "providerDataUseRecordHash",
			"provider_data_use_record_hash": "providerDataUseRecordHash",
			"transitionId":                  "transitionId",
			"transition_id":                 "transitionId",
			"transitionHash":                "transitionHash",
			"transition_hash":               "transitionHash",
			"transitionSequence":            "transitionSequence",
			"transition_sequence":           "transitionSequence",
			"predecessorTransitionHash":     "predecessorTransitionHash",
			"predecessor_transition_hash":   "predecessorTransitionHash",
			"embeddedReviewHash":            "embeddedReviewHash",
			"embedded_review_hash":          "embeddedReviewHash",
			"embeddedStatusHash":            "embeddedStatusHash",
			"embedded_status_hash":          "embeddedStatusHash",
			"transitionObjectKey":           "transitionObjectKey",
			"transition_object_key":         "transitionObjectKey",
			"signatureEnvelopeHash":         "signatureEnvelopeHash",
			"signature_envelope_hash":       "signatureEnvelopeHash",
			"publicKeyRegistryId":           "publicKeyRegistryId",
			"public_key_registry_id":        "publicKeyRegistryId",
			"publicKeyRegistryHash":         "publicKeyRegistryHash",
			"public_key_registry_hash":      "publicKeyRegistryHash",
			"registryPredecessorHash":       "registryPredecessorHash",
			"registry_predecessor_hash":     "registryPredecessorHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProviderEvidenceTransitionDelivery JSON: %w", err)
	}
	var decoded providerEvidenceTransitionDeliveryJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProviderEvidenceTransitionDelivery: %w", err)
	}
	*message = ProviderEvidenceTransitionDelivery(decoded)
	return nil
}

type providerRouteHoldFrameJSONAlias ProviderRouteHoldFrame

func (message *ProviderRouteHoldFrame) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProviderRouteHoldFrame")
	}
	object, err := decodeProtoJSONObject("ProviderRouteHoldFrame", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProviderRouteHoldFrame",
		object,
		map[string]string{
			"holdId":                        "holdId",
			"hold_id":                       "holdId",
			"holdHash":                      "holdHash",
			"hold_hash":                     "holdHash",
			"providerDataUseRecordId":       "providerDataUseRecordId",
			"provider_data_use_record_id":   "providerDataUseRecordId",
			"transitionId":                  "transitionId",
			"transition_id":                 "transitionId",
			"cellReleaseBindingHash":        "cellReleaseBindingHash",
			"cell_release_binding_hash":     "cellReleaseBindingHash",
			"state":                         "state",
			"maximumPreHoldLeaseExpiry":     "maximumPreHoldLeaseExpiry",
			"maximum_pre_hold_lease_expiry": "maximumPreHoldLeaseExpiry",
			"safeReasonCode":                "safeReasonCode",
			"safe_reason_code":              "safeReasonCode",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProviderRouteHoldFrame JSON: %w", err)
	}
	var decoded providerRouteHoldFrameJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProviderRouteHoldFrame: %w", err)
	}
	*message = ProviderRouteHoldFrame(decoded)
	return nil
}

type providerUseLeaseFrameJSONAlias ProviderUseLeaseFrame

func (message *ProviderUseLeaseFrame) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProviderUseLeaseFrame")
	}
	object, err := decodeProtoJSONObject("ProviderUseLeaseFrame", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProviderUseLeaseFrame",
		object,
		map[string]string{
			"leaseId":                       "leaseId",
			"lease_id":                      "leaseId",
			"reservationId":                 "reservationId",
			"reservation_id":                "reservationId",
			"cellId":                        "cellId",
			"cell_id":                       "cellId",
			"cellGeneration":                "cellGeneration",
			"cell_generation":               "cellGeneration",
			"cellReleaseBindingHash":        "cellReleaseBindingHash",
			"cell_release_binding_hash":     "cellReleaseBindingHash",
			"providerDataUseRecordId":       "providerDataUseRecordId",
			"provider_data_use_record_id":   "providerDataUseRecordId",
			"providerDataUseRecordHash":     "providerDataUseRecordHash",
			"provider_data_use_record_hash": "providerDataUseRecordHash",
			"acceptedTransitionId":          "acceptedTransitionId",
			"accepted_transition_id":        "acceptedTransitionId",
			"acceptedTransitionSequence":    "acceptedTransitionSequence",
			"accepted_transition_sequence":  "acceptedTransitionSequence",
			"acceptedStatusHash":            "acceptedStatusHash",
			"accepted_status_hash":          "acceptedStatusHash",
			"agentBundleId":                 "agentBundleId",
			"agent_bundle_id":               "agentBundleId",
			"agentBundleHash":               "agentBundleHash",
			"agent_bundle_hash":             "agentBundleHash",
			"releaseUnitId":                 "releaseUnitId",
			"release_unit_id":               "releaseUnitId",
			"releaseUnitHash":               "releaseUnitHash",
			"release_unit_hash":             "releaseUnitHash",
			"controlEpoch":                  "controlEpoch",
			"control_epoch":                 "controlEpoch",
			"noUnresolvedBindingHold":       "noUnresolvedBindingHold",
			"no_unresolved_binding_hold":    "noUnresolvedBindingHold",
			"issuedAt":                      "issuedAt",
			"issued_at":                     "issuedAt",
			"expiresAt":                     "expiresAt",
			"expires_at":                    "expiresAt",
			"ttlSeconds":                    "ttlSeconds",
			"ttl_seconds":                   "ttlSeconds",
			"nonceHash":                     "nonceHash",
			"nonce_hash":                    "nonceHash",
			"signaturePurpose":              "signaturePurpose",
			"signature_purpose":             "signaturePurpose",
			"signatureEnvelopeHash":         "signatureEnvelopeHash",
			"signature_envelope_hash":       "signatureEnvelopeHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProviderUseLeaseFrame JSON: %w", err)
	}
	var decoded providerUseLeaseFrameJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProviderUseLeaseFrame: %w", err)
	}
	*message = ProviderUseLeaseFrame(decoded)
	return nil
}

type providerControlAckJSONAlias ProviderControlAck

func (message *ProviderControlAck) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *ProviderControlAck")
	}
	object, err := decodeProtoJSONObject("ProviderControlAck", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"ProviderControlAck",
		object,
		map[string]string{
			"deliveryId":              "deliveryId",
			"delivery_id":             "deliveryId",
			"transitionId":            "transitionId",
			"transition_id":           "transitionId",
			"transitionHash":          "transitionHash",
			"transition_hash":         "transitionHash",
			"routeHoldId":             "routeHoldId",
			"route_hold_id":           "routeHoldId",
			"acceptedHeadHash":        "acceptedHeadHash",
			"accepted_head_hash":      "acceptedHeadHash",
			"state":                   "state",
			"acceptedAt":              "acceptedAt",
			"accepted_at":             "acceptedAt",
			"signatureEnvelopeHash":   "signatureEnvelopeHash",
			"signature_envelope_hash": "signatureEnvelopeHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize ProviderControlAck JSON: %w", err)
	}
	var decoded providerControlAckJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode ProviderControlAck: %w", err)
	}
	*message = ProviderControlAck(decoded)
	return nil
}

type renewRequestJSONAlias RenewRequest

func (message *RenewRequest) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *RenewRequest")
	}
	object, err := decodeProtoJSONObject("RenewRequest", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"RenewRequest",
		object,
		map[string]string{
			"context":                      "context",
			"failoverManifestId":           "failoverManifestId",
			"failover_manifest_id":         "failoverManifestId",
			"failoverManifestHash":         "failoverManifestHash",
			"failover_manifest_hash":       "failoverManifestHash",
			"priorControlRegionEpoch":      "priorControlRegionEpoch",
			"prior_control_region_epoch":   "priorControlRegionEpoch",
			"currentControlRegionEpoch":    "currentControlRegionEpoch",
			"current_control_region_epoch": "currentControlRegionEpoch",
			"oldCertificateSerial":         "oldCertificateSerial",
			"old_certificate_serial":       "oldCertificateSerial",
			"csrDerSha256":                 "csrDerSha256",
			"csr_der_sha256":               "csrDerSha256",
			"csrDer":                       "csrDer",
			"csr_der":                      "csrDer",
			"instanceIdentityHash":         "instanceIdentityHash",
			"instance_identity_hash":       "instanceIdentityHash",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize RenewRequest JSON: %w", err)
	}
	var decoded renewRequestJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode RenewRequest: %w", err)
	}
	*message = RenewRequest(decoded)
	return nil
}

type renewResponseJSONAlias RenewResponse

func (message *RenewResponse) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *RenewResponse")
	}
	object, err := decodeProtoJSONObject("RenewResponse", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"RenewResponse",
		object,
		map[string]string{
			"context":               "context",
			"requestId":             "requestId",
			"request_id":            "requestId",
			"pollSecret":            "pollSecret",
			"poll_secret":           "pollSecret",
			"pollSecretHash":        "pollSecretHash",
			"poll_secret_hash":      "pollSecretHash",
			"expiresAt":             "expiresAt",
			"expires_at":            "expiresAt",
			"recoveryReceiptRoot":   "recoveryReceiptRoot",
			"recovery_receipt_root": "recoveryReceiptRoot",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize RenewResponse JSON: %w", err)
	}
	var decoded renewResponseJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode RenewResponse: %w", err)
	}
	*message = RenewResponse(decoded)
	return nil
}

type SupervisorFrameVariant interface {
	isSupervisorFrameVariant()
}

type SupervisorFrameCellHello struct {
	CellHello *CellHello `protobuf:"bytes,2,opt,name=cell_hello,proto3,oneof" json:"cellHello,omitempty"`
}

func (*SupervisorFrameCellHello) isSupervisorFrameVariant() {}

type SupervisorFrameHeartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof" json:"heartbeat,omitempty"`
}

func (*SupervisorFrameHeartbeat) isSupervisorFrameVariant() {}

type SupervisorFrameCommandLease struct {
	CommandLease *CommandLease `protobuf:"bytes,4,opt,name=command_lease,proto3,oneof" json:"commandLease,omitempty"`
}

func (*SupervisorFrameCommandLease) isSupervisorFrameVariant() {}

type SupervisorFrameCommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,5,opt,name=command_ack,proto3,oneof" json:"commandAck,omitempty"`
}

func (*SupervisorFrameCommandAck) isSupervisorFrameVariant() {}

type SupervisorFrameProjectionSnapshot struct {
	ProjectionSnapshot *ProjectionSnapshot `protobuf:"bytes,6,opt,name=projection_snapshot,proto3,oneof" json:"projectionSnapshot,omitempty"`
}

func (*SupervisorFrameProjectionSnapshot) isSupervisorFrameVariant() {}

type SupervisorFrameOperationGrant struct {
	OperationGrant *OperationGrant `protobuf:"bytes,7,opt,name=operation_grant,proto3,oneof" json:"operationGrant,omitempty"`
}

func (*SupervisorFrameOperationGrant) isSupervisorFrameVariant() {}

type SupervisorFrameToolReceipt struct {
	ToolReceipt *ToolReceipt `protobuf:"bytes,8,opt,name=tool_receipt,proto3,oneof" json:"toolReceipt,omitempty"`
}

func (*SupervisorFrameToolReceipt) isSupervisorFrameVariant() {}

type SupervisorFrameCellEventBatch struct {
	CellEventBatch *CellEventBatch `protobuf:"bytes,9,opt,name=cell_event_batch,proto3,oneof" json:"cellEventBatch,omitempty"`
}

func (*SupervisorFrameCellEventBatch) isSupervisorFrameVariant() {}

type SupervisorFrameEventAck struct {
	EventAck *EventAck `protobuf:"bytes,10,opt,name=event_ack,proto3,oneof" json:"eventAck,omitempty"`
}

func (*SupervisorFrameEventAck) isSupervisorFrameVariant() {}

type SupervisorFrameEvidenceAccessRequest struct {
	EvidenceAccessRequest *EvidenceAccessRequest `protobuf:"bytes,11,opt,name=evidence_access_request,proto3,oneof" json:"evidenceAccessRequest,omitempty"`
}

func (*SupervisorFrameEvidenceAccessRequest) isSupervisorFrameVariant() {}

type SupervisorFrameEvidenceAccessReceipt struct {
	EvidenceAccessReceipt *EvidenceAccessReceipt `protobuf:"bytes,12,opt,name=evidence_access_receipt,proto3,oneof" json:"evidenceAccessReceipt,omitempty"`
}

func (*SupervisorFrameEvidenceAccessReceipt) isSupervisorFrameVariant() {}

type SupervisorFrameCredentialLeaseRequest struct {
	CredentialLeaseRequest *CredentialLeaseRequest `protobuf:"bytes,13,opt,name=credential_lease_request,proto3,oneof" json:"credentialLeaseRequest,omitempty"`
}

func (*SupervisorFrameCredentialLeaseRequest) isSupervisorFrameVariant() {}

type SupervisorFrameCredentialLeaseReceipt struct {
	CredentialLeaseReceipt *CredentialLeaseReceipt `protobuf:"bytes,14,opt,name=credential_lease_receipt,proto3,oneof" json:"credentialLeaseReceipt,omitempty"`
}

func (*SupervisorFrameCredentialLeaseReceipt) isSupervisorFrameVariant() {}

type SupervisorFrameRecoveryPointer struct {
	RecoveryPointer *RecoveryPointer `protobuf:"bytes,15,opt,name=recovery_pointer,proto3,oneof" json:"recoveryPointer,omitempty"`
}

func (*SupervisorFrameRecoveryPointer) isSupervisorFrameVariant() {}

type SupervisorFrameProviderEvidenceTransition struct {
	ProviderEvidenceTransition *ProviderEvidenceTransitionDelivery `protobuf:"bytes,16,opt,name=provider_evidence_transition,proto3,oneof" json:"providerEvidenceTransition,omitempty"`
}

func (*SupervisorFrameProviderEvidenceTransition) isSupervisorFrameVariant() {}

type SupervisorFrameProviderRouteHold struct {
	ProviderRouteHold *ProviderRouteHoldFrame `protobuf:"bytes,17,opt,name=provider_route_hold,proto3,oneof" json:"providerRouteHold,omitempty"`
}

func (*SupervisorFrameProviderRouteHold) isSupervisorFrameVariant() {}

type SupervisorFrameProviderUseLease struct {
	ProviderUseLease *ProviderUseLeaseFrame `protobuf:"bytes,18,opt,name=provider_use_lease,proto3,oneof" json:"providerUseLease,omitempty"`
}

func (*SupervisorFrameProviderUseLease) isSupervisorFrameVariant() {}

type SupervisorFrameProviderControlAck struct {
	ProviderControlAck *ProviderControlAck `protobuf:"bytes,19,opt,name=provider_control_ack,proto3,oneof" json:"providerControlAck,omitempty"`
}

func (*SupervisorFrameProviderControlAck) isSupervisorFrameVariant() {}

func (message *SupervisorFrame) HasValidFrame() bool {
	if message == nil {
		return false
	}
	switch variant := message.Frame.(type) {
	case *SupervisorFrameCellHello:
		return variant != nil && variant.CellHello != nil
	case *SupervisorFrameHeartbeat:
		return variant != nil && variant.Heartbeat != nil
	case *SupervisorFrameCommandLease:
		return variant != nil && variant.CommandLease != nil
	case *SupervisorFrameCommandAck:
		return variant != nil && variant.CommandAck != nil
	case *SupervisorFrameProjectionSnapshot:
		return variant != nil && variant.ProjectionSnapshot != nil
	case *SupervisorFrameOperationGrant:
		return variant != nil && variant.OperationGrant != nil
	case *SupervisorFrameToolReceipt:
		return variant != nil && variant.ToolReceipt != nil
	case *SupervisorFrameCellEventBatch:
		return variant != nil && variant.CellEventBatch != nil
	case *SupervisorFrameEventAck:
		return variant != nil && variant.EventAck != nil
	case *SupervisorFrameEvidenceAccessRequest:
		return variant != nil && variant.EvidenceAccessRequest != nil
	case *SupervisorFrameEvidenceAccessReceipt:
		return variant != nil && variant.EvidenceAccessReceipt != nil
	case *SupervisorFrameCredentialLeaseRequest:
		return variant != nil && variant.CredentialLeaseRequest != nil
	case *SupervisorFrameCredentialLeaseReceipt:
		return variant != nil && variant.CredentialLeaseReceipt != nil
	case *SupervisorFrameRecoveryPointer:
		return variant != nil && variant.RecoveryPointer != nil
	case *SupervisorFrameProviderEvidenceTransition:
		return variant != nil && variant.ProviderEvidenceTransition != nil
	case *SupervisorFrameProviderRouteHold:
		return variant != nil && variant.ProviderRouteHold != nil
	case *SupervisorFrameProviderUseLease:
		return variant != nil && variant.ProviderUseLease != nil
	case *SupervisorFrameProviderControlAck:
		return variant != nil && variant.ProviderControlAck != nil
	default:
		return false
	}
}

type supervisorFrameJSONAlias SupervisorFrame

func (message SupervisorFrame) MarshalJSON() ([]byte, error) {
	base, err := json.Marshal(supervisorFrameJSONAlias(message))
	if err != nil {
		return nil, err
	}
	var object map[string]json.RawMessage
	if err := json.Unmarshal(base, &object); err != nil {
		return nil, err
	}
	switch variant := message.Frame.(type) {
	case nil:
		return nil, fmt.Errorf("SupervisorFrame.Frame requires exactly one variant")
	case *SupervisorFrameCellHello:
		if variant == nil || variant.CellHello == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil cell_hello variant")
		}
		payload, err := json.Marshal(variant.CellHello)
		if err != nil {
			return nil, err
		}
		object["cellHello"] = payload
	case *SupervisorFrameHeartbeat:
		if variant == nil || variant.Heartbeat == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil heartbeat variant")
		}
		payload, err := json.Marshal(variant.Heartbeat)
		if err != nil {
			return nil, err
		}
		object["heartbeat"] = payload
	case *SupervisorFrameCommandLease:
		if variant == nil || variant.CommandLease == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil command_lease variant")
		}
		payload, err := json.Marshal(variant.CommandLease)
		if err != nil {
			return nil, err
		}
		object["commandLease"] = payload
	case *SupervisorFrameCommandAck:
		if variant == nil || variant.CommandAck == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil command_ack variant")
		}
		payload, err := json.Marshal(variant.CommandAck)
		if err != nil {
			return nil, err
		}
		object["commandAck"] = payload
	case *SupervisorFrameProjectionSnapshot:
		if variant == nil || variant.ProjectionSnapshot == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil projection_snapshot variant")
		}
		payload, err := json.Marshal(variant.ProjectionSnapshot)
		if err != nil {
			return nil, err
		}
		object["projectionSnapshot"] = payload
	case *SupervisorFrameOperationGrant:
		if variant == nil || variant.OperationGrant == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil operation_grant variant")
		}
		payload, err := json.Marshal(variant.OperationGrant)
		if err != nil {
			return nil, err
		}
		object["operationGrant"] = payload
	case *SupervisorFrameToolReceipt:
		if variant == nil || variant.ToolReceipt == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil tool_receipt variant")
		}
		payload, err := json.Marshal(variant.ToolReceipt)
		if err != nil {
			return nil, err
		}
		object["toolReceipt"] = payload
	case *SupervisorFrameCellEventBatch:
		if variant == nil || variant.CellEventBatch == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil cell_event_batch variant")
		}
		payload, err := json.Marshal(variant.CellEventBatch)
		if err != nil {
			return nil, err
		}
		object["cellEventBatch"] = payload
	case *SupervisorFrameEventAck:
		if variant == nil || variant.EventAck == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil event_ack variant")
		}
		payload, err := json.Marshal(variant.EventAck)
		if err != nil {
			return nil, err
		}
		object["eventAck"] = payload
	case *SupervisorFrameEvidenceAccessRequest:
		if variant == nil || variant.EvidenceAccessRequest == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil evidence_access_request variant")
		}
		payload, err := json.Marshal(variant.EvidenceAccessRequest)
		if err != nil {
			return nil, err
		}
		object["evidenceAccessRequest"] = payload
	case *SupervisorFrameEvidenceAccessReceipt:
		if variant == nil || variant.EvidenceAccessReceipt == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil evidence_access_receipt variant")
		}
		payload, err := json.Marshal(variant.EvidenceAccessReceipt)
		if err != nil {
			return nil, err
		}
		object["evidenceAccessReceipt"] = payload
	case *SupervisorFrameCredentialLeaseRequest:
		if variant == nil || variant.CredentialLeaseRequest == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil credential_lease_request variant")
		}
		payload, err := json.Marshal(variant.CredentialLeaseRequest)
		if err != nil {
			return nil, err
		}
		object["credentialLeaseRequest"] = payload
	case *SupervisorFrameCredentialLeaseReceipt:
		if variant == nil || variant.CredentialLeaseReceipt == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil credential_lease_receipt variant")
		}
		payload, err := json.Marshal(variant.CredentialLeaseReceipt)
		if err != nil {
			return nil, err
		}
		object["credentialLeaseReceipt"] = payload
	case *SupervisorFrameRecoveryPointer:
		if variant == nil || variant.RecoveryPointer == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil recovery_pointer variant")
		}
		payload, err := json.Marshal(variant.RecoveryPointer)
		if err != nil {
			return nil, err
		}
		object["recoveryPointer"] = payload
	case *SupervisorFrameProviderEvidenceTransition:
		if variant == nil || variant.ProviderEvidenceTransition == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil provider_evidence_transition variant")
		}
		payload, err := json.Marshal(variant.ProviderEvidenceTransition)
		if err != nil {
			return nil, err
		}
		object["providerEvidenceTransition"] = payload
	case *SupervisorFrameProviderRouteHold:
		if variant == nil || variant.ProviderRouteHold == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil provider_route_hold variant")
		}
		payload, err := json.Marshal(variant.ProviderRouteHold)
		if err != nil {
			return nil, err
		}
		object["providerRouteHold"] = payload
	case *SupervisorFrameProviderUseLease:
		if variant == nil || variant.ProviderUseLease == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil provider_use_lease variant")
		}
		payload, err := json.Marshal(variant.ProviderUseLease)
		if err != nil {
			return nil, err
		}
		object["providerUseLease"] = payload
	case *SupervisorFrameProviderControlAck:
		if variant == nil || variant.ProviderControlAck == nil {
			return nil, fmt.Errorf("SupervisorFrame.Frame contains a nil provider_control_ack variant")
		}
		payload, err := json.Marshal(variant.ProviderControlAck)
		if err != nil {
			return nil, err
		}
		object["providerControlAck"] = payload
	default:
		return nil, fmt.Errorf("SupervisorFrame.Frame contains an unknown variant %T", variant)
	}
	return json.Marshal(object)
}

func (message *SupervisorFrame) UnmarshalJSON(data []byte) error {
	if message == nil {
		return fmt.Errorf("cannot decode JSON into nil *SupervisorFrame")
	}
	object, err := decodeProtoJSONObject("SupervisorFrame", data)
	if err != nil {
		return err
	}
	normalized, err := normalizeProtoJSONFields(
		"SupervisorFrame",
		object,
		map[string]string{
			"context":                      "context",
			"cellHello":                    "cellHello",
			"cell_hello":                   "cellHello",
			"heartbeat":                    "heartbeat",
			"commandLease":                 "commandLease",
			"command_lease":                "commandLease",
			"commandAck":                   "commandAck",
			"command_ack":                  "commandAck",
			"projectionSnapshot":           "projectionSnapshot",
			"projection_snapshot":          "projectionSnapshot",
			"operationGrant":               "operationGrant",
			"operation_grant":              "operationGrant",
			"toolReceipt":                  "toolReceipt",
			"tool_receipt":                 "toolReceipt",
			"cellEventBatch":               "cellEventBatch",
			"cell_event_batch":             "cellEventBatch",
			"eventAck":                     "eventAck",
			"event_ack":                    "eventAck",
			"evidenceAccessRequest":        "evidenceAccessRequest",
			"evidence_access_request":      "evidenceAccessRequest",
			"evidenceAccessReceipt":        "evidenceAccessReceipt",
			"evidence_access_receipt":      "evidenceAccessReceipt",
			"credentialLeaseRequest":       "credentialLeaseRequest",
			"credential_lease_request":     "credentialLeaseRequest",
			"credentialLeaseReceipt":       "credentialLeaseReceipt",
			"credential_lease_receipt":     "credentialLeaseReceipt",
			"recoveryPointer":              "recoveryPointer",
			"recovery_pointer":             "recoveryPointer",
			"providerEvidenceTransition":   "providerEvidenceTransition",
			"provider_evidence_transition": "providerEvidenceTransition",
			"providerRouteHold":            "providerRouteHold",
			"provider_route_hold":          "providerRouteHold",
			"providerUseLease":             "providerUseLease",
			"provider_use_lease":           "providerUseLease",
			"providerControlAck":           "providerControlAck",
			"provider_control_ack":         "providerControlAck",
		},
	)
	if err != nil {
		return err
	}
	normalizedPayload, err := json.Marshal(normalized)
	if err != nil {
		return fmt.Errorf("normalize SupervisorFrame JSON: %w", err)
	}
	var decoded supervisorFrameJSONAlias
	if err := json.Unmarshal(normalizedPayload, &decoded); err != nil {
		return fmt.Errorf("decode SupervisorFrame: %w", err)
	}
	var selected SupervisorFrameVariant
	variantSeen := false
	if payload, ok := normalized["cellHello"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CellHello
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.cell_hello: %w", err)
			}
			selected = &SupervisorFrameCellHello{CellHello: &value}
		}
	}
	if payload, ok := normalized["heartbeat"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value Heartbeat
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.heartbeat: %w", err)
			}
			selected = &SupervisorFrameHeartbeat{Heartbeat: &value}
		}
	}
	if payload, ok := normalized["commandLease"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CommandLease
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.command_lease: %w", err)
			}
			selected = &SupervisorFrameCommandLease{CommandLease: &value}
		}
	}
	if payload, ok := normalized["commandAck"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CommandAck
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.command_ack: %w", err)
			}
			selected = &SupervisorFrameCommandAck{CommandAck: &value}
		}
	}
	if payload, ok := normalized["projectionSnapshot"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ProjectionSnapshot
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.projection_snapshot: %w", err)
			}
			selected = &SupervisorFrameProjectionSnapshot{ProjectionSnapshot: &value}
		}
	}
	if payload, ok := normalized["operationGrant"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value OperationGrant
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.operation_grant: %w", err)
			}
			selected = &SupervisorFrameOperationGrant{OperationGrant: &value}
		}
	}
	if payload, ok := normalized["toolReceipt"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ToolReceipt
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.tool_receipt: %w", err)
			}
			selected = &SupervisorFrameToolReceipt{ToolReceipt: &value}
		}
	}
	if payload, ok := normalized["cellEventBatch"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CellEventBatch
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.cell_event_batch: %w", err)
			}
			selected = &SupervisorFrameCellEventBatch{CellEventBatch: &value}
		}
	}
	if payload, ok := normalized["eventAck"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value EventAck
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.event_ack: %w", err)
			}
			selected = &SupervisorFrameEventAck{EventAck: &value}
		}
	}
	if payload, ok := normalized["evidenceAccessRequest"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value EvidenceAccessRequest
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.evidence_access_request: %w", err)
			}
			selected = &SupervisorFrameEvidenceAccessRequest{EvidenceAccessRequest: &value}
		}
	}
	if payload, ok := normalized["evidenceAccessReceipt"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value EvidenceAccessReceipt
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.evidence_access_receipt: %w", err)
			}
			selected = &SupervisorFrameEvidenceAccessReceipt{EvidenceAccessReceipt: &value}
		}
	}
	if payload, ok := normalized["credentialLeaseRequest"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CredentialLeaseRequest
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.credential_lease_request: %w", err)
			}
			selected = &SupervisorFrameCredentialLeaseRequest{CredentialLeaseRequest: &value}
		}
	}
	if payload, ok := normalized["credentialLeaseReceipt"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value CredentialLeaseReceipt
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.credential_lease_receipt: %w", err)
			}
			selected = &SupervisorFrameCredentialLeaseReceipt{CredentialLeaseReceipt: &value}
		}
	}
	if payload, ok := normalized["recoveryPointer"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value RecoveryPointer
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.recovery_pointer: %w", err)
			}
			selected = &SupervisorFrameRecoveryPointer{RecoveryPointer: &value}
		}
	}
	if payload, ok := normalized["providerEvidenceTransition"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ProviderEvidenceTransitionDelivery
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.provider_evidence_transition: %w", err)
			}
			selected = &SupervisorFrameProviderEvidenceTransition{ProviderEvidenceTransition: &value}
		}
	}
	if payload, ok := normalized["providerRouteHold"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ProviderRouteHoldFrame
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.provider_route_hold: %w", err)
			}
			selected = &SupervisorFrameProviderRouteHold{ProviderRouteHold: &value}
		}
	}
	if payload, ok := normalized["providerUseLease"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ProviderUseLeaseFrame
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.provider_use_lease: %w", err)
			}
			selected = &SupervisorFrameProviderUseLease{ProviderUseLease: &value}
		}
	}
	if payload, ok := normalized["providerControlAck"]; ok {
		if variantSeen {
			return fmt.Errorf("SupervisorFrame.Frame contains multiple variants")
		}
		variantSeen = true
		if !bytes.Equal(bytes.TrimSpace(payload), []byte("null")) {
			var value ProviderControlAck
			if err := json.Unmarshal(payload, &value); err != nil {
				return fmt.Errorf("decode SupervisorFrame.provider_control_ack: %w", err)
			}
			selected = &SupervisorFrameProviderControlAck{ProviderControlAck: &value}
		}
	}
	if selected == nil {
		return fmt.Errorf("SupervisorFrame.Frame requires exactly one non-null variant")
	}
	decoded.Frame = selected
	*message = SupervisorFrame(decoded)
	return nil
}
