// Code generated by internal/contracts/codegen/generate.py from cell.proto; DO NOT EDIT.
package cellv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func metadataValue(metadata Metadata, key string) string {
	for candidate, values := range metadata {
		if strings.EqualFold(candidate, key) && len(values) != 0 {
			return values[0]
		}
	}
	return ""
}

type handlerRoundTripper struct {
	handler http.Handler
}

func (transport handlerRoundTripper) RoundTrip(request *http.Request) (*http.Response, error) {
	serverRequest := httptest.NewRequest(request.Method, request.URL.String(), request.Body)
	serverRequest.Header = request.Header.Clone()
	serverRequest = serverRequest.WithContext(request.Context())
	recorder := httptest.NewRecorder()
	transport.handler.ServeHTTP(recorder, serverRequest)
	response := recorder.Result()
	response.Request = request
	return response, nil
}

func handlerHTTPClient(handler http.Handler) *http.Client {
	return &http.Client{Transport: handlerRoundTripper{handler: handler}}
}

func TestCellProtoJSONNamesAndOneofStrictness(t *testing.T) {
	encoded, err := json.Marshal(&RenewResponse{
		Context:   &EnvelopeContext{WorkspaceID: "workspace", CellGeneration: 4},
		RequestID: "request",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range [][]byte{
		[]byte(`"workspaceId":"workspace"`),
		[]byte(`"cellGeneration":"4"`),
		[]byte(`"requestId":"request"`),
	} {
		if !bytes.Contains(encoded, expected) {
			t.Fatalf("ProtoJSON output %s does not contain %s", encoded, expected)
		}
	}
	if bytes.Contains(encoded, []byte("workspace_id")) || bytes.Contains(encoded, []byte("request_id")) {
		t.Fatalf("ProtoJSON output retained proto field spelling: %s", encoded)
	}

	var compatibility RenewResponse
	if err := json.Unmarshal(
		[]byte(`{"context":{"workspace_id":"workspace"},"request_id":"request"}`),
		&compatibility,
	); err != nil {
		t.Fatalf("protobuf parsers must accept original proto field spellings: %v", err)
	}
	if compatibility.Context == nil || compatibility.Context.WorkspaceID != "workspace" || compatibility.RequestID != "request" {
		t.Fatalf("compatibility spelling decoded incorrectly: %#v", compatibility)
	}
	if err := json.Unmarshal(
		[]byte(`{"context":{"workspaceId":"workspace","unknownField":true},"requestId":"request"}`),
		&compatibility,
	); err == nil {
		t.Fatal("unknown nested ProtoJSON field was accepted")
	}

	var frame SupervisorFrame
	if err := json.Unmarshal(
		[]byte(`{"context":{"workspaceId":"workspace"},"heartbeat":{"livenessState":"healthy"}}`),
		&frame,
	); err != nil {
		t.Fatalf("standard lowerCamel ProtoJSON frame was rejected: %v", err)
	}
	heartbeat, ok := frame.Frame.(*SupervisorFrameHeartbeat)
	if !ok || heartbeat.Heartbeat == nil || heartbeat.Heartbeat.LivenessState != "healthy" {
		t.Fatalf("standard lowerCamel frame decoded incorrectly: %#v", frame.Frame)
	}
	if err := json.Unmarshal(
		[]byte(`{"context":{"workspace_id":"workspace"},"cell_hello":{"release_unit_id":"release"}}`),
		&frame,
	); err != nil {
		t.Fatalf("original proto field compatibility spelling was rejected: %v", err)
	}
	encodedFrame, err := json.Marshal(&frame)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Contains(encodedFrame, []byte(`"cellHello"`)) || !bytes.Contains(encodedFrame, []byte(`"releaseUnitId"`)) {
		t.Fatalf("compatibility input was not normalized on output: %s", encodedFrame)
	}

	invalid := map[string]string{
		"missing variant":         `{"context":{"workspaceId":"workspace"}}`,
		"null variant":            `{"heartbeat":null}`,
		"multiple variants":       `{"heartbeat":{},"commandAck":{}}`,
		"unknown variant":         `{"notAFrame":{}}`,
		"duplicate variant":       `{"heartbeat":{},"heartbeat":{}}`,
		"duplicate variant alias": `{"cellHello":{},"cell_hello":{}}`,
	}
	for name, payload := range invalid {
		t.Run(name, func(t *testing.T) {
			var invalidFrame SupervisorFrame
			if err := json.Unmarshal([]byte(payload), &invalidFrame); err == nil {
				t.Fatalf("invalid oneof payload was accepted: %s", payload)
			}
		})
	}
	if _, err := json.Marshal(&SupervisorFrame{Context: &EnvelopeContext{WorkspaceID: "workspace"}}); err == nil {
		t.Fatal("SupervisorFrame without a oneof variant was marshaled")
	}
}

func TestCellCertificateRecoveryConnectUnaryTransport(t *testing.T) {
	handler := http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if request.Method != http.MethodPost {
			t.Errorf("method = %q, want POST", request.Method)
		}
		if request.URL.Path != "/jumpship.cell.v1.CellCertificateRecovery/Renew" {
			t.Errorf("path = %q", request.URL.Path)
		}
		if request.Header.Get("Content-Type") != connectUnaryContentType || request.Header.Get("Accept") != connectUnaryContentType {
			t.Errorf("unary media types = %q / %q", request.Header.Get("Content-Type"), request.Header.Get("Accept"))
		}
		if request.Header.Get("Connect-Protocol-Version") != connectProtocolVersion {
			t.Errorf("Connect protocol version = %q", request.Header.Get("Connect-Protocol-Version"))
		}
		if request.Header.Get("X-Request-Metadata") != "present" {
			t.Errorf("request metadata was not forwarded")
		}
		payload, err := io.ReadAll(request.Body)
		if err != nil {
			http.Error(writer, err.Error(), http.StatusBadRequest)
			return
		}
		if !bytes.Contains(payload, []byte(`"priorControlRegionEpoch":"7"`)) || bytes.Contains(payload, []byte("prior_control_region_epoch")) {
			t.Errorf("request is not standard ProtoJSON: %s", payload)
		}
		var decoded RenewRequest
		if err := json.Unmarshal(payload, &decoded); err != nil || decoded.PriorControlRegionEpoch != 7 {
			t.Errorf("decode request: value=%#v err=%v", decoded, err)
		}

		writer.Header().Set("Content-Type", "application/json; charset=utf-8")
		writer.Header().Set("X-Reply-Metadata", "present")
		writer.Header().Add("Trailer", "X-Reply-Trailer")
		writer.WriteHeader(http.StatusOK)
		_, _ = io.WriteString(writer, `{"context":{"workspaceId":"workspace","cellGeneration":"8"},"requestId":"request","pollSecret":"secret"}`)
		writer.Header().Set("X-Reply-Trailer", "complete")
	})

	client, err := NewCellCertificateRecoveryClient(
		"https://jumpship.test",
		handlerHTTPClient(handler),
	)
	if err != nil {
		t.Fatal(err)
	}
	response, err := client.Renew(context.Background(), &RPCRequest[RenewRequest]{
		Message: &RenewRequest{
			Context:                 &EnvelopeContext{WorkspaceID: "workspace"},
			PriorControlRegionEpoch: 7,
		},
		Header: Metadata{"X-Request-Metadata": {"present"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	if response.Message == nil || response.Message.RequestID != "request" || response.Message.Context == nil || response.Message.Context.CellGeneration != 8 {
		t.Fatalf("unexpected unary response: %#v", response.Message)
	}
	if metadataValue(response.Header, "X-Reply-Metadata") != "present" || metadataValue(response.Trailer, "X-Reply-Trailer") != "complete" {
		t.Fatalf("unary metadata not preserved: header=%v trailer=%v", response.Header, response.Trailer)
	}
}

func TestSupervisorControlConnectBidiTransport(t *testing.T) {
	handler := http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		if request.Method != http.MethodPost || request.URL.Path != "/jumpship.cell.v1.SupervisorControl/Connect" {
			http.Error(writer, "unexpected procedure", http.StatusNotFound)
			return
		}
		if request.Header.Get("Content-Type") != connectStreamContentType || request.Header.Get("Accept") != connectStreamContentType {
			t.Errorf("stream media types = %q / %q", request.Header.Get("Content-Type"), request.Header.Get("Accept"))
		}
		if request.Header.Get("Connect-Protocol-Version") != connectProtocolVersion || request.Header.Get("X-Stream-Metadata") != "present" {
			t.Errorf("stream protocol headers were not forwarded")
		}
		flags, payload, err := readConnectEnvelope(request.Body)
		if err != nil {
			http.Error(writer, err.Error(), http.StatusBadRequest)
			return
		}
		if flags != 0 {
			t.Errorf("request envelope flags = 0x%02x, want 0", flags)
		}
		if !bytes.Contains(payload, []byte(`"cellHello"`)) || !bytes.Contains(payload, []byte(`"releaseUnitId"`)) || bytes.Contains(payload, []byte("cell_hello")) {
			t.Errorf("stream request is not standard ProtoJSON: %s", payload)
		}
		var requestFrame SupervisorFrame
		if err := json.Unmarshal(payload, &requestFrame); err != nil || !requestFrame.HasValidFrame() {
			t.Errorf("decode request frame: value=%#v err=%v", requestFrame, err)
		}

		writer.Header().Set("Content-Type", "application/connect+json; charset=utf-8")
		writer.Header().Set("X-Stream-Reply", "present")
		writer.Header().Add("Trailer", "X-HTTP-Trailer")
		writer.WriteHeader(http.StatusOK)
		messageEnvelope, err := encodeConnectEnvelope(
			0,
			[]byte(`{"context":{"workspaceId":"workspace"},"heartbeat":{"livenessState":"healthy"}}`),
		)
		if err != nil {
			t.Errorf("encode response envelope: %v", err)
			return
		}
		if _, err := writer.Write(messageEnvelope); err != nil {
			t.Errorf("write response envelope: %v", err)
			return
		}
		endEnvelope, err := encodeConnectEnvelope(
			connectFlagEndStream,
			[]byte(`{"metadata":{"X-End":["complete"]}}`),
		)
		if err != nil {
			t.Errorf("encode end-stream envelope: %v", err)
			return
		}
		if _, err := writer.Write(endEnvelope); err != nil {
			t.Errorf("write end-stream envelope: %v", err)
			return
		}
		writer.Header().Set("X-HTTP-Trailer", "transport-complete")
	})

	client, err := NewSupervisorControlClient(
		"https://jumpship.test",
		handlerHTTPClient(handler),
	)
	if err != nil {
		t.Fatal(err)
	}
	stream, err := client.Connect(
		context.Background(),
		Metadata{"X-Stream-Metadata": {"present"}},
	)
	if err != nil {
		t.Fatal(err)
	}
	if err := stream.Send(&SupervisorFrame{
		Context: &EnvelopeContext{WorkspaceID: "workspace"},
		Frame: &SupervisorFrameCellHello{
			CellHello: &CellHello{ReleaseUnitID: "release"},
		},
	}); err != nil {
		t.Fatal(err)
	}
	if err := stream.CloseRequest(); err != nil {
		t.Fatal(err)
	}
	header, err := stream.ResponseHeader()
	if err != nil {
		t.Fatal(err)
	}
	if metadataValue(header, "X-Stream-Reply") != "present" {
		t.Fatalf("stream response metadata not preserved: %v", header)
	}
	response, err := stream.Receive()
	if err != nil {
		t.Fatal(err)
	}
	heartbeat, ok := response.Frame.(*SupervisorFrameHeartbeat)
	if !ok || heartbeat.Heartbeat == nil || heartbeat.Heartbeat.LivenessState != "healthy" {
		t.Fatalf("unexpected stream response: %#v", response.Frame)
	}
	if _, err := stream.Receive(); !errors.Is(err, io.EOF) {
		t.Fatalf("end-stream Receive error = %v, want EOF", err)
	}
	trailer := stream.ResponseTrailer()
	if metadataValue(trailer, "X-End") != "complete" || metadataValue(trailer, "X-HTTP-Trailer") != "transport-complete" {
		t.Fatalf("stream trailers not preserved: %v", trailer)
	}
	if err := stream.CloseResponse(); err != nil {
		t.Fatal(err)
	}
}
