// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.
// This allowlisted type is the only trajectory shape permitted across the quality boundary.
package sanitizedtrajectory

// SanitizedTrajectory is generated from contracts/agent/trajectory.schema.json.
type SanitizedTrajectory struct {
	BundleID            string `json:"bundle_id"`
	ContainsRawEvidence bool   `json:"contains_raw_evidence"`
	Events              []struct {
		ContextManifestHash *string `json:"context_manifest_hash"`
		EventKind           string  `json:"event_kind"`
		EventRoot           string  `json:"event_root"`
		OccurredAt          string  `json:"occurred_at"`
		SafeSummary         string  `json:"safe_summary"`
		Sequence            int64   `json:"sequence"`
		ToolReceiptHash     *string `json:"tool_receipt_hash"`
	} `json:"events"`
	PosturesObserved    []string `json:"postures_observed"`
	RunID               string   `json:"run_id"`
	SanitizerPolicyHash string   `json:"sanitizer_policy_hash"`
	SanitizerVersion    string   `json:"sanitizer_version"`
	SchemaVersion       string   `json:"schema_version"`
	TrajectoryID        string   `json:"trajectory_id"`
	TrajectoryRoot      string   `json:"trajectory_root"`
}
