// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.
// Canonical verification DTOs generated from their frozen schemas.
package canonical

// PublicKeyRegistry is generated from contracts/crypto/public-key-registry.schema.json.
type PublicKeyRegistry struct {
	IssuedAt string `json:"issued_at"`
	Keys     []struct {
		Algorithm        string   `json:"algorithm"`
		Environments     []string `json:"environments"`
		Kid              string   `json:"kid"`
		PublicKeyPem     string   `json:"public_key_pem"`
		Purposes         []string `json:"purposes"`
		RevocationReason *string  `json:"revocation_reason"`
		RevokedAt        *string  `json:"revoked_at"`
		Status           string   `json:"status"`
		SupersedesKid    *string  `json:"supersedes_kid"`
		TenantScope      *string  `json:"tenant_scope"`
		ValidFrom        string   `json:"valid_from"`
		ValidUntil       string   `json:"valid_until"`
	} `json:"keys"`
	PreviousRegistryHash *string `json:"previous_registry_hash"`
	PurposePolicyHash    string  `json:"purpose_policy_hash"`
	RegistryID           string  `json:"registry_id"`
	RegistryVersion      int64   `json:"registry_version"`
	RootFingerprint      string  `json:"root_fingerprint"`
	SchemaVersion        string  `json:"schema_version"`
}

// SignatureClaims is the signed projection generated from contracts/crypto/signature-envelope.schema.json.
type SignatureClaims struct {
	Algorithm           string  `json:"algorithm"`
	Environment         string  `json:"environment"`
	ExpiresAt           *string `json:"expires_at"`
	IssuedAt            string  `json:"issued_at"`
	KeyRegistryHash     string  `json:"key_registry_hash"`
	KeyRegistryID       string  `json:"key_registry_id"`
	Kid                 string  `json:"kid"`
	MigrationScope      *string `json:"migration_scope"`
	ObjectSchemaID      string  `json:"object_schema_id"`
	ObjectSchemaVersion string  `json:"object_schema_version"`
	ObjectType          string  `json:"object_type"`
	PayloadDigest       string  `json:"payload_digest"`
	Purpose             string  `json:"purpose"`
	SchemaVersion       string  `json:"schema_version"`
	SignerID            string  `json:"signer_id"`
	SignerRole          string  `json:"signer_role"`
	TenantScope         *string `json:"tenant_scope"`
}

// SignatureEnvelope is generated from contracts/crypto/signature-envelope.schema.json.
type SignatureEnvelope struct {
	Algorithm           string  `json:"algorithm"`
	EnvelopeID          string  `json:"envelope_id"`
	Environment         string  `json:"environment"`
	ExpiresAt           *string `json:"expires_at"`
	IssuedAt            string  `json:"issued_at"`
	KeyRegistryHash     string  `json:"key_registry_hash"`
	KeyRegistryID       string  `json:"key_registry_id"`
	Kid                 string  `json:"kid"`
	MigrationScope      *string `json:"migration_scope"`
	ObjectSchemaID      string  `json:"object_schema_id"`
	ObjectSchemaVersion string  `json:"object_schema_version"`
	ObjectType          string  `json:"object_type"`
	PayloadDigest       string  `json:"payload_digest"`
	Purpose             string  `json:"purpose"`
	SchemaVersion       string  `json:"schema_version"`
	SignatureBase64     string  `json:"signature_base64"`
	SignerID            string  `json:"signer_id"`
	SignerRole          string  `json:"signer_role"`
	TenantScope         *string `json:"tenant_scope"`
}
