// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.
// Thin policy-aware client generated from contracts/openapi/openapi.yaml.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

type OperationID string

const (
	OperationRequestApplicationWriterGrant     OperationID = "requestApplicationWriterGrant"
	OperationExchangeApplicationWriterIdentity OperationID = "exchangeApplicationWriterIdentity"
	OperationCreateDeviceAuthorization         OperationID = "createDeviceAuthorization"
	OperationApproveDeviceAuthorization        OperationID = "approveDeviceAuthorization"
	OperationExchangeDeviceToken               OperationID = "exchangeDeviceToken"
	OperationLogoutSession                     OperationID = "logoutSession"
	OperationLogoutAllSessions                 OperationID = "logoutAllSessions"
	OperationCompleteIdentityOAuth             OperationID = "completeIdentityOAuth"
	OperationConsumeIdentityOAuthCallback      OperationID = "consumeIdentityOAuthCallback"
	OperationPrepareIdentityOAuthCallback      OperationID = "prepareIdentityOAuthCallback"
	OperationStartIdentityOAuth                OperationID = "startIdentityOAuth"
	OperationGetAuthSession                    OperationID = "getAuthSession"
	OperationListWebAuthnCredentials           OperationID = "listWebAuthnCredentials"
	OperationRevokeWebAuthnCredential          OperationID = "revokeWebAuthnCredential"
	OperationCreateWebAuthnRegistration        OperationID = "createWebAuthnRegistration"
	OperationVerifyWebAuthnRegistration        OperationID = "verifyWebAuthnRegistration"
	OperationCreateBrowserCeremony             OperationID = "createBrowserCeremony"
	OperationGetBrowserCeremony                OperationID = "getBrowserCeremony"
	OperationDecideBrowserCeremony             OperationID = "decideBrowserCeremony"
	OperationCompleteConnectorOAuth            OperationID = "completeConnectorOAuth"
	OperationConsumeConnectorOAuthCallback     OperationID = "consumeConnectorOAuthCallback"
	OperationPrepareConnectorOAuthCallback     OperationID = "prepareConnectorOAuthCallback"
	OperationCompleteCellCertificateBootstrap  OperationID = "completeCellCertificateBootstrap"
	OperationRequestCellCertificateBootstrap   OperationID = "requestCellCertificateBootstrap"
	OperationAcceptWorkspaceInvitation         OperationID = "acceptWorkspaceInvitation"
	OperationGetEnvironmentAgentIncapabilities OperationID = "getEnvironmentAgentIncapabilities"
	OperationGetMigrationAgentIncapabilities   OperationID = "getMigrationAgentIncapabilities"
	OperationReceiveProviderWebhook            OperationID = "receiveProviderWebhook"
	OperationListWorkspaces                    OperationID = "listWorkspaces"
	OperationCreateWorkspace                   OperationID = "createWorkspace"
	OperationGetWorkspace                      OperationID = "getWorkspace"
	OperationUpdateWorkspace                   OperationID = "updateWorkspace"
	OperationInviteWorkspaceMember             OperationID = "inviteWorkspaceMember"
	OperationListWorkspaceMembers              OperationID = "listWorkspaceMembers"
	OperationUpdateWorkspaceMember             OperationID = "updateWorkspaceMember"
	OperationRemoveWorkspaceMember             OperationID = "removeWorkspaceMember"
	OperationListMigrations                    OperationID = "listMigrations"
	OperationCreateMigration                   OperationID = "createMigration"
	OperationGetMigration                      OperationID = "getMigration"
	OperationUpdateMigration                   OperationID = "updateMigration"
	OperationAbortMigration                    OperationID = "abortMigration"
	OperationGetAccessManifest                 OperationID = "getAccessManifest"
	OperationGetApplicationChangeSet           OperationID = "getApplicationChangeSet"
	OperationGetApplicationEstate              OperationID = "getApplicationEstate"
	OperationAssignConsentApprover             OperationID = "assignConsentApprover"
	OperationRequestArtifactUpload             OperationID = "requestArtifactUpload"
	OperationListArtifacts                     OperationID = "listArtifacts"
	OperationRequestArtifactAccess             OperationID = "requestArtifactAccess"
	OperationListAttempts                      OperationID = "listAttempts"
	OperationListConnectorRecommendations      OperationID = "listConnectorRecommendations"
	OperationListConnectors                    OperationID = "listConnectors"
	OperationConfigureDraftPRAuthority         OperationID = "configureDraftPRAuthority"
	OperationPutMongoDBCredential              OperationID = "putMongoDBCredential"
	OperationDisconnectConnector               OperationID = "disconnectConnector"
	OperationVerifyConnector                   OperationID = "verifyConnector"
	OperationBeginConnectorGrant               OperationID = "beginConnectorGrant"
	OperationGetConsent                        OperationID = "getConsent"
	OperationChallengeConsent                  OperationID = "challengeConsent"
	OperationConfirmConsent                    OperationID = "confirmConsent"
	OperationDeclineConsent                    OperationID = "declineConsent"
	OperationListConversations                 OperationID = "listConversations"
	OperationCreateConversation                OperationID = "createConversation"
	OperationListConversationEvents            OperationID = "listConversationEvents"
	OperationCreateConversationMessage         OperationID = "createConversationMessage"
	OperationListDecisions                     OperationID = "listDecisions"
	OperationGetDecision                       OperationID = "getDecision"
	OperationDelegateDecision                  OperationID = "delegateDecision"
	OperationCreateDecisionMessage             OperationID = "createDecisionMessage"
	OperationResolveDecision                   OperationID = "resolveDecision"
	OperationGetDeletionState                  OperationID = "getDeletionState"
	OperationPutDeploymentEvidenceProvider     OperationID = "putDeploymentEvidenceProvider"
	OperationGetDeploymentProof                OperationID = "getDeploymentProof"
	OperationIdentifyDeployment                OperationID = "identifyDeployment"
	OperationStreamMigrationEvents             OperationID = "streamMigrationEvents"
	OperationListGates                         OperationID = "listGates"
	OperationGetMigrationHealth                OperationID = "getMigrationHealth"
	OperationListIncidents                     OperationID = "listIncidents"
	OperationGetDecisionLedger                 OperationID = "getDecisionLedger"
	OperationRequestOperation                  OperationID = "requestOperation"
	OperationGetOperation                      OperationID = "getOperation"
	OperationCancelOperation                   OperationID = "cancelOperation"
	OperationRequestPhaseTransition            OperationID = "requestPhaseTransition"
	OperationRecordCustomerValidation          OperationID = "recordCustomerValidation"
	OperationDispatchExternalReview            OperationID = "dispatchExternalReview"
	OperationRequestReport                     OperationID = "requestReport"
	OperationGetReport                         OperationID = "getReport"
	OperationListRubrics                       OperationID = "listRubrics"
	OperationConfirmRubric                     OperationID = "confirmRubric"
	OperationListSpecs                         OperationID = "listSpecs"
	OperationConfirmSpec                       OperationID = "confirmSpec"
	OperationStartMigrationFromPrompt          OperationID = "startMigrationFromPrompt"
	OperationGetTrafficAuthority               OperationID = "getTrafficAuthority"
	OperationListWriterCohorts                 OperationID = "listWriterCohorts"
)

type Operation struct {
	Method              string
	Path                string
	Mutation            bool
	IdempotencyRequired bool
	ConcurrencyMode     string
	MaxBodyBytes        int64
	AllowedAudiences    []string
	RequestMediaType    string
	ManualRedirect      bool
}

var Operations = map[OperationID]Operation{
	OperationRequestApplicationWriterGrant:     {Method: "POST", Path: "/v1/application-writer/grants", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-application-writer"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationExchangeApplicationWriterIdentity: {Method: "POST", Path: "/v1/application-writer/identity-exchanges", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-application-writer"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCreateDeviceAuthorization:         {Method: "POST", Path: "/v1/auth/device/authorizations", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationApproveDeviceAuthorization:        {Method: "POST", Path: "/v1/auth/device/authorizations/approve", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationExchangeDeviceToken:               {Method: "POST", Path: "/v1/auth/device/token", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationLogoutSession:                     {Method: "POST", Path: "/v1/auth/logout", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationLogoutAllSessions:                 {Method: "POST", Path: "/v1/auth/logout-all", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCompleteIdentityOAuth:             {Method: "POST", Path: "/v1/auth/oauth/complete", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/x-www-form-urlencoded", ManualRedirect: true},
	OperationConsumeIdentityOAuthCallback:      {Method: "GET", Path: "/v1/auth/oauth/{provider}/callback", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"oauth-callback-transaction"}, RequestMediaType: "", ManualRedirect: false},
	OperationPrepareIdentityOAuthCallback:      {Method: "POST", Path: "/v1/auth/oauth/{provider}/prepare", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"oauth-callback-transaction"}, RequestMediaType: "application/x-www-form-urlencoded", ManualRedirect: true},
	OperationStartIdentityOAuth:                {Method: "POST", Path: "/v1/auth/oauth/{provider}/start", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetAuthSession:                    {Method: "GET", Path: "/v1/auth/session", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "", ManualRedirect: false},
	OperationListWebAuthnCredentials:           {Method: "GET", Path: "/v1/auth/webauthn/credentials", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "", ManualRedirect: false},
	OperationRevokeWebAuthnCredential:          {Method: "DELETE", Path: "/v1/auth/webauthn/credentials/{credential_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCreateWebAuthnRegistration:        {Method: "POST", Path: "/v1/auth/webauthn/registration/options", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationVerifyWebAuthnRegistration:        {Method: "POST", Path: "/v1/auth/webauthn/registration/verify", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCreateBrowserCeremony:             {Method: "POST", Path: "/v1/cli/browser-ceremonies", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetBrowserCeremony:                {Method: "GET", Path: "/v1/cli/browser-ceremonies/{ceremony_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-cli-human"}, RequestMediaType: "", ManualRedirect: false},
	OperationDecideBrowserCeremony:             {Method: "POST", Path: "/v1/cli/browser-ceremonies/{ceremony_id}/decision", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCompleteConnectorOAuth:            {Method: "POST", Path: "/v1/connectors/oauth/complete", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/x-www-form-urlencoded", ManualRedirect: true},
	OperationConsumeConnectorOAuthCallback:     {Method: "GET", Path: "/v1/connectors/{kind}/callback", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"oauth-callback-transaction"}, RequestMediaType: "", ManualRedirect: false},
	OperationPrepareConnectorOAuthCallback:     {Method: "POST", Path: "/v1/connectors/{kind}/oauth/prepare", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"oauth-callback-transaction"}, RequestMediaType: "application/x-www-form-urlencoded", ManualRedirect: true},
	OperationCompleteCellCertificateBootstrap:  {Method: "POST", Path: "/v1/internal/cell-certificates/bootstrap/complete", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 65536, AllowedAudiences: []string{"jumpship-cell-bootstrap"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRequestCellCertificateBootstrap:   {Method: "POST", Path: "/v1/internal/cell-certificates/bootstrap/request", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 65536, AllowedAudiences: []string{"jumpship-cell-bootstrap"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationAcceptWorkspaceInvitation:         {Method: "POST", Path: "/v1/invitations/accept", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetEnvironmentAgentIncapabilities: {Method: "GET", Path: "/v1/meta/agent-incapabilities", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent", "anonymous"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetMigrationAgentIncapabilities:   {Method: "GET", Path: "/v1/migrations/{migration_id}/agent-incapabilities", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationReceiveProviderWebhook:            {Method: "POST", Path: "/v1/webhooks/{provider}", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 2097152, AllowedAudiences: []string{"provider-webhook"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListWorkspaces:                    {Method: "GET", Path: "/v1/workspaces", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationCreateWorkspace:                   {Method: "POST", Path: "/v1/workspaces", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetWorkspace:                      {Method: "GET", Path: "/v1/workspaces/{workspace_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationUpdateWorkspace:                   {Method: "PATCH", Path: "/v1/workspaces/{workspace_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationInviteWorkspaceMember:             {Method: "POST", Path: "/v1/workspaces/{workspace_id}/invitations", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListWorkspaceMembers:              {Method: "GET", Path: "/v1/workspaces/{workspace_id}/members", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationUpdateWorkspaceMember:             {Method: "PATCH", Path: "/v1/workspaces/{workspace_id}/members/{user_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRemoveWorkspaceMember:             {Method: "DELETE", Path: "/v1/workspaces/{workspace_id}/members/{user_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListMigrations:                    {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationCreateMigration:                   {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetMigration:                      {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationUpdateMigration:                   {Method: "PATCH", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationAbortMigration:                    {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/abort", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetAccessManifest:                 {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/access-manifest", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetApplicationChangeSet:           {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/application-change-sets/{version}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetApplicationEstate:              {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/application-estate", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationAssignConsentApprover:             {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/approvers/{consent_kind}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRequestArtifactUpload:             {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/artifact-uploads", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListArtifacts:                     {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/artifacts", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationRequestArtifactAccess:             {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/artifacts/{artifact_id}/access", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListAttempts:                      {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/attempts", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListConnectorRecommendations:      {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connector-recommendations", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListConnectors:                    {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationConfigureDraftPRAuthority:         {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors/github/pr-authority", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationPutMongoDBCredential:              {Method: "PUT", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors/mongodb/credential", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 16384, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationDisconnectConnector:               {Method: "DELETE", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors/{connector_id}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationVerifyConnector:                   {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors/{connector_id}/verify", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationBeginConnectorGrant:               {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/connectors/{kind}/begin", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetConsent:                        {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/consents/{consent_kind}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "", ManualRedirect: false},
	OperationChallengeConsent:                  {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/consents/{consent_kind}/challenge", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationConfirmConsent:                    {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/consents/{consent_kind}/confirm", Mutation: true, IdempotencyRequired: false, ConcurrencyMode: "protocol_one_time_transaction", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationDeclineConsent:                    {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/consents/{consent_kind}/decline", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListConversations:                 {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/conversations", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationCreateConversation:                {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/conversations", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListConversationEvents:            {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/conversations/{conversation_id}/events", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationCreateConversationMessage:         {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/conversations/{conversation_id}/messages", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 65536, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListDecisions:                     {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/decisions", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetDecision:                       {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/decisions/{decision_key}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationDelegateDecision:                  {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/decisions/{decision_key}/delegate", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationCreateDecisionMessage:             {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/decisions/{decision_key}/messages", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 65536, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationResolveDecision:                   {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/decisions/{decision_key}/resolve", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetDeletionState:                  {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/deletion", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationPutDeploymentEvidenceProvider:     {Method: "PUT", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/deploy-units/{deploy_unit_id}/deployment-evidence-provider", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetDeploymentProof:                {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/deployments/{deployment_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationIdentifyDeployment:                {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/deployments/{deployment_id}/attest", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationStreamMigrationEvents:             {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/events", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListGates:                         {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/gates", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetMigrationHealth:                {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/health", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListIncidents:                     {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/incidents", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationGetDecisionLedger:                 {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/ledger", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationRequestOperation:                  {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/operations", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetOperation:                      {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/operations/{operation_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationCancelOperation:                   {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/operations/{operation_id}/cancel", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRequestPhaseTransition:            {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/phase-transitions", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRecordCustomerValidation:          {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/pull-requests/{pr_binding_id}/customer-validation", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationDispatchExternalReview:            {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/pull-requests/{pr_binding_id}/reviews/{reviewer}", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationRequestReport:                     {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/reports", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetReport:                         {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/reports/{report_id}", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListRubrics:                       {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/rubrics", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationConfirmRubric:                     {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/rubrics/{rubric_id}/confirm", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationListSpecs:                         {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/specs", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationConfirmSpec:                       {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/specs/{spec_id}/confirm", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationStartMigrationFromPrompt:          {Method: "POST", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/start", Mutation: true, IdempotencyRequired: true, ConcurrencyMode: "if_match_or_expected_version", MaxBodyBytes: 65536, AllowedAudiences: []string{"jumpship-browser"}, RequestMediaType: "application/json", ManualRedirect: false},
	OperationGetTrafficAuthority:               {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/traffic-authority", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
	OperationListWriterCohorts:                 {Method: "GET", Path: "/v1/workspaces/{workspace_id}/migrations/{migration_id}/writer-cohorts", Mutation: false, IdempotencyRequired: false, ConcurrencyMode: "strong_etag", MaxBodyBytes: 1048576, AllowedAudiences: []string{"jumpship-browser", "jumpship-cli-human", "jumpship-coding-agent"}, RequestMediaType: "", ManualRedirect: false},
}

type Request struct {
	Audience       string
	PathParameters map[string]string
	Query          url.Values
	Body           json.RawMessage
	Form           url.Values
	IdempotencyKey string
	IfMatch        string
	CSRFToken      string
	RequestID      string
}

type Response struct {
	StatusCode int
	Header     http.Header
	Body       []byte
}

type Problem struct {
	Type      string `json:"type"`
	Code      string `json:"code"`
	Status    int    `json:"status"`
	Detail    string `json:"detail"`
	RequestID string `json:"request_id"`
}

type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
}

func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" || parsed.User != nil || parsed.Fragment != "" {
		return nil, errors.New("invalid API base URL")
	}
	if !strings.HasSuffix(parsed.Path, "/") {
		parsed.Path += "/"
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: parsed, httpClient: httpClient}, nil
}

func (client *Client) Do(ctx context.Context, operationID OperationID, input Request) (Response, error) {
	operation, ok := Operations[operationID]
	if !ok {
		return Response{}, errors.New("unknown generated operation")
	}
	if !audienceAllowed(operation.AllowedAudiences, input.Audience) {
		return Response{}, errors.New("operation audience is not allowed")
	}
	if operation.IdempotencyRequired && input.IdempotencyKey == "" {
		return Response{}, errors.New("operation requires idempotency key")
	}
	if (operation.ConcurrencyMode == "if_match" || operation.ConcurrencyMode == "if_match_required") && input.IfMatch == "" {
		return Response{}, errors.New("operation requires If-Match")
	}
	var body []byte
	switch operation.RequestMediaType {
	case "application/json":
		if len(input.Form) != 0 {
			return Response{}, errors.New("JSON operation does not accept form fields")
		}
		body = input.Body
	case "application/x-www-form-urlencoded":
		if len(input.Body) != 0 {
			return Response{}, errors.New("form operation does not accept a JSON body")
		}
		body = []byte(input.Form.Encode())
	default:
		if len(input.Body) != 0 || len(input.Form) != 0 {
			return Response{}, errors.New("operation does not accept a request body")
		}
	}
	if operation.MaxBodyBytes > 0 && int64(len(body)) > operation.MaxBodyBytes {
		return Response{}, errors.New("request body exceeds contract limit")
	}
	rendered := operation.Path
	for name, value := range input.PathParameters {
		rendered = strings.ReplaceAll(rendered, "{"+name+"}", url.PathEscape(value))
	}
	if strings.ContainsAny(rendered, "{}") {
		return Response{}, errors.New("missing path parameter")
	}
	relative, err := url.Parse(strings.TrimPrefix(rendered, "/"))
	if err != nil {
		return Response{}, err
	}
	relative.RawQuery = input.Query.Encode()
	requestURL := client.baseURL.ResolveReference(relative)
	request, err := http.NewRequestWithContext(ctx, operation.Method, requestURL.String(), bytes.NewReader(body))
	if err != nil {
		return Response{}, err
	}
	request.Header.Set("Accept", "application/json, application/problem+json")
	if len(body) > 0 {
		request.Header.Set("Content-Type", operation.RequestMediaType)
	}
	if input.IdempotencyKey != "" {
		request.Header.Set("Idempotency-Key", input.IdempotencyKey)
	}
	if input.IfMatch != "" {
		request.Header.Set("If-Match", input.IfMatch)
	}
	if input.CSRFToken != "" {
		request.Header.Set("X-CSRF-Token", input.CSRFToken)
	}
	if input.RequestID != "" {
		request.Header.Set("X-Request-ID", input.RequestID)
	}
	httpClient := client.httpClient
	if operation.ManualRedirect {
		clone := *client.httpClient
		clone.CheckRedirect = func(_ *http.Request, _ []*http.Request) error { return http.ErrUseLastResponse }
		httpClient = &clone
	}
	response, err := httpClient.Do(request)
	if err != nil {
		return Response{}, err
	}
	defer response.Body.Close()
	const maxResponseBytes = int64(2 << 20)
	body, err = io.ReadAll(io.LimitReader(response.Body, maxResponseBytes+1))
	if err != nil {
		return Response{}, err
	}
	if int64(len(body)) > maxResponseBytes {
		return Response{}, errors.New("response exceeds contract limit")
	}
	result := Response{StatusCode: response.StatusCode, Header: response.Header.Clone(), Body: body}
	if response.StatusCode >= 400 {
		var problem Problem
		if err := json.Unmarshal(body, &problem); err != nil {
			return result, fmt.Errorf("API error %d", response.StatusCode)
		}
		return result, fmt.Errorf("API error %s (%d): %s", problem.Code, problem.Status, problem.Detail)
	}
	return result, nil
}

func audienceAllowed(allowed []string, audience string) bool {
	if audience == "" {
		return false
	}
	for _, candidate := range allowed {
		if candidate == audience {
			return true
		}
	}
	return false
}
