"""Generated TypeScript canonicalization client and cross-language vectors."""

from __future__ import annotations

import base64
import hashlib
import json

from model import Artifact, json_artifact, text_artifact


CANONICAL_TS = r'''// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.
// RFC 8785 JCS plus Jumpship typed detached-signature verification.

import type { PublicKeyRegistry, SignatureEnvelope } from "./contracts.gen.ts";

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue = JsonPrimitive | ReadonlyArray<JsonValue> | { readonly [key: string]: JsonValue };

export type SignatureClaims = Omit<SignatureEnvelope, "envelope_id" | "signature_base64">;
export type PublicKeyRecord = PublicKeyRegistry["keys"][number];

export interface VerifyExpectation {
  readonly objectType: string;
  readonly objectSchemaID: string;
  readonly objectSchemaVersion: string;
  readonly purpose: string;
  readonly environment: string;
  readonly tenantScope: string | null;
  readonly migrationScope: string | null;
  readonly registryHash: string;
  readonly at: Date;
}

const domainToken = /^[a-z0-9_-]{1,96}$/;
const schemaVersion = /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/;
const hashHex = /^[0-9a-f]{64}$/;
const canonicalBase64 = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;

function rejectLoneSurrogates(value: string): void {
  for (let index = 0; index < value.length; index += 1) {
    const unit = value.charCodeAt(index);
    if (unit >= 0xd800 && unit <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) throw new TypeError("lone high surrogate");
      index += 1;
    } else if (unit >= 0xdc00 && unit <= 0xdfff) {
      throw new TypeError("lone low surrogate");
    }
  }
}

function canonicalValue(value: JsonValue): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new TypeError("non-finite JSON number");
    return JSON.stringify(value);
  }
  if (typeof value === "string") {
    rejectLoneSurrogates(value);
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) return `[${value.map(canonicalValue).join(",")}]`;
  if (typeof value === "object") {
    const object = value as { readonly [key: string]: JsonValue };
    const keys = Object.keys(object).sort(); // ECMAScript UTF-16 code-unit ordering required by JCS.
    return `{${keys.map((key) => {
      rejectLoneSurrogates(key);
      return `${JSON.stringify(key)}:${canonicalValue(object[key])}`;
    }).join(",")}}`;
  }
  throw new TypeError("unsupported JSON value");
}

function strictParse(source: string): JsonValue {
  let offset = 0;
  const whitespace = () => { while (/[\u0009\u000a\u000d\u0020]/.test(source[offset] ?? "")) offset += 1; };
  const parseString = (): string => {
    const start = offset;
    if (source[offset] !== '"') throw new SyntaxError("expected JSON string");
    offset += 1;
    while (offset < source.length) {
      const current = source[offset++];
      if (current === '"') {
        const value = JSON.parse(source.slice(start, offset)) as string;
        rejectLoneSurrogates(value);
        return value;
      }
      if (current === "\\") {
        const escape = source[offset++];
        if (escape === "u") offset += 4;
      } else if (current.charCodeAt(0) < 0x20) {
        throw new SyntaxError("unescaped JSON control character");
      }
    }
    throw new SyntaxError("unterminated JSON string");
  };
  const parseValue = (): JsonValue => {
    whitespace();
    if (source[offset] === "{") {
      offset += 1;
      const object = Object.create(null) as { [key: string]: JsonValue };
      const names = new Set<string>();
      whitespace();
      if (source[offset] === "}") { offset += 1; return object; }
      while (true) {
        whitespace();
        const key = parseString();
        if (names.has(key)) throw new SyntaxError(`duplicate JSON object member: ${key}`);
        names.add(key);
        whitespace();
        if (source[offset++] !== ":") throw new SyntaxError("expected JSON colon");
        object[key] = parseValue();
        whitespace();
        const separator = source[offset++];
        if (separator === "}") return object;
        if (separator !== ",") throw new SyntaxError("expected JSON object separator");
      }
    }
    if (source[offset] === "[") {
      offset += 1;
      const array: JsonValue[] = [];
      whitespace();
      if (source[offset] === "]") { offset += 1; return array; }
      while (true) {
        array.push(parseValue());
        whitespace();
        const separator = source[offset++];
        if (separator === "]") return array;
        if (separator !== ",") throw new SyntaxError("expected JSON array separator");
      }
    }
    if (source[offset] === '"') return parseString();
    for (const [literal, value] of [["true", true], ["false", false], ["null", null]] as const) {
      if (source.startsWith(literal, offset)) { offset += literal.length; return value; }
    }
    const number = source.slice(offset).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/);
    if (!number) throw new SyntaxError("invalid JSON value");
    offset += number[0].length;
    const value = Number(number[0]);
    if (!Number.isFinite(value)) throw new TypeError("non-finite JSON number");
    return value;
  };
  const value = parseValue();
  whitespace();
  if (offset !== source.length) throw new SyntaxError("trailing JSON value");
  return value;
}

export function canonicalizeJson(input: string | JsonValue): string {
  const value = typeof input === "string" ? strictParse(input) : input;
  return canonicalValue(value);
}

function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
}

function base64Bytes(value: string): Uint8Array {
  if (!canonicalBase64.test(value)) throw new TypeError("invalid canonical base64");
  const decoded = atob(value);
  if (btoa(decoded) !== value) throw new TypeError("non-canonical base64 padding bits");
  return Uint8Array.from(decoded, (character) => character.charCodeAt(0));
}

function publicKeyDER(pem: string): Uint8Array {
  const match = pem.match(/^-----BEGIN PUBLIC KEY-----\r?\n([A-Za-z0-9+/=\r\n]+)-----END PUBLIC KEY-----(?:\r?\n)?$/);
  if (!match) throw new TypeError("invalid public-key PEM");
  return base64Bytes(match[1].replace(/[\r\n]/g, ""));
}

function claimsFromEnvelope(envelope: SignatureEnvelope): SignatureClaims {
  const { envelope_id: _id, signature_base64: _signature, ...claims } = envelope;
  return claims;
}

function ecdsaDERToRaw(signature: Uint8Array): Uint8Array {
  let offset = 0;
  const readLength = (limit: number): number => {
    if (offset >= limit) throw new TypeError("truncated ECDSA DER length");
    const first = signature[offset++];
    if (first < 0x80) return first;
    const count = first & 0x7f;
    if (count < 1 || count > 2 || offset + count > limit) throw new TypeError("invalid ECDSA DER length");
    if (signature[offset] === 0) throw new TypeError("non-minimal ECDSA DER length");
    let length = 0;
    for (let index = 0; index < count; index += 1) length = length * 256 + signature[offset++];
    if (length < 0x80) throw new TypeError("non-minimal ECDSA DER length");
    return length;
  };
  if (offset >= signature.length) throw new TypeError("truncated ECDSA DER sequence");
  if (signature[offset++] !== 0x30) throw new TypeError("invalid ECDSA DER sequence");
  const sequenceLength = readLength(signature.length);
  const sequenceEnd = offset + sequenceLength;
  if (sequenceEnd !== signature.length) throw new TypeError("invalid ECDSA DER size");
  const integers: Uint8Array[] = [];
  for (let part = 0; part < 2; part += 1) {
    if (offset >= sequenceEnd) throw new TypeError("truncated ECDSA DER integer");
    if (signature[offset++] !== 0x02) throw new TypeError("invalid ECDSA DER integer");
    const length = readLength(sequenceEnd);
    if (length === 0 || offset + length > sequenceEnd) throw new TypeError("invalid ECDSA DER integer length");
    const encoded = signature.slice(offset, offset + length);
    offset += length;
    if ((encoded[0] & 0x80) !== 0) throw new TypeError("negative ECDSA DER integer");
    if (encoded.length > 1 && encoded[0] === 0 && (encoded[1] & 0x80) === 0) {
      throw new TypeError("non-minimal ECDSA DER integer");
    }
    const integer = encoded.length > 1 && encoded[0] === 0 ? encoded.slice(1) : encoded;
    if (integer.every((byte) => byte === 0)) throw new TypeError("zero ECDSA P-256 integer");
    if (integer.length > 32) throw new TypeError("ECDSA P-256 integer overflow");
    const padded = new Uint8Array(32);
    padded.set(integer, 32 - integer.length);
    integers.push(padded);
  }
  if (offset !== sequenceEnd) throw new TypeError("trailing ECDSA DER sequence content");
  const raw = new Uint8Array(64);
  raw.set(integers[0]);
  raw.set(integers[1], 32);
  return raw;
}

export async function typedDigest(objectType: string, version: string, payload: string | JsonValue): Promise<string> {
  if (!domainToken.test(objectType) || !schemaVersion.test(version)) throw new TypeError("invalid typed-digest domain");
  const prefix = new TextEncoder().encode(`jumpship:${objectType}:${version}\0`);
  const canonical = new TextEncoder().encode(canonicalizeJson(payload));
  const bytes = new Uint8Array(prefix.length + canonical.length);
  bytes.set(prefix);
  bytes.set(canonical, prefix.length);
  return bytesToHex(new Uint8Array(await crypto.subtle.digest("SHA-256", bytes)));
}

export async function registryDigest(registry: PublicKeyRegistry): Promise<string> {
  const logicalBytes = new TextEncoder().encode(canonicalizeJson(registry as unknown as JsonValue));
  return bytesToHex(new Uint8Array(await crypto.subtle.digest("SHA-256", logicalBytes)));
}

function isJsonObject(value: JsonValue): value is { readonly [key: string]: JsonValue } {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

export async function verifyContentIdentity(input: string | JsonValue): Promise<boolean> {
  try {
    const value = typeof input === "string" ? strictParse(input) : input;
    if (!isJsonObject(value)) return false;
    const projectionValue = value.logical_payload_projection;
    if (!isJsonObject(projectionValue)) return false;
    const objectType = projectionValue.object_type;
    const idField = projectionValue.id_field;
    const objectSchemaVersion = projectionValue.object_schema_version;
    const excludedFields = projectionValue.excluded_fields;
    const equivalentFields = projectionValue.equivalent_digest_fields ?? [];
    if (typeof objectType !== "string" || typeof idField !== "string" || idField.length === 0 || typeof objectSchemaVersion !== "string") return false;
    if (projectionValue.canonical_encoder !== "RFC8785_JCS" || projectionValue.id_encoding !== "lowercase_hex_sha256" || projectionValue.id_equals_logical_payload_sha256 !== true) return false;
    if (projectionValue.domain_separator !== `jumpship:${objectType}:${objectSchemaVersion}\0`) return false;
    if (!Array.isArray(excludedFields) || !Array.isArray(equivalentFields)) return false;
    if (!excludedFields.every((field) => typeof field === "string" && field.length > 0) || !equivalentFields.every((field) => typeof field === "string" && field.length > 0)) return false;
    const exclusions = new Set(excludedFields as readonly string[]);
    const equivalents = new Set(equivalentFields as readonly string[]);
    if (exclusions.size !== excludedFields.length || equivalents.size !== equivalentFields.length) return false;
    if (!exclusions.has(idField) || !exclusions.has("logical_payload_sha256") || !exclusions.has("logical_payload_projection")) return false;
    if ([...equivalents].some((field) => !exclusions.has(field))) return false;
    const projected: { [key: string]: JsonValue } = Object.create(null) as { [key: string]: JsonValue };
    for (const [field, member] of Object.entries(value)) {
      if (!exclusions.has(field)) projected[field] = member;
    }
    const digest = await typedDigest(objectType, objectSchemaVersion, projected);
    for (const field of [idField, "logical_payload_sha256", ...equivalents]) {
      const actual = value[field];
      if (typeof actual !== "string" || !hashHex.test(actual) || actual !== digest) return false;
    }
    return true;
  } catch {
    return false;
  }
}

const catalogTopLevelFields = [
  "catalog_hash", "catalog_id", "items", "logical_payload_projection",
  "logical_payload_sha256", "schema_version", "source_registry_hash",
] as const;
const catalogBindingTopLevelFields = [
  "binding_hash", "binding_id", "catalog_hash", "catalog_id", "logical_payload_projection",
  "logical_payload_sha256", "release_unit_hash", "release_unit_id", "schema_version", "source_registry_hash",
] as const;
const catalogResponseTopLevelFields = [
  "catalog", "catalog_binding", "migration_id", "release_evidence_chain", "schema_version",
  "selection_mode", "served_at",
] as const;
const catalogProjectionFields = [
  "canonical_encoder", "domain_separator", "equivalent_digest_fields", "excluded_fields",
  "id_encoding", "id_equals_logical_payload_sha256", "id_field", "object_schema_version", "object_type",
] as const;
const catalogItemFields = [
  "capability_id", "coding_agent_denied", "incapability_id", "negative_test_receipt_hashes",
  "operation_id", "reason_code", "required_human_surface", "safe_explanation", "safe_remediation",
  "structural_denial_contract_ids",
] as const;
const catalogCapabilityID = /^MVP-CAP-[A-Z0-9][A-Z0-9-]+$/;
const catalogSafeToken = /^[A-Za-z0-9][A-Za-z0-9._:/@+\-]*$/;
const catalogMigrationID = /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

function hasExactKeys(value: { readonly [key: string]: JsonValue }, expected: readonly string[]): boolean {
  const actual = Object.keys(value).sort();
  const sortedExpected = [...expected].sort();
  return actual.length === sortedExpected.length && actual.every((field, index) => field === sortedExpected[index]);
}

function equalsStrings(value: JsonValue | undefined, expected: readonly string[]): boolean {
  return Array.isArray(value) && value.length === expected.length && value.every((field, index) => field === expected[index]);
}

function validCatalogToken(value: JsonValue | undefined): value is string {
  return typeof value === "string" && [...value].length >= 1 && [...value].length <= 128 && catalogSafeToken.test(value);
}

function validCatalogText(value: JsonValue | undefined): value is string {
  return typeof value === "string" && [...value].length >= 1 && [...value].length <= 2048;
}

function validCatalogStringArray(
  value: JsonValue | undefined,
  minimum: number,
  maximum: number,
  predicate: (field: JsonValue | undefined) => boolean,
): value is string[] {
  return Array.isArray(value) && value.length >= minimum && value.length <= maximum &&
    new Set(value).size === value.length && value.every((field) => predicate(field));
}

export async function verifyCustomerIncapabilityCatalog(input: string | JsonValue): Promise<boolean> {
  try {
    const value = typeof input === "string" ? strictParse(input) : input;
    if (!isJsonObject(value) || !hasExactKeys(value, catalogTopLevelFields)) return false;
    if (new TextEncoder().encode(canonicalizeJson(value)).length > 1_048_576) return false;
    const projection = value.logical_payload_projection;
    if (!isJsonObject(projection) || !hasExactKeys(projection, catalogProjectionFields)) return false;
    if (value.schema_version !== "2.0.0" || projection.object_type !== "customer_incapability_catalog" ||
      projection.id_field !== "catalog_id" || projection.object_schema_version !== "2.0.0" ||
      projection.canonical_encoder !== "RFC8785_JCS" ||
      projection.domain_separator !== "jumpship:customer_incapability_catalog:2.0.0\0" ||
      projection.id_encoding !== "lowercase_hex_sha256" || projection.id_equals_logical_payload_sha256 !== true ||
      !equalsStrings(projection.excluded_fields, ["catalog_id", "catalog_hash", "logical_payload_sha256", "logical_payload_projection"]) ||
      !equalsStrings(projection.equivalent_digest_fields, ["catalog_hash"])) return false;
    for (const field of ["catalog_id", "logical_payload_sha256", "catalog_hash", "source_registry_hash"] as const) {
      if (typeof value[field] !== "string" || !hashHex.test(value[field] as string)) return false;
    }
    if (!Array.isArray(value.items) || value.items.length < 1 || value.items.length > 2048) return false;
    let previousCapability = "";
    let previousIncapability = "";
    for (const item of value.items) {
      if (!isJsonObject(item) || !hasExactKeys(item, catalogItemFields)) return false;
      if (typeof item.capability_id !== "string" || [...item.capability_id].length > 128 || !catalogCapabilityID.test(item.capability_id) ||
        !validCatalogToken(item.incapability_id) || !validCatalogToken(item.operation_id) || !validCatalogToken(item.reason_code) ||
        !validCatalogText(item.safe_explanation) || !validCatalogText(item.safe_remediation) || item.coding_agent_denied !== true ||
        !["browser", "human_cli", "support", "unavailable"].includes(item.required_human_surface as string) ||
        !validCatalogStringArray(item.structural_denial_contract_ids, 1, 32, validCatalogToken) ||
        !validCatalogStringArray(item.negative_test_receipt_hashes, 1, 64, (field) => typeof field === "string" && hashHex.test(field))) return false;
      const capability = item.capability_id;
      const incapability = item.incapability_id;
      if (previousCapability !== "" && (capability < previousCapability || (capability === previousCapability && incapability <= previousIncapability))) return false;
      previousCapability = capability;
      previousIncapability = incapability;
    }
    return verifyContentIdentity(value);
  } catch {
    return false;
  }
}

export async function verifyCustomerIncapabilityCatalogBinding(input: string | JsonValue): Promise<boolean> {
  try {
    const value = typeof input === "string" ? strictParse(input) : input;
    if (!isJsonObject(value) || !hasExactKeys(value, catalogBindingTopLevelFields)) return false;
    if (new TextEncoder().encode(canonicalizeJson(value)).length > 16_384) return false;
    const projection = value.logical_payload_projection;
    if (!isJsonObject(projection) || !hasExactKeys(projection, catalogProjectionFields)) return false;
    if (value.schema_version !== "1.0.0" || projection.object_type !== "customer_incapability_catalog_binding" ||
      projection.id_field !== "binding_id" || projection.object_schema_version !== "1.0.0" ||
      projection.canonical_encoder !== "RFC8785_JCS" ||
      projection.domain_separator !== "jumpship:customer_incapability_catalog_binding:1.0.0\0" ||
      projection.id_encoding !== "lowercase_hex_sha256" || projection.id_equals_logical_payload_sha256 !== true ||
      !equalsStrings(projection.excluded_fields, ["binding_id", "binding_hash", "logical_payload_sha256", "logical_payload_projection"]) ||
      !equalsStrings(projection.equivalent_digest_fields, ["binding_hash"])) return false;
    for (const field of ["binding_id", "binding_hash", "logical_payload_sha256", "release_unit_id", "release_unit_hash", "catalog_id", "catalog_hash", "source_registry_hash"] as const) {
      if (typeof value[field] !== "string" || !hashHex.test(value[field] as string)) return false;
    }
    if (value.release_unit_id !== value.release_unit_hash || value.catalog_id !== value.catalog_hash) return false;
    return verifyContentIdentity(value);
  } catch {
    return false;
  }
}

export async function verifyCustomerIncapabilityCatalogResponse(input: string | JsonValue): Promise<boolean> {
  try {
    const value = typeof input === "string" ? strictParse(input) : input;
    if (!isJsonObject(value) || !hasExactKeys(value, catalogResponseTopLevelFields)) return false;
    if (new TextEncoder().encode(canonicalizeJson(value)).length > 1_081_344) return false;
    if (value.schema_version !== "1.0.0" ||
      (value.selection_mode !== "new_admission_release" && value.selection_mode !== "pinned_cell_release_binding")) return false;
    if (value.migration_id !== null && (typeof value.migration_id !== "string" || !catalogMigrationID.test(value.migration_id))) return false;
    if (typeof value.served_at !== "string" || strictRFC3339Nanos(value.served_at) === null) return false;
    if (!validCatalogStringArray(value.release_evidence_chain, 1, 64, (field) => typeof field === "string" && hashHex.test(field))) return false;
    if (!await verifyCustomerIncapabilityCatalog(value.catalog) ||
      !await verifyCustomerIncapabilityCatalogBinding(value.catalog_binding)) return false;
    if (!isJsonObject(value.catalog) || !isJsonObject(value.catalog_binding)) return false;
    return value.catalog_binding.catalog_id === value.catalog.catalog_id &&
      value.catalog_binding.catalog_hash === value.catalog.catalog_hash &&
      value.catalog_binding.source_registry_hash === value.catalog.source_registry_hash;
  } catch {
    return false;
  }
}

export async function verifyCustomerIncapabilityCatalogAssociation(
  catalogInput: string | JsonValue,
  bindingInput: string | JsonValue,
  releaseUnitInput: string | JsonValue,
): Promise<boolean> {
  try {
    const catalog = typeof catalogInput === "string" ? strictParse(catalogInput) : catalogInput;
    const binding = typeof bindingInput === "string" ? strictParse(bindingInput) : bindingInput;
    const releaseUnit = typeof releaseUnitInput === "string" ? strictParse(releaseUnitInput) : releaseUnitInput;
    if (!await verifyCustomerIncapabilityCatalog(catalog) ||
      !await verifyCustomerIncapabilityCatalogBinding(binding) ||
      !await verifyContentIdentity(releaseUnit) || !isJsonObject(catalog) || !isJsonObject(binding) ||
      !isJsonObject(releaseUnit)) return false;
    if (binding.release_unit_id !== releaseUnit.release_unit_id || binding.release_unit_hash !== releaseUnit.release_unit_id ||
      binding.catalog_id !== catalog.catalog_id || binding.catalog_hash !== catalog.catalog_hash ||
      binding.source_registry_hash !== catalog.source_registry_hash ||
      releaseUnit.customer_incapability_catalog_hash !== catalog.catalog_hash ||
      releaseUnit.customer_incapability_source_registry_hash !== catalog.source_registry_hash ||
      !Array.isArray(releaseUnit.members)) return false;
    const catalogMembers = releaseUnit.members.filter(
      (member) => isJsonObject(member) && member.kind === "customer_incapability_catalog",
    );
    return catalogMembers.length === 1 && isJsonObject(catalogMembers[0]) &&
      catalogMembers[0].object_id === catalog.catalog_id && catalogMembers[0].content_sha256 === catalog.catalog_hash;
  } catch {
    return false;
  }
}

function strictRFC3339Nanos(value: string): bigint | null {
  const match = value.match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.(\d{1,9}))?Z$/);
  if (!match) return null;
  const [, yearText, monthText, dayText, hourText, minuteText, secondText, fractionText = ""] = match;
  const year = Number(yearText), month = Number(monthText), day = Number(dayText);
  const hour = Number(hourText), minute = Number(minuteText), second = Number(secondText);
  if (month < 1 || month > 12 || day < 1 || day > 31 || hour > 23 || minute > 59 || second > 59) return null;
  const millisecond = Number(fractionText.padEnd(3, "0").slice(0, 3));
  const calendar = new Date(0);
  calendar.setUTCFullYear(year, month - 1, day);
  calendar.setUTCHours(hour, minute, second, millisecond);
  if (!Number.isFinite(calendar.getTime()) || calendar.getUTCFullYear() !== year || calendar.getUTCMonth() !== month - 1 || calendar.getUTCDate() !== day || calendar.getUTCHours() !== hour || calendar.getUTCMinutes() !== minute || calendar.getUTCSeconds() !== second || calendar.getUTCMilliseconds() !== millisecond) return null;
  const fractionalNanos = BigInt(fractionText.padEnd(9, "0") || "0");
  return BigInt(calendar.getTime() - millisecond) * 1_000_000n + fractionalNanos;
}

export async function validatePublicKeyRegistry(registry: PublicKeyRegistry): Promise<boolean> {
  try {
  if (registry.schema_version !== "1.0.0" || registry.registry_version < 1 || registry.keys.length < 1) return false;
  if (!hashHex.test(registry.registry_id) || !hashHex.test(registry.root_fingerprint) || !hashHex.test(registry.purpose_policy_hash)) return false;
  if (registry.registry_version === 1 ? registry.previous_registry_hash !== null : registry.previous_registry_hash === null || !hashHex.test(registry.previous_registry_hash)) return false;
  if (strictRFC3339Nanos(registry.issued_at) === null) return false;
  const kids = new Set(registry.keys.map((candidate) => candidate.kid));
  if (kids.size !== registry.keys.length) return false;
  const parentByKid = new Map<string, string>();
  for (const candidate of registry.keys) {
    const validFrom = strictRFC3339Nanos(candidate.valid_from);
    const validUntil = strictRFC3339Nanos(candidate.valid_until);
    if (validFrom === null || validUntil === null || validFrom > validUntil) return false;
    const revokedAt = candidate.revoked_at === null ? null : strictRFC3339Nanos(candidate.revoked_at);
    if (candidate.status === "revoked") {
      if (revokedAt === null || candidate.revocation_reason === null || revokedAt < validFrom) return false;
    } else if (candidate.status === "active" || candidate.status === "superseded") {
      if (candidate.revoked_at !== null || candidate.revocation_reason !== null) return false;
    } else {
      return false;
    }
    if (candidate.algorithm === "ECDSA_P256_SHA256") {
      const imported = await crypto.subtle.importKey("spki", publicKeyDER(candidate.public_key_pem), { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
      if (imported.algorithm.name !== "ECDSA" || (imported.algorithm as EcKeyAlgorithm).namedCurve !== "P-256") return false;
    } else if (candidate.algorithm === "RSA_PSS_SHA256") {
      const imported = await crypto.subtle.importKey("spki", publicKeyDER(candidate.public_key_pem), { name: "RSA-PSS", hash: "SHA-256" }, false, ["verify"]);
      if (imported.algorithm.name !== "RSA-PSS" || (imported.algorithm as RsaHashedKeyAlgorithm).modulusLength < 2048) return false;
    } else {
      return false;
    }
    if (candidate.supersedes_kid !== null) {
      if (candidate.supersedes_kid === candidate.kid) return false;
      const prior = registry.keys.find((item) => item.kid === candidate.supersedes_kid);
      if (!prior || prior.status !== "superseded" || prior.algorithm !== candidate.algorithm) return false;
      parentByKid.set(candidate.kid, candidate.supersedes_kid);
    }
  }
  const visited = new Set<string>();
  for (const kid of kids) {
    const path = new Set<string>();
    let current: string | undefined = kid;
    while (current !== undefined && !visited.has(current)) {
      if (path.has(current)) return false;
      path.add(current);
      current = parentByKid.get(current);
    }
    for (const member of path) visited.add(member);
  }
  return true;
  } catch {
    return false;
  }
}

export async function verifyDetached(
  payload: string | JsonValue,
  envelope: SignatureEnvelope,
  registry: PublicKeyRegistry,
  expected: VerifyExpectation,
): Promise<boolean> {
  const claims = claimsFromEnvelope(envelope);
  const at = expected.at.getTime();
  if (!Number.isFinite(at)) return false;
  const atNanos = BigInt(at) * 1_000_000n;
  if (claims.schema_version !== "1.0.0" || claims.object_type !== expected.objectType || claims.object_schema_id !== expected.objectSchemaID || claims.object_schema_version !== expected.objectSchemaVersion || claims.purpose !== expected.purpose) return false;
  if (claims.environment !== expected.environment || claims.tenant_scope !== expected.tenantScope || claims.migration_scope !== expected.migrationScope) return false;
  if (claims.key_registry_id !== registry.registry_id || claims.key_registry_hash !== expected.registryHash || expected.registryHash !== await registryDigest(registry)) return false;
  if (claims.payload_digest !== await typedDigest(claims.object_type, claims.object_schema_version, payload)) return false;
  if (envelope.envelope_id !== await typedDigest("signature_envelope", claims.schema_version, claims as unknown as JsonValue)) return false;
  if (!await validatePublicKeyRegistry(registry)) return false;
  const registryIssuedAt = strictRFC3339Nanos(registry.issued_at);
  if (registryIssuedAt === null || registryIssuedAt > atNanos) return false;
  const key = registry.keys.find((candidate) => candidate.kid === claims.kid);
  if (!key || key.status !== "active" || claims.algorithm !== key.algorithm) return false;
  if (!key.purposes.includes(claims.purpose) || !key.environments.includes(claims.environment) || key.tenant_scope !== claims.tenant_scope) return false;
  const issuedAt = strictRFC3339Nanos(claims.issued_at);
  const keyValidFrom = strictRFC3339Nanos(key.valid_from);
  const keyValidUntil = strictRFC3339Nanos(key.valid_until);
  if (issuedAt === null || keyValidFrom === null || keyValidUntil === null || issuedAt > atNanos || issuedAt < keyValidFrom || issuedAt > keyValidUntil) return false;
  if (atNanos < keyValidFrom || atNanos > keyValidUntil) return false;
  const revokedAt = key.revoked_at === null ? null : strictRFC3339Nanos(key.revoked_at);
  if (key.revoked_at !== null && (revokedAt === null || atNanos >= revokedAt)) return false;
  if (claims.expires_at !== null) {
    const expiresAt = strictRFC3339Nanos(claims.expires_at);
    if (expiresAt === null || expiresAt < issuedAt || atNanos > expiresAt) return false;
  }
  try {
    const claimsBytes = new TextEncoder().encode(canonicalizeJson(claims as unknown as JsonValue));
    const signature = base64Bytes(envelope.signature_base64);
    if (claims.algorithm === "ECDSA_P256_SHA256") {
      const publicKey = await crypto.subtle.importKey("spki", publicKeyDER(key.public_key_pem), { name: "ECDSA", namedCurve: "P-256" }, false, ["verify"]);
      return crypto.subtle.verify({ name: "ECDSA", hash: "SHA-256" }, publicKey, ecdsaDERToRaw(signature), claimsBytes);
    }
    if (claims.algorithm !== "RSA_PSS_SHA256") return false;
    const publicKey = await crypto.subtle.importKey("spki", publicKeyDER(key.public_key_pem), { name: "RSA-PSS", hash: "SHA-256" }, false, ["verify"]);
    return crypto.subtle.verify({ name: "RSA-PSS", saltLength: 32 }, publicKey, signature, claimsBytes);
  } catch {
    return false;
  }
}
'''


CANONICAL_TEST_TS = r'''// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { canonicalizeJson, registryDigest, typedDigest, validatePublicKeyRegistry, verifyContentIdentity, verifyCustomerIncapabilityCatalog, verifyCustomerIncapabilityCatalogAssociation, verifyCustomerIncapabilityCatalogBinding, verifyCustomerIncapabilityCatalogResponse, verifyDetached, type JsonValue, type SignatureClaims } from "./canonical.gen.ts";
import type { PublicKeyRegistry, SignatureEnvelope } from "./contracts.gen.ts";

interface Vector { name: string; object_type: string; schema_version: string; input: string; canonical: string; digest: string }

interface SignatureFixture {
  readonly payload: JsonValue;
  readonly registry: PublicKeyRegistry;
  readonly registry_hash: string;
  readonly expected: {
    readonly object_type: string;
    readonly object_schema_id: string;
    readonly object_schema_version: string;
    readonly purpose: string;
    readonly environment: string;
    readonly tenant_scope: string | null;
    readonly migration_scope: string | null;
    readonly at: string;
  };
  readonly vectors: ReadonlyArray<{ readonly name: string; readonly envelope: SignatureEnvelope }>;
  readonly negative_ecdsa_der_vectors: ReadonlyArray<{ readonly name: string; readonly signature_base64: string }>;
}

test("cross-language RFC 8785 and typed digest vectors", async () => {
  const document = JSON.parse(await readFile("contracts/fixtures/canonicalization-vectors.json", "utf8")) as { vectors: Vector[] };
  assert.ok(document.vectors.length >= 3);
  for (const vector of document.vectors) {
    assert.equal(canonicalizeJson(vector.input), vector.canonical, vector.name);
    assert.equal(await typedDigest(vector.object_type, vector.schema_version, vector.input), vector.digest, vector.name);
  }
});

test("canonicalizer rejects unsafe values", () => {
  assert.throws(() => canonicalizeJson({ value: Number.POSITIVE_INFINITY } as unknown as JsonValue));
  assert.throws(() => canonicalizeJson({ value: "\ud800" }));
  assert.throws(() => canonicalizeJson('{"duplicate":1,"duplicate":2}'));
  assert.throws(() => canonicalizeJson('{"number":1e999}'));
});

test("shared ECDSA and RSA-PSS detached-signature vectors verify", async () => {
  const fixture = JSON.parse(await readFile("contracts/fixtures/signature-verification-vectors.json", "utf8")) as SignatureFixture;
  assert.equal(await registryDigest(fixture.registry), fixture.registry_hash);
  assert.equal(await validatePublicKeyRegistry(fixture.registry), true);
  const expected = {
    objectType: fixture.expected.object_type,
    objectSchemaID: fixture.expected.object_schema_id,
    objectSchemaVersion: fixture.expected.object_schema_version,
    purpose: fixture.expected.purpose,
    environment: fixture.expected.environment,
    tenantScope: fixture.expected.tenant_scope,
    migrationScope: fixture.expected.migration_scope,
    registryHash: fixture.registry_hash,
    at: new Date(fixture.expected.at),
  };
  const algorithms = new Set<string>();
  for (const vector of fixture.vectors) {
    algorithms.add(vector.envelope.algorithm);
    assert.equal(await verifyDetached(fixture.payload, vector.envelope, fixture.registry, expected), true, vector.name);
  }
  assert.deepEqual([...algorithms].sort(), ["ECDSA_P256_SHA256", "RSA_PSS_SHA256"]);

  const envelope = fixture.vectors.find((vector) => vector.envelope.algorithm === "ECDSA_P256_SHA256")?.envelope;
  assert.ok(envelope, "shared fixture must contain an ECDSA vector");
  assert.deepEqual(
    fixture.negative_ecdsa_der_vectors.map((vector) => vector.name).sort(),
    [
      "appended-byte",
      "extra-sequence-content",
      "indefinite-length",
      "integer-overrun",
      "missing-required-leading-zero",
      "negative-integer",
      "non-minimal-length-leading-zero",
      "non-minimal-long-form-length",
      "unnecessary-leading-zero",
      "zero-integer",
      "zero-length-integer",
    ],
  );
  for (const vector of fixture.negative_ecdsa_der_vectors) {
    assert.equal(
      await verifyDetached(fixture.payload, { ...envelope, signature_base64: vector.signature_base64 }, fixture.registry, expected),
      false,
      vector.name,
    );
  }
  for (const signature_base64 of ["AA-A", "AAAAA", "AB==", "AAAA\n"]) {
    assert.equal(await verifyDetached(fixture.payload, { ...envelope, signature_base64 }, fixture.registry, expected), false, signature_base64);
  }
  assert.equal(await verifyDetached(fixture.payload, { ...envelope, issued_at: "2026-07-18T01:00:00+00:00" }, fixture.registry, expected), false);
});

test("public-key registry rejects invalid genesis and supersession cycles", async () => {
  const fixture = JSON.parse(await readFile("contracts/fixtures/signature-verification-vectors.json", "utf8")) as SignatureFixture;
  assert.equal(await validatePublicKeyRegistry({ ...fixture.registry, previous_registry_hash: fixture.registry_hash }), false);
  assert.equal(await validatePublicKeyRegistry({ ...fixture.registry, registry_version: 2, previous_registry_hash: null }), false);
  assert.equal(await validatePublicKeyRegistry({ ...fixture.registry, issued_at: "2026-07-18T00:00:00+00:00" }), false);
  assert.equal(await validatePublicKeyRegistry({ ...fixture.registry, issued_at: "2026-07-18T00:00:00.1234567890Z" }), false);
  const self = structuredClone(fixture.registry);
  self.keys[0].status = "superseded";
  self.keys[0].supersedes_kid = self.keys[0].kid;
  assert.equal(await validatePublicKeyRegistry(self), false);
  const cycle = structuredClone(fixture.registry);
  const cycleKid = "fixture-ecdsa-cycle";
  cycle.keys[0].status = "superseded";
  cycle.keys[0].supersedes_kid = cycleKid;
  cycle.keys.push({ ...cycle.keys[0], kid: cycleKid, supersedes_kid: cycle.keys[0].kid });
  assert.equal(await validatePublicKeyRegistry(cycle), false);
  const malformedKey = structuredClone(fixture.registry);
  malformedKey.keys[0].public_key_pem = "-----BEGIN PUBLIC KEY-----\nAAAA\n-----END PUBLIC KEY-----\n";
  assert.equal(await validatePublicKeyRegistry(malformedKey), false);
  const mismatchedKey = structuredClone(fixture.registry);
  mismatchedKey.keys[0].algorithm = "RSA_PSS_SHA256";
  assert.equal(await validatePublicKeyRegistry(mismatchedKey), false);
  const revokedWithoutMetadata = structuredClone(fixture.registry);
  revokedWithoutMetadata.keys[0].status = "revoked";
  assert.equal(await validatePublicKeyRegistry(revokedWithoutMetadata), false);
  const activeWithMetadata = structuredClone(fixture.registry);
  activeWithMetadata.keys[0].revoked_at = "2026-07-18T00:30:00Z";
  activeWithMetadata.keys[0].revocation_reason = "compromised";
  assert.equal(await validatePublicKeyRegistry(activeWithMetadata), false);
  const unsupported = structuredClone(fixture.registry) as unknown as { keys: Array<{ algorithm: string; status: string }> };
  unsupported.keys[0].algorithm = "UNSUPPORTED";
  unsupported.keys[0].status = "unknown";
  assert.equal(await validatePublicKeyRegistry(unsupported as unknown as PublicKeyRegistry), false);
});

type MutableJsonObject = { [key: string]: JsonValue };

async function reidentifyForTest(input: JsonValue, mutate: (object: MutableJsonObject) => void): Promise<JsonValue> {
  const object = structuredClone(input) as MutableJsonObject;
  mutate(object);
  const projection = object.logical_payload_projection as MutableJsonObject;
  const objectType = projection.object_type as string;
  const version = projection.object_schema_version as string;
  const idField = projection.id_field as string;
  const excluded = projection.excluded_fields as ReadonlyArray<string>;
  const equivalents = (projection.equivalent_digest_fields ?? []) as ReadonlyArray<string>;
  const projected: MutableJsonObject = Object.create(null) as MutableJsonObject;
  for (const [field, value] of Object.entries(object)) {
    if (!excluded.includes(field)) projected[field] = value;
  }
  const digest = await typedDigest(objectType, version, projected);
  object[idField] = digest;
  object.logical_payload_sha256 = digest;
  for (const field of equivalents) object[field] = digest;
  return object;
}

test("shared catalog fixture enforces typed identity and strict unique ordering", async () => {
  const fixture = JSON.parse(await readFile("contracts/fixtures/client/valid-customer-incapability-catalog.json", "utf8")) as { instance: JsonValue };
  const bindingFixture = JSON.parse(await readFile("contracts/fixtures/client/valid-customer-incapability-catalog-binding.json", "utf8")) as { instance: JsonValue };
  const responseFixture = JSON.parse(await readFile("contracts/fixtures/client/valid-customer-incapability-catalog-response.json", "utf8")) as { instance: JsonValue };
  assert.equal(await verifyContentIdentity(fixture.instance), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(fixture.instance), true);
  assert.equal(await verifyCustomerIncapabilityCatalogBinding(bindingFixture.instance), true);
  assert.equal(await verifyCustomerIncapabilityCatalogResponse(responseFixture.instance), true);
  const responseMetadataChanged = structuredClone(responseFixture.instance) as MutableJsonObject;
  responseMetadataChanged.selection_mode = "pinned_cell_release_binding";
  responseMetadataChanged.migration_id = "018f0f7e-7b8a-7abc-8def-0123456789ab";
  responseMetadataChanged.release_evidence_chain = ["7".repeat(64)];
  responseMetadataChanged.served_at = "2026-07-19T00:00:00Z";
  assert.equal(await verifyCustomerIncapabilityCatalogResponse(responseMetadataChanged), true);
  assert.deepEqual(responseMetadataChanged.catalog, (responseFixture.instance as MutableJsonObject).catalog);
  const oldFlat = structuredClone(fixture.instance) as MutableJsonObject;
  oldFlat.schema_version = "1.0.0";
  oldFlat.release_unit_id = "2".repeat(64);
  assert.equal(await verifyCustomerIncapabilityCatalog(oldFlat), false);
  assert.equal(await verifyCustomerIncapabilityCatalog(responseFixture.instance), false);
  const tampered = structuredClone(fixture.instance) as unknown as { items: Array<{ safe_explanation: string }> };
  tampered.items[0].safe_explanation = "Semantically changed while holding every digest field fixed.";
  assert.equal(await verifyContentIdentity(tampered as unknown as JsonValue), false);
  const reversed = await reidentifyForTest(fixture.instance, (object) => {
    const items = object.items as unknown as MutableJsonObject[];
    items.reverse();
  });
  assert.equal(await verifyContentIdentity(reversed), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(reversed), false);
  const duplicate = await reidentifyForTest(fixture.instance, (object) => {
    const items = object.items as unknown as MutableJsonObject[];
    items[1].capability_id = items[0].capability_id;
    items[1].incapability_id = items[0].incapability_id;
  });
  assert.equal(await verifyContentIdentity(duplicate), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(duplicate), false);
  const attackerProjection = await reidentifyForTest(fixture.instance, (object) => {
    const projection = object.logical_payload_projection as MutableJsonObject;
    projection.object_type = "attacker_catalog";
    projection.id_field = "attacker_id";
    projection.domain_separator = "jumpship:attacker_catalog:2.0.0\0";
    projection.excluded_fields = ["attacker_id", "logical_payload_sha256", "logical_payload_projection"];
    projection.equivalent_digest_fields = [];
  });
  assert.equal(await verifyContentIdentity(attackerProjection), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(attackerProjection), false);
  const unknownItemField = await reidentifyForTest(fixture.instance, (object) => {
    const items = object.items as unknown as MutableJsonObject[];
    items[0].unexpected_authority = true;
  });
  assert.equal(await verifyContentIdentity(unknownItemField), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(unknownItemField), false);
  const missingItemField = await reidentifyForTest(fixture.instance, (object) => {
    const items = object.items as unknown as MutableJsonObject[];
    delete items[0].reason_code;
  });
  assert.equal(await verifyContentIdentity(missingItemField), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(missingItemField), false);
  const oversized = await reidentifyForTest(fixture.instance, (object) => {
    const items = object.items as unknown as MutableJsonObject[];
    const template = items[items.length - 1];
    for (let index = 0; index < 300; index += 1) {
      const item = structuredClone(template);
      item.capability_id = `MVP-CAP-Z${index.toString().padStart(4, "0")}`;
      item.incapability_id = `cannot-oversize-${index.toString().padStart(4, "0")}`;
      item.safe_explanation = "x".repeat(2048);
      item.safe_remediation = "y".repeat(2048);
      items.push(item);
    }
  });
  assert.ok(new TextEncoder().encode(canonicalizeJson(oversized)).length > 1_048_576);
  assert.equal(await verifyContentIdentity(oversized), true);
  assert.equal(await verifyCustomerIncapabilityCatalog(oversized), false);

  const catalog = fixture.instance as MutableJsonObject;
  const releaseUnit = await reidentifyForTest({
    schema_version: "1.0.0",
    release_unit_id: "0".repeat(64),
    logical_payload_sha256: "0".repeat(64),
    logical_payload_projection: {
      object_type: "release_unit",
      id_field: "release_unit_id",
      object_schema_version: "1.0.0",
      canonical_encoder: "RFC8785_JCS",
      domain_separator: "jumpship:release_unit:1.0.0\0",
      excluded_fields: ["release_unit_id", "logical_payload_sha256", "logical_payload_projection"],
      equivalent_digest_fields: [],
      id_encoding: "lowercase_hex_sha256",
      id_equals_logical_payload_sha256: true,
    },
    customer_incapability_catalog_hash: catalog.catalog_hash,
    customer_incapability_source_registry_hash: catalog.source_registry_hash,
    members: [{ kind: "customer_incapability_catalog", object_id: catalog.catalog_id, content_sha256: catalog.catalog_hash }],
  }, () => {});
  const releaseUnitID = (releaseUnit as MutableJsonObject).release_unit_id;
  const associationBinding = await reidentifyForTest(bindingFixture.instance, (object) => {
    object.release_unit_id = releaseUnitID;
    object.release_unit_hash = releaseUnitID;
  });
  assert.equal(await verifyCustomerIncapabilityCatalogAssociation(fixture.instance, associationBinding, releaseUnit), true);
  const substitutedBinding = await reidentifyForTest(associationBinding, (object) => {
    object.source_registry_hash = "8".repeat(64);
  });
  assert.equal(await verifyCustomerIncapabilityCatalogBinding(substitutedBinding), true);
  assert.equal(await verifyCustomerIncapabilityCatalogAssociation(fixture.instance, substitutedBinding, releaseUnit), false);
});

function base64(bytes: Uint8Array): string {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary);
}

function publicKeyPEM(bytes: Uint8Array): string {
  const encoded = base64(bytes);
  const lines = encoded.match(/.{1,64}/g) ?? [];
  return `-----BEGIN PUBLIC KEY-----\n${lines.join("\n")}\n-----END PUBLIC KEY-----`;
}

test("detached signature denies tamper/replay/supersession and preserves re-sign identity", async () => {
  const payload: JsonValue = { schema_version: "1.0.0", value: "stable" };
  const keys = await crypto.subtle.generateKey({ name: "RSA-PSS", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" }, true, ["sign", "verify"]);
  const successorKeys = await crypto.subtle.generateKey({ name: "RSA-PSS", modulusLength: 2048, publicExponent: new Uint8Array([1, 0, 1]), hash: "SHA-256" }, true, ["sign", "verify"]);
  const publicKey = new Uint8Array(await crypto.subtle.exportKey("spki", keys.publicKey));
  const successorPublicKey = new Uint8Array(await crypto.subtle.exportKey("spki", successorKeys.publicKey));
  const tenant = "018f1234-5678-7abc-8def-0123456789ab";
  const registryID = "a".repeat(64);
  const registry: PublicKeyRegistry = {
    schema_version: "1.0.0", registry_id: registryID, registry_version: 1, previous_registry_hash: null,
    root_fingerprint: "c".repeat(64), purpose_policy_hash: "d".repeat(64), issued_at: "2026-07-18T00:00:00Z",
    keys: [{ kid: "release-a", algorithm: "RSA_PSS_SHA256", public_key_pem: publicKeyPEM(publicKey), purposes: ["release_evidence"],
      environments: ["staging"], tenant_scope: tenant, valid_from: "2026-07-18T00:00:00Z", valid_until: "2026-07-19T00:00:00Z",
      status: "active", supersedes_kid: null, revoked_at: null, revocation_reason: null }],
  };
  const registryHash = await registryDigest(registry);
  const claims: SignatureClaims = {
    schema_version: "1.0.0", object_type: "release_unit",
    object_schema_id: "https://jumpship.dev/contracts/release/release-unit.schema.json", object_schema_version: "1.0.0",
    payload_digest: await typedDigest("release_unit", "1.0.0", payload), purpose: "release_evidence", environment: "staging",
    tenant_scope: tenant, migration_scope: null, kid: "release-a", algorithm: "RSA_PSS_SHA256",
    signer_id: "release-workflow", signer_role: "release-evidence", issued_at: "2026-07-18T01:00:00Z", expires_at: null,
    key_registry_id: registryID, key_registry_hash: registryHash,
  };
  const claimsBytes = new TextEncoder().encode(canonicalizeJson(claims as unknown as JsonValue));
  const signature = new Uint8Array(await crypto.subtle.sign({ name: "RSA-PSS", saltLength: 32 }, keys.privateKey, claimsBytes));
  const envelope = { ...claims, envelope_id: await typedDigest("signature_envelope", "1.0.0", claims as unknown as JsonValue), signature_base64: base64(signature) };
  const expected = { objectType: "release_unit", objectSchemaID: claims.object_schema_id, objectSchemaVersion: "1.0.0", purpose: "release_evidence", environment: "staging", tenantScope: tenant, migrationScope: null, registryHash, at: new Date("2026-07-18T01:01:00Z") };
  assert.equal(await verifyDetached(payload, envelope, registry, expected), true);
  assert.equal(await verifyDetached(payload, envelope, { ...registry, root_fingerprint: "e".repeat(64) }, expected), false);
  assert.equal(await verifyDetached(payload, envelope, registry, { ...expected, at: new Date(Number.NaN) }), false);
  assert.equal(await verifyDetached(payload, envelope, { ...registry, issued_at: "2026-02-30T00:00:00Z" }, expected), false);
  assert.equal(await verifyDetached(payload, envelope, { ...registry, keys: [{ ...registry.keys[0], valid_until: "2026-13-01T00:00:00Z" }] }, expected), false);
  assert.equal(await verifyDetached({ schema_version: "1.0.0", value: "tampered" }, envelope, registry, expected), false);
  const signatureTamper = `${envelope.signature_base64[0] === "A" ? "B" : "A"}${envelope.signature_base64.slice(1)}`;
  assert.equal(await verifyDetached(payload, { ...envelope, signature_base64: signatureTamper }, registry, expected), false);
  assert.equal(await verifyDetached(payload, envelope, registry, { ...expected, purpose: "bundle_promotion" }), false);
  assert.equal(await verifyDetached(payload, envelope, registry, { ...expected, objectType: "qualification_record" }), false);
  assert.equal(await verifyDetached(payload, envelope, registry, { ...expected, objectSchemaVersion: "2.0.0" }), false);
  const identityBefore = claims.payload_digest;
  const resigned = new Uint8Array(await crypto.subtle.sign({ name: "RSA-PSS", saltLength: 32 }, keys.privateKey, claimsBytes));
  assert.equal(claims.payload_digest, identityBefore);
  assert.notEqual(base64(resigned), envelope.signature_base64);
  assert.equal(await typedDigest("signature_envelope", "1.0.0", claims as unknown as JsonValue), envelope.envelope_id);
  const successor: PublicKeyRegistry = { ...registry, registry_id: "f".repeat(64), registry_version: 2, previous_registry_hash: registryHash, keys: [
    { ...registry.keys[0], status: "superseded" },
    { ...registry.keys[0], kid: "release-b", public_key_pem: publicKeyPEM(successorPublicKey), status: "active", supersedes_kid: "release-a" },
  ] };
  const successorHash = await registryDigest(successor);
  const oldKeyClaims: SignatureClaims = { ...claims, key_registry_id: successor.registry_id, key_registry_hash: successorHash };
  const oldKeyClaimsBytes = new TextEncoder().encode(canonicalizeJson(oldKeyClaims as unknown as JsonValue));
  const oldKeySignature = new Uint8Array(await crypto.subtle.sign({ name: "RSA-PSS", saltLength: 32 }, keys.privateKey, oldKeyClaimsBytes));
  const oldKeyEnvelope = { ...oldKeyClaims, envelope_id: await typedDigest("signature_envelope", "1.0.0", oldKeyClaims as unknown as JsonValue), signature_base64: base64(oldKeySignature) };
  const successorExpected = { ...expected, registryHash: successorHash, at: new Date("2026-07-18T02:00:00Z") };
  assert.equal(await verifyDetached(payload, oldKeyEnvelope, successor, successorExpected), false);
  const newKeyClaims: SignatureClaims = { ...oldKeyClaims, kid: "release-b" };
  const newKeyClaimsBytes = new TextEncoder().encode(canonicalizeJson(newKeyClaims as unknown as JsonValue));
  const newKeySignature = new Uint8Array(await crypto.subtle.sign({ name: "RSA-PSS", saltLength: 32 }, successorKeys.privateKey, newKeyClaimsBytes));
  const newKeyEnvelope = { ...newKeyClaims, envelope_id: await typedDigest("signature_envelope", "1.0.0", newKeyClaims as unknown as JsonValue), signature_base64: base64(newKeySignature) };
  assert.equal(await verifyDetached(payload, newKeyEnvelope, successor, successorExpected), true);
  assert.equal(newKeyEnvelope.payload_digest, identityBefore);
});
'''


def _vectors() -> dict:
    source = [
        (
            "key-order-unicode",
            "release_unit",
            "1.0.0",
            '{"z":1,"a":"é","nested":{"β":2,"a":true}}',
            '{"a":"é","nested":{"a":true,"β":2},"z":1}',
        ),
        (
            "ieee754-number-edges",
            "eval_report",
            "1.0.0",
            '{"n":[1e30,0.002,1e-7,1e20,-0.0,333333333.33333329]}',
            '{"n":[1e+30,0.002,1e-7,100000000000000000000,0,333333333.3333333]}',
        ),
        (
            "utf16-property-order",
            "integrity_envelope",
            "1.0.0",
            '{"":1,"😀":2,"a":"line\\nfeed"}',
            '{"a":"line\\nfeed","😀":2,"":1}',
        ),
    ]
    vectors = []
    for name, object_type, version, input_value, canonical in source:
        domain = f"jumpship:{object_type}:{version}\0".encode("utf-8")
        digest = hashlib.sha256(domain + canonical.encode("utf-8")).hexdigest()
        vectors.append(
            {
                "name": name,
                "object_type": object_type,
                "schema_version": version,
                "input": input_value,
                "canonical": canonical,
                "digest": digest,
            }
        )
    return {
        "_generated": "generated by internal/contracts/codegen/generate.py; DO NOT EDIT",
        "schema_version": "1.0.0",
        "encoder": "RFC8785-JCS",
        "domain_rule": "SHA-256(jumpship:<object-type>:<schema-version>\\u0000 || canonical_payload)",
        "vectors": vectors,
        "negative_vectors": [
            {"name": "duplicate-key", "input": '{"a":1,"a":2}', "expected": "reject"},
            {"name": "lone-surrogate", "input": '{"a":"\\ud800"}', "expected": "reject"},
            {"name": "non-finite", "input": '{"a":1e999}', "expected": "reject"},
        ],
    }


def _signature_vectors() -> dict:
    """Static cross-runtime signatures over one shared registry and payload.

    The private keys are intentionally not shipped.  These immutable public
    verification vectors were produced once with OpenSSL using ECDSA P-256 and
    RSA-PSS/SHA-256 (32-byte salt); generation recomputes every unsigned digest
    so accidental edits fail deterministically.
    """

    tenant = "018f1234-5678-7abc-8def-0123456789ab"
    registry_id = "a" * 64
    ecdsa_public_key = (
        "-----BEGIN PUBLIC KEY-----\n"
        "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEvNr7H6uDZ60wJz1gMRgrePoSZHT2\n"
        "vRHEvnGznGcMAeMNdDIMo2mHtGXyWkcAXI9sL0D6cQz3hr8xER5RYQ8I4w==\n"
        "-----END PUBLIC KEY-----\n"
    )
    rsa_public_key = (
        "-----BEGIN PUBLIC KEY-----\n"
        "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAojBxUCIPnzkkQ8xLJT5f\n"
        "h5RngdLiqiTN60sdKS+FNTXmpuLtTyQzZqsIBpWyn4OuT8zxTXHeJ2Ci1nJO2els\n"
        "K7JC/rvCJQ2bYe71T18CQ0InMjD1xsAVmrsI2DC3KvqR4UlghpgapDnNb610Ylsi\n"
        "qybLjFxRBzvCXt+35Mz34AY5FaIP/A8Ftl7gdzsJ+twQbrH15hP0Lh743ARDiCtH\n"
        "4/49BDgetyhYI9hvkIZe6csgv4db1+eda4HXvd2UKmrZ16HG6Z6tblROnVxn2b1i\n"
        "NGYtwPu7nzzbgNYZs0FQN55cXscOedKcBGV6EDc1B/Vrog1TKxp8sX8kQCDGGknh\n"
        "6QIDAQAB\n"
        "-----END PUBLIC KEY-----\n"
    )
    key_common = {
        "purposes": ["release_evidence"],
        "environments": ["staging"],
        "tenant_scope": tenant,
        "valid_from": "2026-07-18T00:00:00Z",
        "valid_until": "2026-07-19T00:00:00Z",
        "status": "active",
        "supersedes_kid": None,
        "revoked_at": None,
        "revocation_reason": None,
    }
    registry = {
        "schema_version": "1.0.0",
        "registry_id": registry_id,
        "registry_version": 1,
        "previous_registry_hash": None,
        "root_fingerprint": "c" * 64,
        "purpose_policy_hash": "d" * 64,
        "issued_at": "2026-07-18T00:00:00.123456789Z",
        "keys": [
            {
                "kid": "fixture-ecdsa",
                "algorithm": "ECDSA_P256_SHA256",
                "public_key_pem": ecdsa_public_key,
                **key_common,
            },
            {
                "kid": "fixture-rsa",
                "algorithm": "RSA_PSS_SHA256",
                "public_key_pem": rsa_public_key,
                **key_common,
            },
        ],
    }
    registry_canonical = json.dumps(
        registry, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    registry_hash = hashlib.sha256(registry_canonical).hexdigest()
    expected_registry_hash = (
        "8eeea0de6d176b8f07c3d3cd660d602935b4fe2b21d9a7af2a910335f11306c7"
    )
    if registry_hash != expected_registry_hash:
        raise AssertionError("shared signature registry changed without re-signing vectors")

    payload = {"schema_version": "1.0.0", "value": "shared-stable"}
    payload_canonical = json.dumps(
        payload, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode("utf-8")
    payload_digest = hashlib.sha256(
        b"jumpship:release_unit:1.0.0\0" + payload_canonical
    ).hexdigest()

    def envelope(kid: str, algorithm: str, signature: str) -> dict:
        claims = {
            "schema_version": "1.0.0",
            "object_type": "release_unit",
            "object_schema_id": (
                "https://jumpship.dev/contracts/release/release-unit.schema.json"
            ),
            "object_schema_version": "1.0.0",
            "payload_digest": payload_digest,
            "purpose": "release_evidence",
            "environment": "staging",
            "tenant_scope": tenant,
            "migration_scope": None,
            "kid": kid,
            "algorithm": algorithm,
            "signer_id": "fixture-signer",
            "signer_role": "release-evidence",
            "issued_at": "2026-07-18T01:00:00.123456789Z",
            "expires_at": None,
            "key_registry_id": registry_id,
            "key_registry_hash": registry_hash,
        }
        canonical_claims = json.dumps(
            claims, ensure_ascii=False, separators=(",", ":"), sort_keys=True
        ).encode("utf-8")
        envelope_id = hashlib.sha256(
            b"jumpship:signature_envelope:1.0.0\0" + canonical_claims
        ).hexdigest()
        return {
            **claims,
            "envelope_id": envelope_id,
            "signature_base64": signature,
        }

    ecdsa_signature = (
        "MEYCIQCWK4YqsynTPiSoGgG1rKnXMkasDjwpFIXDRQyJDFL0DgIhAKIqEpcknhPtWZebNmyqXyUFYc5b+W5bBhxbJ6ZBSGf8"
    )
    rsa_signature = (
        "IKel4Q5lrvpRekPvUo2r+CQiDWEQ5PIfIYhIzQoJzZtT1WhjcbKZ/SLP2u5CjbHp1hiPNKhm6noQuBfHuOv8TNAuXA92z938lvoGxihrjtHgl8IRJ+1ENCDi7Fnj40woSlErPbRaCxdeC5G7nY8fyJhGfyTt0vIygfHuk6EIJQiSgcv37x7nY6Jco7RHgagzoe6gEiZ4KrehC+tPK6FNYlrnWsI9W3GW7w3BmkSVb/H5Arqkg66Jr1mJ8aapXnKrNsr2QC8zAz8PNDxS+OT7q0RfVK65It5rtm3mZNVMu6EjWFnX3zpCQUvC20Ik4hygBi/I6CI4Kuwca9AHJdPt3A=="
    )
    valid_der = base64.b64decode(ecdsa_signature, validate=True)
    if valid_der[:2] != bytes((0x30, len(valid_der) - 2)):
        raise AssertionError("shared ECDSA fixture must use a short-form DER sequence")
    offset = 2
    if valid_der[offset] != 0x02:
        raise AssertionError("shared ECDSA fixture is missing r")
    r_length = valid_der[offset + 1]
    r = valid_der[offset + 2 : offset + 2 + r_length]
    offset += 2 + r_length
    if valid_der[offset] != 0x02:
        raise AssertionError("shared ECDSA fixture is missing s")
    s_length = valid_der[offset + 1]
    s = valid_der[offset + 2 : offset + 2 + s_length]
    offset += 2 + s_length
    if offset != len(valid_der) or len(r) != 33 or len(s) != 33:
        raise AssertionError("shared ECDSA fixture changed DER shape")
    if r[0] != 0 or s[0] != 0 or not (r[1] & 0x80) or not (s[1] & 0x80):
        raise AssertionError("shared ECDSA fixture must exercise required leading zeros")

    def der_length(length: int) -> bytes:
        if length < 0x80:
            return bytes((length,))
        encoded = length.to_bytes((length.bit_length() + 7) // 8, "big")
        return bytes((0x80 | len(encoded),)) + encoded

    def der_integer(encoded: bytes) -> bytes:
        return b"\x02" + der_length(len(encoded)) + encoded

    def der_sequence(content: bytes) -> bytes:
        return b"\x30" + der_length(len(content)) + content

    valid_body = der_integer(r) + der_integer(s)
    malformed_der = {
        "appended-byte": valid_der + b"\x00",
        "extra-sequence-content": der_sequence(valid_body + der_integer(b"\x01")),
        "indefinite-length": b"\x30\x80" + valid_body + b"\x00\x00",
        "integer-overrun": der_sequence(b"\x02" + der_length(len(r)) + r[:-1]),
        "missing-required-leading-zero": der_sequence(der_integer(r[1:]) + der_integer(s)),
        "negative-integer": der_sequence(der_integer(b"\xff" + r[1:]) + der_integer(s)),
        "non-minimal-long-form-length": b"\x30\x81" + bytes((len(valid_body),)) + valid_body,
        "non-minimal-length-leading-zero": b"\x30\x82\x00" + bytes((len(valid_body),)) + valid_body,
        "unnecessary-leading-zero": der_sequence(der_integer(b"\x00" + r) + der_integer(s)),
        "zero-integer": der_sequence(der_integer(b"\x00") + der_integer(s)),
        "zero-length-integer": der_sequence(der_integer(b"") + der_integer(s)),
    }

    return {
        "_generated": "generated by internal/contracts/codegen/generate.py; DO NOT EDIT",
        "schema_version": "1.0.0",
        "payload": payload,
        "registry": registry,
        "registry_hash": registry_hash,
        "expected": {
            "object_type": "release_unit",
            "object_schema_id": (
                "https://jumpship.dev/contracts/release/release-unit.schema.json"
            ),
            "object_schema_version": "1.0.0",
            "purpose": "release_evidence",
            "environment": "staging",
            "tenant_scope": tenant,
            "migration_scope": None,
            "at": "2026-07-18T01:01:00Z",
        },
        "vectors": [
            {
                "name": "ecdsa-p256-sha256",
                "envelope": envelope(
                    "fixture-ecdsa",
                    "ECDSA_P256_SHA256",
                    ecdsa_signature,
                ),
            },
            {
                "name": "rsa-pss-sha256",
                "envelope": envelope(
                    "fixture-rsa",
                    "RSA_PSS_SHA256",
                    rsa_signature,
                ),
            },
        ],
        "negative_ecdsa_der_vectors": [
            {
                "name": name,
                "signature_base64": base64.b64encode(signature).decode("ascii"),
            }
            for name, signature in malformed_der.items()
        ],
    }


def artifacts() -> dict[str, Artifact]:
    return {
        "contracts/fixtures/canonicalization-vectors.json": json_artifact(_vectors(), "application/json"),
        "contracts/fixtures/signature-verification-vectors.json": json_artifact(
            _signature_vectors(), "application/json"
        ),
        "web/src/lib/api/generated/canonical.gen.ts": text_artifact(CANONICAL_TS, "text/typescript"),
        "web/src/lib/api/generated/canonical.test.ts": text_artifact(CANONICAL_TEST_TS, "text/typescript"),
        "web/src/lib/api/generated/index.ts": text_artifact(
            "// Code generated by internal/contracts/codegen/generate.py; DO NOT EDIT.\n"
            'export * from "./canonical.gen.ts";\n'
            'export * from "./contracts.gen.ts";\n'
            'export * from "./openapi.gen.ts";\n',
            "text/typescript",
        ),
    }
